-- =============================================================
-- HYPE LOUNGE CLUB // V18 COMPLETO
-- 1) Sorteios por evento (somente ingressos PAGOS participam)
-- 2) Computador da Portaria vinculado/autorizado pelo Admin
-- 3) Celular como leitor QR pareado por QR temporario
-- 4) Portaria sem senha compartilhada + suporte a contingencia offline
-- 5) Preserva promoter global e vendas manuais/WhatsApp existentes
--
-- EXECUTE UMA VEZ no Supabase > SQL Editor > New query > Run.
-- Este patch e ADITIVO: nao apaga ingressos, pagamentos, eventos ou promoters.
-- =============================================================

create extension if not exists pgcrypto;

-- -------------------------------------------------------------
-- PRE-REQUISITOS V16/V12 (idempotentes)
-- Deixa este V18 seguro mesmo se algum patch antigo nao tiver sido
-- executado: somente adiciona campos/tabelas que estiverem faltando.
-- -------------------------------------------------------------
alter table public.ticket_lots
  add column if not exists auto_sequence boolean not null default false,
  add column if not exists price_female numeric(12,2),
  add column if not exists price_male numeric(12,2);

alter table public.tickets
  add column if not exists email text,
  add column if not exists original_price numeric(12,2),
  add column if not exists discount_amount numeric(12,2) not null default 0,
  add column if not exists coupon_code text,
  add column if not exists promoter_code text,
  add column if not exists service_fee numeric(12,2) not null default 0;

update public.tickets
set original_price = coalesce(original_price, greatest(price - coalesce(service_fee,0),0)),
    discount_amount = coalesce(discount_amount,0)
where original_price is null or discount_amount is null;

create table if not exists public.promoters_v16 (
  id bigint generated by default as identity primary key,
  event_id bigint not null references public.events(id) on delete cascade,
  name text not null,
  code text not null,
  active boolean not null default true,
  created_at timestamptz not null default now(),
  unique(event_id, code)
);

create index if not exists idx_promoters_v16_event
  on public.promoters_v16(event_id, active);

create table if not exists public.coupons_v16 (
  id bigint generated by default as identity primary key,
  event_id bigint not null references public.events(id) on delete cascade,
  code text not null,
  discount_type text not null default 'percent' check (discount_type in ('percent','fixed')),
  discount_value numeric(12,2) not null default 0 check (discount_value >= 0),
  usage_limit integer not null default 0 check (usage_limit >= 0),
  starts_at timestamptz,
  ends_at timestamptz,
  active boolean not null default true,
  created_at timestamptz not null default now(),
  unique(event_id, code)
);

create index if not exists idx_coupons_v16_event
  on public.coupons_v16(event_id, active);

revoke all on public.promoters_v16, public.coupons_v16 from anon, authenticated;


-- -------------------------------------------------------------
-- PROMOTER GLOBAL + PEDIDO MANUAL (base V16.8, incorporada no V18)
-- -------------------------------------------------------------
-- =============================================================
-- HYPE V16.8 - PROMOTER GLOBAL
-- Um unico promoter/link funciona em TODOS os eventos atuais e futuros.
-- Execute UMA VEZ no Supabase > SQL Editor > New query > Run.
-- NAO apaga ingressos, pagamentos, eventos, lotes ou historico de vendas.
-- =============================================================

create extension if not exists pgcrypto;

alter table public.tickets
  add column if not exists service_fee numeric(12,2) not null default 0;

-- 1) Cadastro global de promoters, sem vinculo obrigatorio com evento.
create table if not exists public.promoters_global_v16 (
  id bigint generated by default as identity primary key,
  name text not null,
  code text not null unique,
  active boolean not null default true,
  created_at timestamptz not null default now()
);

create index if not exists idx_promoters_global_v16_active
  on public.promoters_global_v16(active, created_at desc);

-- Migra os promoters ja existentes. Se o mesmo codigo existir em mais de
-- um evento, vira um unico promoter global.
insert into public.promoters_global_v16(name, code, active)
select
  min(trim(p.name)) as name,
  upper(trim(p.code)) as code,
  bool_or(p.active) as active
from public.promoters_v16 p
where coalesce(trim(p.code),'') <> ''
group by upper(trim(p.code))
on conflict (code) do nothing;

revoke all on public.promoters_global_v16 from anon, authenticated;

-- 2) Lista global + ranking calculado por TODAS as vendas.
drop function if exists public.staff_list_promoters_global_v16(text,text);
create function public.staff_list_promoters_global_v16(
  p_username text,
  p_password text
)
returns table(
  id bigint,
  name text,
  code text,
  active boolean,
  sales_count bigint,
  paid_count bigint,
  revenue numeric
)
language plpgsql
security definer
set search_path=public,extensions
as $$
declare v_staff public.staff_users%rowtype;
begin
  select s.* into v_staff
  from public.staff_users s
  where s.username=trim(p_username)
    and s.active=true
    and s.password_hash=crypt(p_password,s.password_hash)
  limit 1;

  if not found or v_staff.role<>'admin' then raise exception 'Sem permissao'; end if;

  return query
  select
    p.id,p.name,p.code,p.active,
    count(t.id) filter(where t.payment_status in ('Pendente','Pago'))::bigint,
    count(t.id) filter(where t.payment_status='Pago')::bigint,
    coalesce(sum(t.price) filter(where t.payment_status='Pago'),0)::numeric
  from public.promoters_global_v16 p
  left join public.tickets t
    on upper(coalesce(t.promoter_code,''))=upper(p.code)
  group by p.id
  order by 6 desc, 5 desc, p.created_at desc;
end;
$$;

grant execute on function public.staff_list_promoters_global_v16(text,text)
to anon, authenticated;

-- 3) Criar/editar/desativar promoter global.
drop function if exists public.staff_upsert_promoter_global_v16(text,text,bigint,text,text,boolean);
create function public.staff_upsert_promoter_global_v16(
  p_username text,
  p_password text,
  p_id bigint,
  p_name text,
  p_code text,
  p_active boolean
)
returns public.promoters_global_v16
language plpgsql
security definer
set search_path=public,extensions
as $$
declare
  v_staff public.staff_users%rowtype;
  v_row public.promoters_global_v16%rowtype;
  v_code text:=upper(trim(p_code));
begin
  select s.* into v_staff
  from public.staff_users s
  where s.username=trim(p_username)
    and s.active=true
    and s.password_hash=crypt(p_password,s.password_hash)
  limit 1;

  if not found or v_staff.role<>'admin' then raise exception 'Sem permissao'; end if;
  if coalesce(trim(p_name),'')='' or v_code='' then raise exception 'Informe nome e codigo do promoter'; end if;

  if coalesce(p_id,0)=0 then
    insert into public.promoters_global_v16(name,code,active)
    values(trim(p_name),v_code,coalesce(p_active,true))
    returning * into v_row;
  else
    update public.promoters_global_v16 p
    set name=trim(p_name), code=v_code, active=coalesce(p_active,true)
    where p.id=p_id
    returning * into v_row;
    if not found then raise exception 'Promoter nao encontrado'; end if;
  end if;

  return v_row;
exception when unique_violation then
  raise exception 'Este codigo de promoter ja existe';
end;
$$;

grant execute on function public.staff_upsert_promoter_global_v16(text,text,bigint,text,text,boolean)
to anon, authenticated;

-- 4) Excluir promoter global. Vendas antigas continuam com promoter_code.
drop function if exists public.staff_delete_promoter_global_v16(text,text,bigint);
create function public.staff_delete_promoter_global_v16(
  p_username text,
  p_password text,
  p_id bigint
)
returns boolean
language plpgsql
security definer
set search_path=public,extensions
as $$
declare v_staff public.staff_users%rowtype;
begin
  select s.* into v_staff
  from public.staff_users s
  where s.username=trim(p_username)
    and s.active=true
    and s.password_hash=crypt(p_password,s.password_hash)
  limit 1;

  if not found or v_staff.role<>'admin' then raise exception 'Sem permissao'; end if;

  delete from public.promoters_global_v16 p where p.id=p_id;
  if not found then raise exception 'Promoter nao encontrado'; end if;
  return true;
end;
$$;

grant execute on function public.staff_delete_promoter_global_v16(text,text,bigint)
to anon, authenticated;

-- 5) Pedido V16 atualizado: o promoter agora e validado GLOBALMENTE.
-- Mantem cupom por evento, lotes automaticos e taxa de servico R$ 1,98.
drop function if exists public.create_manual_order_v12(text,text,text,bigint,text,text);
drop function if exists public.create_manual_order_v16(text,text,text,text,text,bigint,text,text);

create function public.create_manual_order_v16(
  p_name text,
  p_phone text,
  p_email text,
  p_cpf text,
  p_gender text,
  p_lot_id bigint,
  p_coupon_code text default null,
  p_promoter_code text default null
)
returns table(
  id bigint,event_id bigint,ticket_code text,qr_token text,customer_name text,phone text,email text,cpf text,gender text,
  lot_id bigint,lot_name text,sector text,price numeric,original_price numeric,discount_amount numeric,coupon_code text,promoter_code text,
  payment_status text,entry_status text,purchased_at timestamptz
)
language plpgsql
security definer
set search_path = public, extensions
as $$
declare
  v_lot public.ticket_lots%rowtype;
  v_event public.events%rowtype;
  v_coupon public.coupons_v16%rowtype;
  v_promoter public.promoters_global_v16%rowtype;
  v_used integer;
  v_previous_open integer := 0;
  v_original numeric(12,2);
  v_discount numeric(12,2) := 0;
  v_ticket_value numeric(12,2);
  v_service_fee numeric(12,2) := 1.98;
  v_final numeric(12,2);
  v_coupon_used bigint := 0;
  v_coupon_code text := upper(trim(coalesce(p_coupon_code,'')));
  v_promoter_code text := upper(trim(coalesce(p_promoter_code,'')));
  v_id bigint;
  v_code text;
  v_qr text;
  v_purchased timestamptz;
begin
  if coalesce(trim(p_name),'')='' then raise exception 'Nome do cliente e obrigatorio'; end if;
  if coalesce(trim(p_email),'')='' or position('@' in p_email)=0 then raise exception 'E-mail invalido'; end if;
  if p_gender not in ('Feminino','Masculino') then raise exception 'Selecione Feminino ou Masculino'; end if;

  select l.* into v_lot
  from public.ticket_lots l
  where l.id=p_lot_id
  for update;

  if not found or not v_lot.active then raise exception 'Categoria indisponivel'; end if;

  select e.* into v_event
  from public.events e
  where e.id=v_lot.event_id;

  if not found or not v_event.active then raise exception 'Evento indisponivel'; end if;
  if v_lot.starts_at is not null and now()<v_lot.starts_at then raise exception 'As vendas desta categoria ainda nao comecaram'; end if;
  if v_lot.ends_at is not null and now()>=v_lot.ends_at then raise exception 'As vendas desta categoria ja encerraram'; end if;

  if coalesce(v_lot.auto_sequence,false) then
    select count(*)::integer into v_previous_open
    from public.ticket_lots p
    where p.event_id=v_lot.event_id
      and lower(coalesce(p.sector,''))=lower(coalesce(v_lot.sector,''))
      and p.active=true
      and (p.sort_order<v_lot.sort_order or (p.sort_order=v_lot.sort_order and p.id<v_lot.id))
      and (
        p.quantity_total=0
        or (
          select count(*) from public.tickets tp
          where tp.lot_id=p.id and tp.payment_status in ('Pendente','Pago')
        ) < p.quantity_total
      );
    if v_previous_open>0 then raise exception 'Este lote sera liberado automaticamente quando o anterior esgotar'; end if;
  end if;

  select count(*)::integer into v_used
  from public.tickets t
  where t.lot_id=v_lot.id and t.payment_status in ('Pendente','Pago');

  if v_lot.quantity_total>0 and v_used>=v_lot.quantity_total then raise exception 'Categoria esgotada'; end if;

  v_original := case
    when p_gender='Masculino' then coalesce(v_lot.price_male,v_lot.price,0)
    else coalesce(v_lot.price_female,v_lot.price,0)
  end;

  if v_coupon_code<>'' then
    select c.* into v_coupon
    from public.coupons_v16 c
    where c.event_id=v_lot.event_id
      and upper(c.code)=v_coupon_code
      and c.active=true
    for update;

    if not found then raise exception 'Cupom invalido'; end if;
    if v_coupon.starts_at is not null and now()<v_coupon.starts_at then raise exception 'Cupom ainda nao iniciou'; end if;
    if v_coupon.ends_at is not null and now()>=v_coupon.ends_at then raise exception 'Cupom expirado'; end if;

    select count(*)::bigint into v_coupon_used
    from public.tickets t
    where t.event_id=v_lot.event_id
      and upper(coalesce(t.coupon_code,''))=v_coupon_code
      and t.payment_status in ('Pendente','Pago');

    if v_coupon.usage_limit>0 and v_coupon_used>=v_coupon.usage_limit then raise exception 'Limite do cupom atingido'; end if;

    if v_coupon.discount_type='percent' then
      v_discount := round(v_original*least(v_coupon.discount_value,100)/100,2);
    else
      v_discount := least(v_original,v_coupon.discount_value);
    end if;
  end if;

  -- V16.8: valida o promoter na lista GLOBAL, sem comparar event_id.
  if v_promoter_code<>'' then
    select p.* into v_promoter
    from public.promoters_global_v16 p
    where upper(p.code)=v_promoter_code
      and p.active=true
    limit 1;
    if not found then raise exception 'Codigo de promoter invalido'; end if;
  end if;

  v_ticket_value := greatest(v_original-v_discount,0);
  if v_ticket_value<=0 then raise exception 'O desconto precisa deixar um valor maior que zero para pagamento PIX'; end if;
  v_final := round(v_ticket_value + v_service_fee, 2);

  loop
    v_code := 'HYPE-'||upper(substr(md5(random()::text||clock_timestamp()::text),1,10));
    exit when not exists(select 1 from public.tickets t where t.ticket_code=v_code);
  end loop;

  v_qr := gen_random_uuid()::text;

  insert into public.tickets(
    event_id,lot_id,customer_name,phone,email,cpf,gender,
    price,original_price,discount_amount,service_fee,
    coupon_code,promoter_code,ticket_code,qr_token,payment_status,entry_status
  ) values(
    v_lot.event_id,v_lot.id,trim(p_name),trim(p_phone),lower(trim(p_email)),trim(p_cpf),p_gender,
    v_final,v_original,v_discount,v_service_fee,
    nullif(v_coupon_code,''),nullif(v_promoter_code,''),v_code,v_qr,'Pendente','Não utilizado'
  )
  returning tickets.id,tickets.purchased_at into v_id,v_purchased;

  return query select
    v_id,v_lot.event_id,v_code,v_qr,trim(p_name),trim(p_phone),lower(trim(p_email)),trim(p_cpf),p_gender,
    v_lot.id,v_lot.name,v_lot.sector,v_final,v_original,v_discount,
    nullif(v_coupon_code,''),nullif(v_promoter_code,''),
    'Pendente'::text,'Não utilizado'::text,v_purchased;
end;
$$;

grant execute on function public.create_manual_order_v16(text,text,text,text,text,bigint,text,text)
to anon, authenticated;

-- Compatibilidade com navegador antigo em cache.
create function public.create_manual_order_v12(
  p_cpf text,
  p_email text,
  p_gender text,
  p_lot_id bigint,
  p_name text,
  p_phone text
)
returns table(
  id bigint,event_id bigint,ticket_code text,qr_token text,customer_name text,phone text,email text,cpf text,gender text,
  lot_id bigint,lot_name text,sector text,price numeric,original_price numeric,discount_amount numeric,coupon_code text,promoter_code text,
  payment_status text,entry_status text,purchased_at timestamptz
)
language sql
security definer
set search_path = public, extensions
as $$
  select * from public.create_manual_order_v16(
    p_name,p_phone,p_email,p_cpf,p_gender,p_lot_id,null,null
  );
$$;

grant execute on function public.create_manual_order_v12(text,text,text,bigint,text,text)
to anon, authenticated;

-- -------------------------------------------------------------
-- BASE NECESSARIA PARA PORTARIA PRO
-- -------------------------------------------------------------
alter table public.tickets
  add column if not exists document_checked boolean not null default false,
  add column if not exists document_checked_at timestamptz,
  add column if not exists document_checked_by text,
  add column if not exists temporary_exit boolean not null default false,
  add column if not exists temporary_exit_at timestamptz,
  add column if not exists reentry_authorized boolean not null default false,
  add column if not exists reentry_authorized_at timestamptz,
  add column if not exists reentry_authorized_by text,
  add column if not exists reentry_count integer not null default 0,
  add column if not exists last_entry_device text;

-- -------------------------------------------------------------
-- SORTEIOS V18
-- -------------------------------------------------------------
alter table public.events
  add column if not exists raffle_enabled boolean not null default false,
  add column if not exists raffle_prize text not null default '';

create table if not exists public.raffle_draws_v18 (
  id bigint generated by default as identity primary key,
  event_id bigint not null references public.events(id) on delete cascade,
  winner_ticket_id bigint not null references public.tickets(id) on delete restrict,
  prize text not null default '',
  drawn_by text not null,
  drawn_at timestamptz not null default now()
);

create index if not exists idx_raffle_draws_v18_event
  on public.raffle_draws_v18(event_id, drawn_at desc);

alter table public.raffle_draws_v18 enable row level security;
revoke all on public.raffle_draws_v18 from anon, authenticated;

create or replace function public.public_raffle_info_v18(p_event_id bigint)
returns table(
  event_id bigint,
  enabled boolean,
  prize text,
  participant_count bigint
)
language sql
security definer
set search_path=public
as $$
  select e.id,
         coalesce(e.raffle_enabled,false),
         coalesce(e.raffle_prize,''),
         count(t.id) filter(where t.payment_status='Pago')::bigint
  from public.events e
  left join public.tickets t on t.event_id=e.id
  where e.id=p_event_id and e.active=true
  group by e.id;
$$;

grant execute on function public.public_raffle_info_v18(bigint) to anon, authenticated;

create or replace function public.staff_raffle_status_v18(
  p_username text,
  p_password text,
  p_event_id bigint
)
returns table(
  event_id bigint,
  event_name text,
  enabled boolean,
  prize text,
  participant_count bigint,
  last_winner_name text,
  last_winner_code text,
  last_draw_at timestamptz
)
language plpgsql
security definer
set search_path=public,extensions
as $$
declare s public.staff_users%rowtype;
begin
  select u.* into s
  from public.staff_users u
  where u.username=trim(p_username)
    and u.active=true
    and u.password_hash=crypt(p_password,u.password_hash)
  limit 1;
  if not found or s.role<>'admin' then raise exception 'Sem permissao'; end if;

  return query
  select e.id,e.name,coalesce(e.raffle_enabled,false),coalesce(e.raffle_prize,''),
         count(t.id) filter(where t.payment_status='Pago')::bigint,
         lw.customer_name,lw.ticket_code,rd.drawn_at
  from public.events e
  left join public.tickets t on t.event_id=e.id
  left join lateral (
    select d.winner_ticket_id,d.drawn_at
    from public.raffle_draws_v18 d
    where d.event_id=e.id
    order by d.drawn_at desc,d.id desc
    limit 1
  ) rd on true
  left join public.tickets lw on lw.id=rd.winner_ticket_id
  where e.id=p_event_id
  group by e.id,lw.customer_name,lw.ticket_code,rd.drawn_at;
end;
$$;

grant execute on function public.staff_raffle_status_v18(text,text,bigint) to anon, authenticated;

create or replace function public.staff_save_raffle_v18(
  p_username text,
  p_password text,
  p_event_id bigint,
  p_enabled boolean,
  p_prize text
)
returns boolean
language plpgsql
security definer
set search_path=public,extensions
as $$
declare s public.staff_users%rowtype;
begin
  select u.* into s
  from public.staff_users u
  where u.username=trim(p_username)
    and u.active=true
    and u.password_hash=crypt(p_password,u.password_hash)
  limit 1;
  if not found or s.role<>'admin' then raise exception 'Sem permissao'; end if;

  if coalesce(p_enabled,false) and coalesce(trim(p_prize),'')='' then
    raise exception 'Informe o premio do sorteio';
  end if;

  update public.events e
  set raffle_enabled=coalesce(p_enabled,false), raffle_prize=coalesce(trim(p_prize),'')
  where e.id=p_event_id;
  if not found then raise exception 'Evento nao encontrado'; end if;
  return true;
end;
$$;

grant execute on function public.staff_save_raffle_v18(text,text,bigint,boolean,text) to anon, authenticated;

create or replace function public.staff_raffle_participants_v18(
  p_username text,
  p_password text,
  p_event_id bigint
)
returns table(
  ticket_id bigint,
  customer_name text,
  ticket_code text,
  phone text,
  cpf text,
  promoter_code text,
  purchased_at timestamptz,
  paid_at timestamptz
)
language plpgsql
security definer
set search_path=public,extensions
as $$
declare s public.staff_users%rowtype;
begin
  select u.* into s
  from public.staff_users u
  where u.username=trim(p_username)
    and u.active=true
    and u.password_hash=crypt(p_password,u.password_hash)
  limit 1;
  if not found or s.role<>'admin' then raise exception 'Sem permissao'; end if;

  return query
  select t.id,t.customer_name,t.ticket_code,t.phone,t.cpf,t.promoter_code,t.purchased_at,t.paid_at
  from public.tickets t
  where t.event_id=p_event_id and t.payment_status='Pago'
  order by coalesce(t.paid_at,t.purchased_at) desc,t.id desc;
end;
$$;

grant execute on function public.staff_raffle_participants_v18(text,text,bigint) to anon, authenticated;

create or replace function public.staff_draw_raffle_v18(
  p_username text,
  p_password text,
  p_event_id bigint
)
returns table(
  draw_id bigint,
  winner_ticket_id bigint,
  customer_name text,
  ticket_code text,
  phone text,
  cpf text,
  promoter_code text,
  prize text,
  drawn_at timestamptz
)
language plpgsql
security definer
set search_path=public,extensions
as $$
declare
  s public.staff_users%rowtype;
  e public.events%rowtype;
  w public.tickets%rowtype;
  d public.raffle_draws_v18%rowtype;
begin
  select u.* into s
  from public.staff_users u
  where u.username=trim(p_username)
    and u.active=true
    and u.password_hash=crypt(p_password,u.password_hash)
  limit 1;
  if not found or s.role<>'admin' then raise exception 'Sem permissao'; end if;

  select ev.* into e from public.events ev where ev.id=p_event_id for update;
  if not found then raise exception 'Evento nao encontrado'; end if;
  if not coalesce(e.raffle_enabled,false) then raise exception 'Ative o sorteio antes de sortear'; end if;
  if coalesce(trim(e.raffle_prize),'')='' then raise exception 'Informe o premio do sorteio'; end if;

  select t.* into w
  from public.tickets t
  where t.event_id=p_event_id
    and t.payment_status='Pago'
    and not exists(
      select 1 from public.raffle_draws_v18 old
      where old.event_id=p_event_id and old.winner_ticket_id=t.id
    )
  order by random()
  limit 1;

  if not found then
    raise exception 'Nenhum participante pago disponivel para um novo sorteio';
  end if;

  insert into public.raffle_draws_v18(event_id,winner_ticket_id,prize,drawn_by)
  values(p_event_id,w.id,e.raffle_prize,s.username)
  returning * into d;

  return query select d.id,w.id,w.customer_name,w.ticket_code,w.phone,w.cpf,w.promoter_code,d.prize,d.drawn_at;
end;
$$;

grant execute on function public.staff_draw_raffle_v18(text,text,bigint) to anon, authenticated;

-- -------------------------------------------------------------
-- PORTARIA: DISPOSITIVOS AUTORIZADOS
-- -------------------------------------------------------------
create table if not exists public.portaria_devices_v18 (
  id uuid primary key default gen_random_uuid(),
  device_key_hash text not null unique,
  request_code text not null unique,
  label text not null default 'Computador da Portaria',
  active boolean not null default false,
  approved_at timestamptz,
  approved_by text,
  revoked_at timestamptz,
  last_seen timestamptz,
  created_at timestamptz not null default now()
);

create index if not exists idx_portaria_devices_v18_active
  on public.portaria_devices_v18(active, created_at desc);

alter table public.portaria_devices_v18 enable row level security;
revoke all on public.portaria_devices_v18 from anon, authenticated;

create table if not exists public.portaria_pairings_v18 (
  id uuid primary key default gen_random_uuid(),
  device_id uuid not null references public.portaria_devices_v18(id) on delete cascade,
  pair_token_hash text not null unique,
  reader_secret_hash text unique,
  expires_at timestamptz not null,
  reader_expires_at timestamptz,
  claimed_at timestamptz,
  last_scan_at timestamptz,
  active boolean not null default true,
  created_at timestamptz not null default now()
);

create index if not exists idx_portaria_pairings_v18_device
  on public.portaria_pairings_v18(device_id,active,created_at desc);

alter table public.portaria_pairings_v18 enable row level security;
revoke all on public.portaria_pairings_v18 from anon, authenticated;

create table if not exists public.portaria_scan_queue_v18 (
  id bigint generated by default as identity primary key,
  device_id uuid not null references public.portaria_devices_v18(id) on delete cascade,
  pairing_id uuid references public.portaria_pairings_v18(id) on delete set null,
  raw_code text not null,
  created_at timestamptz not null default now(),
  consumed_at timestamptz
);

create index if not exists idx_portaria_scan_queue_v18_pull
  on public.portaria_scan_queue_v18(device_id,consumed_at,created_at);

alter table public.portaria_scan_queue_v18 enable row level security;
revoke all on public.portaria_scan_queue_v18 from anon, authenticated;

create table if not exists public.portaria_logs_v18 (
  id bigint generated by default as identity primary key,
  device_id uuid references public.portaria_devices_v18(id) on delete set null,
  ticket_id bigint references public.tickets(id) on delete set null,
  action text not null,
  metadata jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now()
);

create index if not exists idx_portaria_logs_v18_ticket on public.portaria_logs_v18(ticket_id,created_at desc);
alter table public.portaria_logs_v18 enable row level security;
revoke all on public.portaria_logs_v18 from anon, authenticated;

-- Helper interno: valida a chave secreta gravada somente no computador autorizado.
create or replace function public.portaria_device_id_v18(p_device_key text)
returns uuid
language plpgsql
security definer
set search_path=public,extensions
as $$
declare v_id uuid;
begin
  if coalesce(length(trim(p_device_key)),0)<20 then return null; end if;
  select d.id into v_id
  from public.portaria_devices_v18 d
  where d.device_key_hash=encode(digest(trim(p_device_key),'sha256'),'hex')
    and d.active=true
    and d.revoked_at is null
  limit 1;
  return v_id;
end;
$$;
revoke all on function public.portaria_device_id_v18(text) from public, anon, authenticated;

create or replace function public.portaria_device_request_v18(
  p_device_key text,
  p_label text default null
)
returns table(
  device_id uuid,
  request_code text,
  active boolean,
  label text,
  approved_at timestamptz,
  created_at timestamptz
)
language plpgsql
security definer
set search_path=public,extensions
as $$
declare
  v_hash text;
  d public.portaria_devices_v18%rowtype;
  v_code text;
begin
  if coalesce(length(trim(p_device_key)),0)<20 then raise exception 'Chave do dispositivo invalida'; end if;
  v_hash:=encode(digest(trim(p_device_key),'sha256'),'hex');

  select x.* into d from public.portaria_devices_v18 x where x.device_key_hash=v_hash limit 1;
  if found then
    if coalesce(trim(p_label),'')<>'' then
      update public.portaria_devices_v18 x set label=trim(p_label) where x.id=d.id returning * into d;
    end if;
    return query select d.id,d.request_code,d.active,d.label,d.approved_at,d.created_at;
    return;
  end if;

  loop
    v_code:=upper(substr(replace(gen_random_uuid()::text,'-',''),1,8));
    exit when not exists(select 1 from public.portaria_devices_v18 x where x.request_code=v_code);
  end loop;

  insert into public.portaria_devices_v18(device_key_hash,request_code,label)
  values(v_hash,v_code,coalesce(nullif(trim(p_label),''),'Computador da Portaria'))
  returning * into d;

  return query select d.id,d.request_code,d.active,d.label,d.approved_at,d.created_at;
end;
$$;

grant execute on function public.portaria_device_request_v18(text,text) to anon, authenticated;

create or replace function public.portaria_device_status_v18(p_device_key text)
returns table(
  device_id uuid,
  request_code text,
  active boolean,
  label text,
  approved_at timestamptz,
  revoked_at timestamptz,
  last_seen timestamptz
)
language plpgsql
security definer
set search_path=public,extensions
as $$
declare v_hash text; d public.portaria_devices_v18%rowtype;
begin
  v_hash:=encode(digest(trim(coalesce(p_device_key,'')),'sha256'),'hex');
  select x.* into d from public.portaria_devices_v18 x where x.device_key_hash=v_hash limit 1;
  if not found then return; end if;
  if d.active and d.revoked_at is null then
    update public.portaria_devices_v18 x set last_seen=now() where x.id=d.id returning * into d;
  end if;
  return query select d.id,d.request_code,d.active and d.revoked_at is null,d.label,d.approved_at,d.revoked_at,d.last_seen;
end;
$$;

grant execute on function public.portaria_device_status_v18(text) to anon, authenticated;

create or replace function public.staff_list_portaria_devices_v18(p_username text,p_password text)
returns table(
  device_id uuid,
  request_code text,
  label text,
  active boolean,
  approved_at timestamptz,
  approved_by text,
  revoked_at timestamptz,
  last_seen timestamptz,
  created_at timestamptz
)
language plpgsql
security definer
set search_path=public,extensions
as $$
declare s public.staff_users%rowtype;
begin
  select u.* into s from public.staff_users u
  where u.username=trim(p_username) and u.active=true and u.password_hash=crypt(p_password,u.password_hash)
  limit 1;
  if not found or s.role<>'admin' then raise exception 'Sem permissao'; end if;

  return query
  select d.id,d.request_code,d.label,d.active,d.approved_at,d.approved_by,d.revoked_at,d.last_seen,d.created_at
  from public.portaria_devices_v18 d
  order by d.active desc,d.created_at desc;
end;
$$;

grant execute on function public.staff_list_portaria_devices_v18(text,text) to anon, authenticated;

create or replace function public.staff_approve_portaria_device_v18(
  p_username text,
  p_password text,
  p_request_code text,
  p_label text default null
)
returns boolean
language plpgsql
security definer
set search_path=public,extensions
as $$
declare s public.staff_users%rowtype;
begin
  select u.* into s from public.staff_users u
  where u.username=trim(p_username) and u.active=true and u.password_hash=crypt(p_password,u.password_hash)
  limit 1;
  if not found or s.role<>'admin' then raise exception 'Sem permissao'; end if;

  update public.portaria_devices_v18 d
  set active=true,
      approved_at=now(),
      approved_by=s.username,
      revoked_at=null,
      label=case when coalesce(trim(p_label),'')<>'' then trim(p_label) else d.label end
  where upper(d.request_code)=upper(trim(p_request_code));
  if not found then raise exception 'Codigo do computador nao encontrado'; end if;
  return true;
end;
$$;

grant execute on function public.staff_approve_portaria_device_v18(text,text,text,text) to anon, authenticated;

create or replace function public.staff_revoke_portaria_device_v18(
  p_username text,
  p_password text,
  p_device_id uuid
)
returns boolean
language plpgsql
security definer
set search_path=public,extensions
as $$
declare s public.staff_users%rowtype;
begin
  select u.* into s from public.staff_users u
  where u.username=trim(p_username) and u.active=true and u.password_hash=crypt(p_password,u.password_hash)
  limit 1;
  if not found or s.role<>'admin' then raise exception 'Sem permissao'; end if;

  update public.portaria_devices_v18 d set active=false,revoked_at=now() where d.id=p_device_id;
  if not found then raise exception 'Dispositivo nao encontrado'; end if;
  update public.portaria_pairings_v18 p set active=false where p.device_id=p_device_id;
  return true;
end;
$$;

grant execute on function public.staff_revoke_portaria_device_v18(text,text,uuid) to anon, authenticated;

-- -------------------------------------------------------------
-- PORTARIA: PAREAMENTO DO CELULAR LEITOR
-- -------------------------------------------------------------
create or replace function public.portaria_create_pair_v18(
  p_device_key text,
  p_pair_token text
)
returns table(pairing_id uuid,expires_at timestamptz)
language plpgsql
security definer
set search_path=public,extensions
as $$
declare v_device uuid; p public.portaria_pairings_v18%rowtype;
begin
  v_device:=public.portaria_device_id_v18(p_device_key);
  if v_device is null then raise exception 'Computador nao autorizado'; end if;
  if coalesce(length(trim(p_pair_token)),0)<20 then raise exception 'Token de pareamento invalido'; end if;

  update public.portaria_pairings_v18 x
  set active=false
  where x.device_id=v_device and x.active=true and x.claimed_at is null;

  insert into public.portaria_pairings_v18(device_id,pair_token_hash,expires_at)
  values(v_device,encode(digest(trim(p_pair_token),'sha256'),'hex'),now()+interval '3 minutes')
  returning * into p;

  return query select p.id,p.expires_at;
end;
$$;

grant execute on function public.portaria_create_pair_v18(text,text) to anon, authenticated;

create or replace function public.portaria_claim_pair_v18(
  p_pair_token text,
  p_reader_secret text
)
returns table(ok boolean,message text,reader_expires_at timestamptz)
language plpgsql
security definer
set search_path=public,extensions
as $$
declare p public.portaria_pairings_v18%rowtype; d public.portaria_devices_v18%rowtype;
begin
  if coalesce(length(trim(p_reader_secret)),0)<20 then
    return query select false,'Leitor invalido'::text,null::timestamptz; return;
  end if;

  select x.* into p
  from public.portaria_pairings_v18 x
  where x.pair_token_hash=encode(digest(trim(coalesce(p_pair_token,'')),'sha256'),'hex')
    and x.active=true
    and x.claimed_at is null
    and x.expires_at>now()
  for update
  limit 1;

  if not found then
    return query select false,'QR de conexao expirado ou ja utilizado'::text,null::timestamptz; return;
  end if;

  select x.* into d from public.portaria_devices_v18 x where x.id=p.device_id;
  if not found or not d.active or d.revoked_at is not null then
    return query select false,'Computador nao autorizado'::text,null::timestamptz; return;
  end if;

  update public.portaria_pairings_v18 x
  set reader_secret_hash=encode(digest(trim(p_reader_secret),'sha256'),'hex'),
      claimed_at=now(),
      reader_expires_at=now()+interval '12 hours'
  where x.id=p.id
  returning * into p;

  return query select true,'Leitor conectado'::text,p.reader_expires_at;
end;
$$;

grant execute on function public.portaria_claim_pair_v18(text,text) to anon, authenticated;

create or replace function public.portaria_reader_submit_v18(
  p_reader_secret text,
  p_raw_code text
)
returns boolean
language plpgsql
security definer
set search_path=public,extensions
as $$
declare p public.portaria_pairings_v18%rowtype; d public.portaria_devices_v18%rowtype; v_code text;
begin
  v_code:=left(trim(coalesce(p_raw_code,'')),500);
  if v_code='' then raise exception 'QR vazio'; end if;

  select x.* into p
  from public.portaria_pairings_v18 x
  where x.reader_secret_hash=encode(digest(trim(coalesce(p_reader_secret,'')),'sha256'),'hex')
    and x.active=true
    and x.claimed_at is not null
    and x.reader_expires_at>now()
  limit 1;
  if not found then raise exception 'Sessao do leitor expirada. Conecte novamente pelo computador.'; end if;

  select x.* into d from public.portaria_devices_v18 x where x.id=p.device_id;
  if not found or not d.active or d.revoked_at is not null then raise exception 'Computador nao autorizado'; end if;

  insert into public.portaria_scan_queue_v18(device_id,pairing_id,raw_code)
  values(p.device_id,p.id,v_code);
  update public.portaria_pairings_v18 x set last_scan_at=now() where x.id=p.id;
  return true;
end;
$$;

grant execute on function public.portaria_reader_submit_v18(text,text) to anon, authenticated;

create or replace function public.portaria_device_pull_scan_v18(p_device_key text)
returns table(scan_id bigint,raw_code text,created_at timestamptz)
language plpgsql
security definer
set search_path=public,extensions
as $$
declare v_device uuid; q public.portaria_scan_queue_v18%rowtype;
begin
  v_device:=public.portaria_device_id_v18(p_device_key);
  if v_device is null then raise exception 'Computador nao autorizado'; end if;

  select x.* into q
  from public.portaria_scan_queue_v18 x
  where x.device_id=v_device and x.consumed_at is null
  order by x.created_at,x.id
  for update skip locked
  limit 1;

  if not found then return; end if;
  update public.portaria_scan_queue_v18 x set consumed_at=now() where x.id=q.id;
  return query select q.id,q.raw_code,q.created_at;
end;
$$;

grant execute on function public.portaria_device_pull_scan_v18(text) to anon, authenticated;

create or replace function public.portaria_device_end_readers_v18(p_device_key text)
returns boolean
language plpgsql
security definer
set search_path=public,extensions
as $$
declare v_device uuid;
begin
  v_device:=public.portaria_device_id_v18(p_device_key);
  if v_device is null then raise exception 'Computador nao autorizado'; end if;
  update public.portaria_pairings_v18 x set active=false where x.device_id=v_device and x.active=true;
  return true;
end;
$$;

grant execute on function public.portaria_device_end_readers_v18(text) to anon, authenticated;

-- -------------------------------------------------------------
-- PORTARIA: CONSULTA E OPERACAO SEM SENHA DE STAFF
-- -------------------------------------------------------------
create or replace function public.portaria_device_lookup_v18(
  p_device_key text,
  p_code text
)
returns table(
  ticket_id bigint,event_id bigint,event_name text,event_date date,
  ticket_code text,qr_token text,customer_name text,phone text,cpf text,gender text,
  lot_name text,sector text,payment_status text,entry_status text,entry_at timestamptz,
  document_checked boolean,temporary_exit boolean,reentry_authorized boolean,reentry_count integer
)
language plpgsql
security definer
set search_path=public,extensions
as $$
declare v_device uuid; v_code text;
begin
  v_device:=public.portaria_device_id_v18(p_device_key);
  if v_device is null then raise exception 'Computador nao autorizado'; end if;
  v_code:=trim(coalesce(p_code,''));
  if left(v_code,1)='#' then v_code:=substr(v_code,2); end if;

  return query
  select t.id,t.event_id,e.name,e.event_date,t.ticket_code,t.qr_token,t.customer_name,t.phone,t.cpf,t.gender,
         l.name,l.sector,t.payment_status,t.entry_status,t.entry_at,
         coalesce(t.document_checked,false),coalesce(t.temporary_exit,false),coalesce(t.reentry_authorized,false),coalesce(t.reentry_count,0)
  from public.tickets t
  join public.ticket_lots l on l.id=t.lot_id
  join public.events e on e.id=t.event_id
  where upper(t.ticket_code)=upper(v_code) or t.qr_token=v_code
  order by t.id desc
  limit 1;
end;
$$;

grant execute on function public.portaria_device_lookup_v18(text,text) to anon, authenticated;

create or replace function public.portaria_device_search_v18(
  p_device_key text,
  p_event_id bigint,
  p_query text
)
returns table(
  ticket_id bigint,event_id bigint,event_name text,event_date date,
  ticket_code text,qr_token text,customer_name text,phone text,cpf text,gender text,
  lot_name text,sector text,payment_status text,entry_status text,entry_at timestamptz,
  document_checked boolean,temporary_exit boolean,reentry_authorized boolean,reentry_count integer
)
language plpgsql
security definer
set search_path=public,extensions
as $$
declare v_device uuid; q text;
begin
  v_device:=public.portaria_device_id_v18(p_device_key);
  if v_device is null then raise exception 'Computador nao autorizado'; end if;
  q:=trim(coalesce(p_query,''));
  if q='' then return; end if;

  return query
  select t.id,t.event_id,e.name,e.event_date,t.ticket_code,t.qr_token,t.customer_name,t.phone,t.cpf,t.gender,
         l.name,l.sector,t.payment_status,t.entry_status,t.entry_at,
         coalesce(t.document_checked,false),coalesce(t.temporary_exit,false),coalesce(t.reentry_authorized,false),coalesce(t.reentry_count,0)
  from public.tickets t
  join public.ticket_lots l on l.id=t.lot_id
  join public.events e on e.id=t.event_id
  where (p_event_id is null or t.event_id=p_event_id)
    and (
      lower(t.customer_name) like '%'||lower(q)||'%'
      or lower(coalesce(t.phone,'')) like '%'||lower(q)||'%'
      or lower(coalesce(t.cpf,'')) like '%'||lower(q)||'%'
      or lower(t.ticket_code) like '%'||lower(replace(q,'#',''))||'%'
    )
  order by t.purchased_at desc,t.id desc
  limit 25;
end;
$$;

grant execute on function public.portaria_device_search_v18(text,bigint,text) to anon, authenticated;

create or replace function public.portaria_device_document_v18(
  p_device_key text,
  p_ticket_id bigint,
  p_checked boolean
)
returns boolean
language plpgsql
security definer
set search_path=public,extensions
as $$
declare v_device uuid; d public.portaria_devices_v18%rowtype;
begin
  v_device:=public.portaria_device_id_v18(p_device_key);
  if v_device is null then raise exception 'Computador nao autorizado'; end if;
  select x.* into d from public.portaria_devices_v18 x where x.id=v_device;

  update public.tickets t
  set document_checked=coalesce(p_checked,false),
      document_checked_at=case when coalesce(p_checked,false) then now() else null end,
      document_checked_by=case when coalesce(p_checked,false) then d.label else null end
  where t.id=p_ticket_id;
  if not found then raise exception 'Ingresso nao encontrado'; end if;
  insert into public.portaria_logs_v18(device_id,ticket_id,action,metadata)
  values(v_device,p_ticket_id,'DOCUMENT',jsonb_build_object('checked',coalesce(p_checked,false)));
  return true;
end;
$$;

grant execute on function public.portaria_device_document_v18(text,bigint,boolean) to anon, authenticated;

create or replace function public.portaria_device_validate_v18(
  p_device_key text,
  p_event_id bigint,
  p_code text
)
returns table(
  ok boolean,message text,ticket_id bigint,event_id bigint,ticket_code text,customer_name text,cpf text,
  lot_name text,sector text,payment_status text,entry_status text,entry_at timestamptz,
  document_checked boolean,temporary_exit boolean,reentry_authorized boolean,reentry_count integer
)
language plpgsql
security definer
set search_path=public,extensions
as $$
declare
  v_device uuid;
  d public.portaria_devices_v18%rowtype;
  t public.tickets%rowtype;
  l public.ticket_lots%rowtype;
  v_code text;
begin
  v_device:=public.portaria_device_id_v18(p_device_key);
  if v_device is null then raise exception 'Computador nao autorizado'; end if;
  select x.* into d from public.portaria_devices_v18 x where x.id=v_device;

  v_code:=trim(coalesce(p_code,'')); if left(v_code,1)='#' then v_code:=substr(v_code,2); end if;
  select x.* into t from public.tickets x where upper(x.ticket_code)=upper(v_code) or x.qr_token=v_code limit 1 for update;
  if not found then return query select false,'INGRESSO NAO ENCONTRADO',null::bigint,null::bigint,null::text,null::text,null::text,null::text,null::text,null::text,null::text,null::timestamptz,false,false,false,0; return; end if;
  select x.* into l from public.ticket_lots x where x.id=t.lot_id;

  if p_event_id is not null and t.event_id<>p_event_id then
    return query select false,'INGRESSO DE OUTRO EVENTO',t.id,t.event_id,t.ticket_code,t.customer_name,t.cpf,l.name,l.sector,t.payment_status,t.entry_status,t.entry_at,t.document_checked,t.temporary_exit,t.reentry_authorized,t.reentry_count; return;
  end if;
  if t.payment_status<>'Pago' then
    return query select false,case when t.payment_status='Cancelado' then 'INGRESSO CANCELADO' else 'PAGAMENTO NAO CONFIRMADO' end,t.id,t.event_id,t.ticket_code,t.customer_name,t.cpf,l.name,l.sector,t.payment_status,t.entry_status,t.entry_at,t.document_checked,t.temporary_exit,t.reentry_authorized,t.reentry_count; return;
  end if;
  if not coalesce(t.document_checked,false) then
    return query select false,'CONFIRA O DOCUMENTO/CPF ANTES DE LIBERAR',t.id,t.event_id,t.ticket_code,t.customer_name,t.cpf,l.name,l.sector,t.payment_status,t.entry_status,t.entry_at,t.document_checked,t.temporary_exit,t.reentry_authorized,t.reentry_count; return;
  end if;
  if t.entry_status='Entrada utilizada' and not coalesce(t.temporary_exit,false) then
    return query select false,'INGRESSO JA UTILIZADO',t.id,t.event_id,t.ticket_code,t.customer_name,t.cpf,l.name,l.sector,t.payment_status,t.entry_status,t.entry_at,t.document_checked,t.temporary_exit,t.reentry_authorized,t.reentry_count; return;
  end if;
  if coalesce(t.temporary_exit,false) and not coalesce(t.reentry_authorized,false) then
    return query select false,'REENTRADA NAO AUTORIZADA',t.id,t.event_id,t.ticket_code,t.customer_name,t.cpf,l.name,l.sector,t.payment_status,t.entry_status,t.entry_at,t.document_checked,t.temporary_exit,t.reentry_authorized,t.reentry_count; return;
  end if;

  if coalesce(t.temporary_exit,false) and coalesce(t.reentry_authorized,false) then
    update public.tickets x
    set temporary_exit=false,reentry_authorized=false,reentry_count=coalesce(x.reentry_count,0)+1,last_entry_device=d.label
    where x.id=t.id returning * into t;
    insert into public.portaria_logs_v18(device_id,ticket_id,action,metadata) values(v_device,t.id,'REENTRY',jsonb_build_object('device',d.label));
    return query select true,'REENTRADA LIBERADA',t.id,t.event_id,t.ticket_code,t.customer_name,t.cpf,l.name,l.sector,t.payment_status,t.entry_status,t.entry_at,t.document_checked,t.temporary_exit,t.reentry_authorized,t.reentry_count; return;
  end if;

  update public.tickets x
  set entry_status='Entrada utilizada',entry_at=coalesce(x.entry_at,now()),last_entry_device=d.label
  where x.id=t.id returning * into t;
  insert into public.portaria_logs_v18(device_id,ticket_id,action,metadata) values(v_device,t.id,'ENTRY',jsonb_build_object('device',d.label));
  return query select true,'ENTRADA LIBERADA',t.id,t.event_id,t.ticket_code,t.customer_name,t.cpf,l.name,l.sector,t.payment_status,t.entry_status,t.entry_at,t.document_checked,t.temporary_exit,t.reentry_authorized,t.reentry_count;
end;
$$;

grant execute on function public.portaria_device_validate_v18(text,bigint,text) to anon, authenticated;

create or replace function public.portaria_device_temporary_exit_v18(
  p_device_key text,
  p_ticket_id bigint
)
returns boolean
language plpgsql
security definer
set search_path=public,extensions
as $$
declare v_device uuid;
begin
  v_device:=public.portaria_device_id_v18(p_device_key);
  if v_device is null then raise exception 'Computador nao autorizado'; end if;
  update public.tickets t
  set temporary_exit=true,temporary_exit_at=now(),reentry_authorized=false,reentry_authorized_at=null,reentry_authorized_by=null
  where t.id=p_ticket_id and t.payment_status='Pago' and t.entry_status='Entrada utilizada';
  if not found then raise exception 'Ingresso nao esta dentro do evento'; end if;
  insert into public.portaria_logs_v18(device_id,ticket_id,action) values(v_device,p_ticket_id,'TEMPORARY_EXIT');
  return true;
end;
$$;

grant execute on function public.portaria_device_temporary_exit_v18(text,bigint) to anon, authenticated;

create or replace function public.portaria_device_reentry_v18(
  p_device_key text,
  p_ticket_id bigint,
  p_authorized boolean
)
returns boolean
language plpgsql
security definer
set search_path=public,extensions
as $$
declare v_device uuid; d public.portaria_devices_v18%rowtype;
begin
  v_device:=public.portaria_device_id_v18(p_device_key);
  if v_device is null then raise exception 'Computador nao autorizado'; end if;
  select x.* into d from public.portaria_devices_v18 x where x.id=v_device;
  update public.tickets t
  set reentry_authorized=coalesce(p_authorized,false),
      reentry_authorized_at=case when coalesce(p_authorized,false) then now() else null end,
      reentry_authorized_by=case when coalesce(p_authorized,false) then d.label else null end
  where t.id=p_ticket_id and t.temporary_exit=true;
  if not found then raise exception 'Saida temporaria nao encontrada'; end if;
  insert into public.portaria_logs_v18(device_id,ticket_id,action,metadata)
  values(v_device,p_ticket_id,'REENTRY_AUTH',jsonb_build_object('authorized',coalesce(p_authorized,false)));
  return true;
end;
$$;

grant execute on function public.portaria_device_reentry_v18(text,bigint,boolean) to anon, authenticated;

create or replace function public.portaria_device_dashboard_v18(
  p_device_key text,
  p_event_id bigint
)
returns jsonb
language plpgsql
security definer
set search_path=public,extensions
as $$
declare v_device uuid; result jsonb;
begin
  v_device:=public.portaria_device_id_v18(p_device_key);
  if v_device is null then raise exception 'Computador nao autorizado'; end if;

  select jsonb_build_object(
    'event_id',e.id,
    'event_name',e.name,
    'event_date',e.event_date,
    'total_paid',count(t.id) filter(where t.payment_status='Pago'),
    'entered_count',count(t.id) filter(where t.payment_status='Pago' and t.entry_status='Entrada utilizada' and not coalesce(t.temporary_exit,false)),
    'remaining_count',count(t.id) filter(where t.payment_status='Pago' and (t.entry_status<>'Entrada utilizada' or coalesce(t.temporary_exit,false))),
    'female_entered',count(t.id) filter(where t.payment_status='Pago' and t.entry_status='Entrada utilizada' and not coalesce(t.temporary_exit,false) and lower(coalesce(t.gender,''))='feminino'),
    'male_entered',count(t.id) filter(where t.payment_status='Pago' and t.entry_status='Entrada utilizada' and not coalesce(t.temporary_exit,false) and lower(coalesce(t.gender,''))='masculino'),
    'sector_stats',coalesce((
      select jsonb_agg(jsonb_build_object('sector',s.sector,'paid',s.paid,'entered',s.entered) order by s.sector)
      from (
        select coalesce(l2.sector,'Ingresso') sector,
               count(t2.id) filter(where t2.payment_status='Pago') paid,
               count(t2.id) filter(where t2.payment_status='Pago' and t2.entry_status='Entrada utilizada' and not coalesce(t2.temporary_exit,false)) entered
        from public.tickets t2 join public.ticket_lots l2 on l2.id=t2.lot_id
        where t2.event_id=e.id group by coalesce(l2.sector,'Ingresso')
      ) s
    ),'[]'::jsonb),
    'recent',coalesce((
      select jsonb_agg(x.obj order by x.entry_at desc)
      from (
        select jsonb_build_object('name',t3.customer_name,'code',t3.ticket_code,'sector',l3.sector,'entry_at',t3.entry_at) obj,t3.entry_at
        from public.tickets t3 join public.ticket_lots l3 on l3.id=t3.lot_id
        where t3.event_id=e.id and t3.entry_status='Entrada utilizada' and t3.entry_at is not null
        order by t3.entry_at desc limit 12
      ) x
    ),'[]'::jsonb)
  ) into result
  from public.events e
  left join public.tickets t on t.event_id=e.id
  where e.id=p_event_id
  group by e.id;

  return coalesce(result,'{}'::jsonb);
end;
$$;

grant execute on function public.portaria_device_dashboard_v18(text,bigint) to anon, authenticated;

create or replace function public.portaria_device_snapshot_v18(
  p_device_key text,
  p_event_id bigint
)
returns table(
  ticket_id bigint,event_id bigint,ticket_code text,qr_token text,customer_name text,phone text,cpf text,gender text,
  lot_name text,sector text,payment_status text,entry_status text,entry_at timestamptz,
  document_checked boolean,temporary_exit boolean,reentry_authorized boolean,reentry_count integer
)
language plpgsql
security definer
set search_path=public,extensions
as $$
declare v_device uuid;
begin
  v_device:=public.portaria_device_id_v18(p_device_key);
  if v_device is null then raise exception 'Computador nao autorizado'; end if;
  return query
  select t.id,t.event_id,t.ticket_code,t.qr_token,t.customer_name,t.phone,t.cpf,t.gender,l.name,l.sector,
         t.payment_status,t.entry_status,t.entry_at,coalesce(t.document_checked,false),coalesce(t.temporary_exit,false),coalesce(t.reentry_authorized,false),coalesce(t.reentry_count,0)
  from public.tickets t join public.ticket_lots l on l.id=t.lot_id
  where t.event_id=p_event_id and t.payment_status='Pago'
  order by t.id;
end;
$$;

grant execute on function public.portaria_device_snapshot_v18(text,bigint) to anon, authenticated;

-- Limpeza de filas antigas para nao acumular indefinidamente.
delete from public.portaria_scan_queue_v18 where created_at < now()-interval '2 days';
update public.portaria_pairings_v18 set active=false where active=true and coalesce(reader_expires_at,expires_at)<now();

-- FIM V18
-- =============================================================
-- HYPE LOUNGE CLUB // V19 ATUALIZACAO
-- 1) Varios celulares leitores simultaneos na Portaria
-- 2) QR de pareamento renovavel/continuo + lista em tempo real
-- 3) Venda na hora pela Portaria com PIX da chave cadastrada
-- 4) Pagamento de venda na hora confirmado pela Portaria autorizada
-- 5) Toda venda PAGA (site, promoter ou portaria) entra no sorteio do evento
-- 6) Sorteio continua sendo executado SOMENTE pelo Admin
--
-- Execute depois da V18. O arquivo SUPABASE_V19_COMPLETO.sql ja inclui V18+V19.
-- Este patch e aditivo e nao apaga ingressos/eventos/promoters.
-- =============================================================

create extension if not exists pgcrypto;

alter table public.portaria_pairings_v18
  add column if not exists reader_label text;

alter table public.tickets
  add column if not exists sale_origin text not null default 'site',
  add column if not exists door_device_id uuid;

do $$
begin
  if not exists (
    select 1 from pg_constraint where conname='tickets_door_device_v19_fkey'
  ) then
    alter table public.tickets
      add constraint tickets_door_device_v19_fkey
      foreign key (door_device_id) references public.portaria_devices_v18(id) on delete set null;
  end if;
end $$;

create index if not exists idx_tickets_sale_origin_v19
  on public.tickets(event_id,sale_origin,payment_status,purchased_at desc);

-- -------------------------------------------------------------
-- LEITORES: varios celulares + monitor em tempo real
-- -------------------------------------------------------------
create or replace function public.portaria_create_pair_v19(
  p_device_key text,
  p_pair_token text
)
returns table(pairing_id uuid, expires_at timestamptz, pairing_code text)
language plpgsql
security definer
set search_path=public,extensions
as $$
declare
  v_device uuid;
  p public.portaria_pairings_v18%rowtype;
begin
  v_device:=public.portaria_device_id_v18(p_device_key);
  if v_device is null then raise exception 'Computador nao autorizado'; end if;
  if coalesce(length(trim(p_pair_token)),0)<20 then raise exception 'Token de pareamento invalido'; end if;

  -- Invalida somente QRs ainda nao usados e expirados/antigos.
  -- Celulares ja conectados continuam funcionando juntos.
  update public.portaria_pairings_v18 x
  set active=false
  where x.device_id=v_device
    and x.claimed_at is null
    and x.active=true;

  insert into public.portaria_pairings_v18(device_id,pair_token_hash,expires_at,active)
  values(v_device,encode(digest(trim(p_pair_token),'sha256'),'hex'),now()+interval '2 minutes',true)
  returning * into p;

  return query select
    p.id,
    p.expires_at,
    upper(substr(replace(p.id::text,'-',''),1,6));
end;
$$;

grant execute on function public.portaria_create_pair_v19(text,text) to anon, authenticated;

create or replace function public.portaria_claim_pair_v19(
  p_pair_token text,
  p_reader_secret text,
  p_reader_label text default null
)
returns table(ok boolean,message text,reader_id uuid,reader_label text,reader_expires_at timestamptz)
language plpgsql
security definer
set search_path=public,extensions
as $$
declare
  p public.portaria_pairings_v18%rowtype;
  d public.portaria_devices_v18%rowtype;
  v_label text;
begin
  if coalesce(length(trim(p_reader_secret)),0)<20 then
    return query select false,'Leitor invalido'::text,null::uuid,null::text,null::timestamptz;
    return;
  end if;

  select x.* into p
  from public.portaria_pairings_v18 x
  where x.pair_token_hash=encode(digest(trim(coalesce(p_pair_token,'')),'sha256'),'hex')
    and x.active=true
    and x.claimed_at is null
    and x.expires_at>now()
  for update
  limit 1;

  if not found then
    return query select false,'QR de conexao expirado ou ja utilizado'::text,null::uuid,null::text,null::timestamptz;
    return;
  end if;

  select x.* into d from public.portaria_devices_v18 x where x.id=p.device_id;
  if not found or not d.active or d.revoked_at is not null then
    return query select false,'Computador nao autorizado'::text,null::uuid,null::text,null::timestamptz;
    return;
  end if;

  v_label:=left(coalesce(nullif(trim(p_reader_label),''),'Celular '||upper(substr(replace(p.id::text,'-',''),1,4))),50);

  update public.portaria_pairings_v18 x
  set reader_secret_hash=encode(digest(trim(p_reader_secret),'sha256'),'hex'),
      reader_label=v_label,
      claimed_at=now(),
      reader_expires_at=now()+interval '12 hours',
      last_scan_at=null,
      active=true
  where x.id=p.id
  returning * into p;

  return query select true,'Leitor conectado'::text,p.id,p.reader_label,p.reader_expires_at;
end;
$$;

grant execute on function public.portaria_claim_pair_v19(text,text,text) to anon, authenticated;

create or replace function public.portaria_reader_submit_v19(
  p_reader_secret text,
  p_raw_code text
)
returns boolean
language plpgsql
security definer
set search_path=public,extensions
as $$
declare
  p public.portaria_pairings_v18%rowtype;
  d public.portaria_devices_v18%rowtype;
  v_code text;
begin
  v_code:=left(trim(coalesce(p_raw_code,'')),500);
  if v_code='' then raise exception 'QR vazio'; end if;

  select x.* into p
  from public.portaria_pairings_v18 x
  where x.reader_secret_hash=encode(digest(trim(coalesce(p_reader_secret,'')),'sha256'),'hex')
    and x.active=true
    and x.claimed_at is not null
    and x.reader_expires_at>now()
  limit 1;
  if not found then raise exception 'Sessao do leitor expirada. Conecte novamente pelo computador.'; end if;

  select x.* into d from public.portaria_devices_v18 x where x.id=p.device_id;
  if not found or not d.active or d.revoked_at is not null then raise exception 'Computador nao autorizado'; end if;

  insert into public.portaria_scan_queue_v18(device_id,pairing_id,raw_code)
  values(p.device_id,p.id,v_code);
  update public.portaria_pairings_v18 x set last_scan_at=now() where x.id=p.id;
  return true;
end;
$$;

grant execute on function public.portaria_reader_submit_v19(text,text) to anon, authenticated;

create or replace function public.portaria_device_list_readers_v19(p_device_key text)
returns table(
  reader_id uuid,
  reader_label text,
  connected_at timestamptz,
  last_scan_at timestamptz,
  expires_at timestamptz,
  active boolean
)
language plpgsql
security definer
set search_path=public,extensions
as $$
declare v_device uuid;
begin
  v_device:=public.portaria_device_id_v18(p_device_key);
  if v_device is null then raise exception 'Computador nao autorizado'; end if;

  return query
  select
    p.id,
    coalesce(p.reader_label,'Celular '||upper(substr(replace(p.id::text,'-',''),1,4))),
    p.claimed_at,
    p.last_scan_at,
    p.reader_expires_at,
    (p.active=true and p.claimed_at is not null and p.reader_expires_at>now())
  from public.portaria_pairings_v18 p
  where p.device_id=v_device
    and p.claimed_at is not null
    and p.created_at>now()-interval '24 hours'
  order by (p.active=true and p.reader_expires_at>now()) desc,p.claimed_at desc;
end;
$$;

grant execute on function public.portaria_device_list_readers_v19(text) to anon, authenticated;

create or replace function public.portaria_device_disconnect_reader_v19(
  p_device_key text,
  p_reader_id uuid
)
returns boolean
language plpgsql
security definer
set search_path=public,extensions
as $$
declare v_device uuid;
begin
  v_device:=public.portaria_device_id_v18(p_device_key);
  if v_device is null then raise exception 'Computador nao autorizado'; end if;
  update public.portaria_pairings_v18 p
  set active=false
  where p.id=p_reader_id and p.device_id=v_device;
  if not found then raise exception 'Leitor nao encontrado'; end if;
  return true;
end;
$$;

grant execute on function public.portaria_device_disconnect_reader_v19(text,uuid) to anon, authenticated;

-- -------------------------------------------------------------
-- VENDA NA HORA: contexto de evento/lotes + PIX cadastrado
-- -------------------------------------------------------------
create or replace function public.portaria_device_sales_context_v19(
  p_device_key text,
  p_event_id bigint
)
returns table(
  event_id bigint,
  event_name text,
  event_date date,
  pix_key text,
  raffle_enabled boolean,
  raffle_prize text,
  lot_id bigint,
  lot_name text,
  sector text,
  price_female numeric,
  price_male numeric,
  quantity_available bigint,
  starts_at timestamptz,
  ends_at timestamptz,
  active boolean
)
language plpgsql
security definer
set search_path=public,extensions
as $$
declare v_device uuid;
begin
  v_device:=public.portaria_device_id_v18(p_device_key);
  if v_device is null then raise exception 'Computador nao autorizado'; end if;

  return query
  select
    e.id,
    e.name,
    e.event_date,
    coalesce(e.pix_key,''),
    coalesce(e.raffle_enabled,false),
    coalesce(e.raffle_prize,''),
    l.id,
    l.name,
    l.sector,
    coalesce(l.price_female,l.price),
    coalesce(l.price_male,l.price),
    case when l.quantity_total=0 then null::bigint
         else greatest(l.quantity_total-count(t.id) filter(where t.payment_status in('Pendente','Pago')),0)::bigint
    end,
    l.starts_at,
    l.ends_at,
    l.active
  from public.events e
  join public.ticket_lots l on l.event_id=e.id
  left join public.tickets t on t.lot_id=l.id
  where e.id=p_event_id
    and e.active=true
  group by e.id,l.id
  order by l.sort_order,l.id;
end;
$$;

grant execute on function public.portaria_device_sales_context_v19(text,bigint) to anon, authenticated;

create or replace function public.portaria_device_create_door_order_v19(
  p_device_key text,
  p_event_id bigint,
  p_lot_id bigint,
  p_name text,
  p_phone text default null,
  p_cpf text default null,
  p_email text default null,
  p_gender text default 'Feminino'
)
returns table(
  ticket_id bigint,
  event_id bigint,
  event_name text,
  ticket_code text,
  qr_token text,
  customer_name text,
  phone text,
  cpf text,
  email text,
  gender text,
  lot_id bigint,
  lot_name text,
  sector text,
  price numeric,
  payment_status text,
  pix_key text,
  raffle_enabled boolean,
  raffle_prize text,
  purchased_at timestamptz
)
language plpgsql
security definer
set search_path=public,extensions
as $$
declare
  v_device uuid;
  l public.ticket_lots%rowtype;
  e public.events%rowtype;
  v_used integer;
  v_original numeric(12,2);
  v_fee numeric(12,2):=1.98;
  v_total numeric(12,2);
  v_id bigint;
  v_code text;
  v_qr text;
  v_purchased timestamptz;
begin
  v_device:=public.portaria_device_id_v18(p_device_key);
  if v_device is null then raise exception 'Computador nao autorizado'; end if;
  if coalesce(trim(p_name),'')='' then raise exception 'Informe o nome da pessoa'; end if;
  if p_gender not in('Feminino','Masculino') then raise exception 'Selecione Feminino ou Masculino'; end if;

  select x.* into l
  from public.ticket_lots x
  where x.id=p_lot_id and x.event_id=p_event_id
  for update;
  if not found or not l.active then raise exception 'Ingresso indisponivel'; end if;

  select x.* into e from public.events x where x.id=p_event_id and x.active=true;
  if not found then raise exception 'Evento indisponivel'; end if;
  if coalesce(trim(e.pix_key),'')='' then raise exception 'Cadastre a chave PIX deste evento no Admin antes de vender na Portaria'; end if;
  if l.starts_at is not null and now()<l.starts_at then raise exception 'Este lote ainda nao abriu'; end if;
  if l.ends_at is not null and now()>=l.ends_at then raise exception 'Este lote ja encerrou'; end if;

  select count(*)::integer into v_used
  from public.tickets t
  where t.lot_id=l.id and t.payment_status in('Pendente','Pago');
  if l.quantity_total>0 and v_used>=l.quantity_total then raise exception 'Ingresso esgotado'; end if;

  v_original:=case when p_gender='Masculino' then coalesce(l.price_male,l.price,0) else coalesce(l.price_female,l.price,0) end;
  if v_original<0 then raise exception 'Preco invalido'; end if;
  v_total:=round(v_original+v_fee,2);

  loop
    v_code:='HYPE-'||upper(substr(md5(random()::text||clock_timestamp()::text),1,10));
    exit when not exists(select 1 from public.tickets t where t.ticket_code=v_code);
  end loop;
  v_qr:=gen_random_uuid()::text;

  insert into public.tickets(
    event_id,lot_id,customer_name,phone,email,cpf,gender,
    price,original_price,discount_amount,service_fee,
    ticket_code,qr_token,payment_status,entry_status,
    sale_origin,door_device_id
  ) values(
    e.id,l.id,trim(p_name),nullif(trim(coalesce(p_phone,'')),''),nullif(lower(trim(coalesce(p_email,''))),''),nullif(trim(coalesce(p_cpf,'')),''),p_gender,
    v_total,v_original,0,v_fee,
    v_code,v_qr,'Pendente','Não utilizado',
    'portaria',v_device
  ) returning tickets.id,tickets.purchased_at into v_id,v_purchased;

  insert into public.portaria_logs_v18(device_id,ticket_id,action,metadata)
  values(v_device,v_id,'DOOR_ORDER_CREATED',jsonb_build_object('event_id',e.id,'lot_id',l.id,'price',v_total));

  return query select
    v_id,e.id,e.name,v_code,v_qr,trim(p_name),nullif(trim(coalesce(p_phone,'')),''),nullif(trim(coalesce(p_cpf,'')),''),nullif(lower(trim(coalesce(p_email,''))),''),p_gender,
    l.id,l.name,l.sector,v_total,'Pendente'::text,coalesce(e.pix_key,''),coalesce(e.raffle_enabled,false),coalesce(e.raffle_prize,''),v_purchased;
end;
$$;

grant execute on function public.portaria_device_create_door_order_v19(text,bigint,bigint,text,text,text,text,text) to anon, authenticated;

create or replace function public.portaria_device_confirm_door_payment_v19(
  p_device_key text,
  p_ticket_id bigint
)
returns table(
  ticket_id bigint,
  ticket_code text,
  qr_token text,
  customer_name text,
  payment_status text,
  paid_at timestamptz,
  raffle_enabled boolean,
  raffle_prize text
)
language plpgsql
security definer
set search_path=public,extensions
as $$
declare
  v_device uuid;
  t public.tickets%rowtype;
  e public.events%rowtype;
begin
  v_device:=public.portaria_device_id_v18(p_device_key);
  if v_device is null then raise exception 'Computador nao autorizado'; end if;

  select x.* into t from public.tickets x where x.id=p_ticket_id for update;
  if not found then raise exception 'Venda nao encontrada'; end if;
  if coalesce(t.sale_origin,'site')<>'portaria' then raise exception 'Este pagamento deve ser confirmado pelo Admin'; end if;
  if t.door_device_id is distinct from v_device then raise exception 'Esta venda foi criada em outro computador da Portaria'; end if;
  if t.payment_status='Cancelado' then raise exception 'Ingresso cancelado'; end if;

  if t.payment_status<>'Pago' then
    update public.tickets x
    set payment_status='Pago',paid_at=coalesce(x.paid_at,now())
    where x.id=t.id
    returning * into t;

    insert into public.portaria_logs_v18(device_id,ticket_id,action,metadata)
    values(v_device,t.id,'DOOR_PAYMENT_CONFIRMED',jsonb_build_object('price',t.price));
  end if;

  select x.* into e from public.events x where x.id=t.event_id;

  return query select
    t.id,t.ticket_code,t.qr_token,t.customer_name,t.payment_status,t.paid_at,
    coalesce(e.raffle_enabled,false),coalesce(e.raffle_prize,'');
end;
$$;

grant execute on function public.portaria_device_confirm_door_payment_v19(text,bigint) to anon, authenticated;

create or replace function public.portaria_device_cancel_door_order_v19(
  p_device_key text,
  p_ticket_id bigint
)
returns boolean
language plpgsql
security definer
set search_path=public,extensions
as $$
declare
  v_device uuid;
  t public.tickets%rowtype;
begin
  v_device:=public.portaria_device_id_v18(p_device_key);
  if v_device is null then raise exception 'Computador nao autorizado'; end if;
  select x.* into t from public.tickets x where x.id=p_ticket_id for update;
  if not found then raise exception 'Venda nao encontrada'; end if;
  if coalesce(t.sale_origin,'site')<>'portaria' or t.door_device_id is distinct from v_device then raise exception 'Sem permissao para cancelar esta venda'; end if;
  if t.payment_status='Pago' then raise exception 'Venda ja paga. Cancele pelo Admin se necessario'; end if;
  update public.tickets x set payment_status='Cancelado',canceled_at=now() where x.id=t.id;
  insert into public.portaria_logs_v18(device_id,ticket_id,action) values(v_device,t.id,'DOOR_ORDER_CANCELED');
  return true;
end;
$$;

grant execute on function public.portaria_device_cancel_door_order_v19(text,bigint) to anon, authenticated;

-- A regra do sorteio permanece simples e segura:
-- staff_raffle_participants_v18 e staff_draw_raffle_v18 leem TODOS os tickets
-- do evento com payment_status='Pago'. Portanto site, promoter e portaria entram
-- automaticamente depois da confirmacao do pagamento. O sorteio so pode ser
-- executado pela funcao staff_draw_raffle_v18, que exige perfil Admin.

-- Limpeza leve de tokens antigos. Nao remove leitores ainda validos.
update public.portaria_pairings_v18
set active=false
where active=true
  and claimed_at is null
  and expires_at<now();
-- =============================================================
-- HYPE LOUNGE CLUB // V20 - LINK EXCLUSIVO DO LEITOR
-- Execute depois da V18 ou V19. Nao apaga ingressos/eventos/promoters.
-- =============================================================

create extension if not exists pgcrypto;

alter table public.portaria_pairings_v18
  add column if not exists reader_label text;

-- Gera um link individual de ativacao a partir do computador autorizado.
-- Nao invalida outros links ainda nao usados, permitindo preparar varios celulares.
create or replace function public.portaria_device_create_reader_link_v20(
  p_device_key text,
  p_link_token text,
  p_reader_label text default null
)
returns table(
  reader_id uuid,
  reader_label text,
  link_expires_at timestamptz
)
language plpgsql
security definer
set search_path=public,extensions
as $$
declare
  v_device uuid;
  p public.portaria_pairings_v18%rowtype;
  v_label text;
begin
  v_device:=public.portaria_device_id_v18(p_device_key);
  if v_device is null then raise exception 'Computador nao autorizado'; end if;
  if coalesce(length(trim(p_link_token)),0)<40 then raise exception 'Token do link invalido'; end if;

  v_label:=left(coalesce(nullif(trim(p_reader_label),''),'Celular leitor'),50);

  update public.portaria_pairings_v18 x
  set active=false
  where x.device_id=v_device
    and x.active=true
    and x.claimed_at is null
    and x.expires_at<=now();

  insert into public.portaria_pairings_v18(
    device_id,pair_token_hash,expires_at,active,reader_label
  ) values(
    v_device,
    encode(digest(trim(p_link_token),'sha256'),'hex'),
    now()+interval '15 minutes',
    true,
    v_label
  )
  returning * into p;

  return query select p.id,coalesce(p.reader_label,v_label),p.expires_at;
end;
$$;

grant execute on function public.portaria_device_create_reader_link_v20(text,text,text) to anon, authenticated;

-- O link pode ser ativado apenas uma vez. Depois o token some da URL e
-- o celular guarda apenas uma credencial secreta local por ate 16 horas.
create or replace function public.portaria_claim_reader_link_v20(
  p_link_token text,
  p_reader_secret text,
  p_reader_label text default null
)
returns table(
  ok boolean,
  message text,
  reader_id uuid,
  reader_label text,
  reader_expires_at timestamptz
)
language plpgsql
security definer
set search_path=public,extensions
as $$
declare
  p public.portaria_pairings_v18%rowtype;
  d public.portaria_devices_v18%rowtype;
  v_label text;
begin
  if coalesce(length(trim(p_reader_secret)),0)<40 then
    return query select false,'Leitor invalido'::text,null::uuid,null::text,null::timestamptz;
    return;
  end if;

  select x.* into p
  from public.portaria_pairings_v18 x
  where x.pair_token_hash=encode(digest(trim(coalesce(p_link_token,'')),'sha256'),'hex')
    and x.active=true
    and x.claimed_at is null
    and x.expires_at>now()
  for update
  limit 1;

  if not found then
    return query select false,'Link expirado, ja utilizado ou bloqueado. Gere um novo link na Portaria.'::text,null::uuid,null::text,null::timestamptz;
    return;
  end if;

  select x.* into d from public.portaria_devices_v18 x where x.id=p.device_id;
  if not found or not d.active or d.revoked_at is not null then
    return query select false,'Computador da Portaria nao autorizado'::text,null::uuid,null::text,null::timestamptz;
    return;
  end if;

  v_label:=left(coalesce(nullif(trim(p.reader_label),''),nullif(trim(p_reader_label),''),'Celular leitor'),50);

  update public.portaria_pairings_v18 x
  set reader_secret_hash=encode(digest(trim(p_reader_secret),'sha256'),'hex'),
      reader_label=v_label,
      claimed_at=now(),
      reader_expires_at=now()+interval '16 hours',
      last_scan_at=null,
      active=true
  where x.id=p.id
  returning * into p;

  return query select true,'Leitor autorizado'::text,p.id,p.reader_label,p.reader_expires_at;
end;
$$;

grant execute on function public.portaria_claim_reader_link_v20(text,text,text) to anon, authenticated;

-- Admin enxerga os leitores de todos os computadores autorizados.
create or replace function public.staff_list_portaria_readers_v20(
  p_username text,
  p_password text
)
returns table(
  reader_id uuid,
  device_id uuid,
  device_label text,
  reader_label text,
  connected_at timestamptz,
  last_scan_at timestamptz,
  expires_at timestamptz,
  active boolean
)
language plpgsql
security definer
set search_path=public,extensions
as $$
declare s public.staff_users%rowtype;
begin
  select u.* into s
  from public.staff_users u
  where u.username=trim(p_username)
    and u.active=true
    and u.password_hash=crypt(p_password,u.password_hash)
  limit 1;

  if not found or s.role<>'admin' then raise exception 'Sem permissao'; end if;

  return query
  select
    p.id,
    d.id,
    d.label,
    coalesce(p.reader_label,'Celular leitor'),
    p.claimed_at,
    p.last_scan_at,
    p.reader_expires_at,
    (p.active=true and p.claimed_at is not null and p.reader_expires_at>now() and d.active=true and d.revoked_at is null)
  from public.portaria_pairings_v18 p
  join public.portaria_devices_v18 d on d.id=p.device_id
  where p.claimed_at is not null
    and p.created_at>now()-interval '7 days'
  order by
    (p.active=true and p.reader_expires_at>now()) desc,
    p.claimed_at desc;
end;
$$;

grant execute on function public.staff_list_portaria_readers_v20(text,text) to anon, authenticated;

create or replace function public.staff_revoke_portaria_reader_v20(
  p_username text,
  p_password text,
  p_reader_id uuid
)
returns boolean
language plpgsql
security definer
set search_path=public,extensions
as $$
declare s public.staff_users%rowtype;
begin
  select u.* into s
  from public.staff_users u
  where u.username=trim(p_username)
    and u.active=true
    and u.password_hash=crypt(p_password,u.password_hash)
  limit 1;

  if not found or s.role<>'admin' then raise exception 'Sem permissao'; end if;

  update public.portaria_pairings_v18 p
  set active=false
  where p.id=p_reader_id;

  if not found then raise exception 'Leitor nao encontrado'; end if;
  return true;
end;
$$;

grant execute on function public.staff_revoke_portaria_reader_v20(text,text,uuid) to anon, authenticated;

-- Limpeza leve de links de ativacao vencidos. Nao remove leitores validos.
update public.portaria_pairings_v18
set active=false
where active=true
  and claimed_at is null
  and expires_at<=now();

-- IMPORTANTE SOBRE VENDA NA HORA:
-- As funcoes V19 reaplicadas no patch V20 mantem a regra:
-- 1) a Portaria cria sale_origin='portaria' e grava door_device_id;
-- 2) portaria_device_confirm_door_payment_v19 recusa qualquer venda do site/promoter;
-- 3) o mesmo RPC recusa venda criada em outro computador da Portaria;
-- 4) ao ficar PAGO, o ingresso passa a integrar o sorteio do evento automaticamente;
-- 5) o sorteio continua exigindo perfil Admin.
