-- HYPE V59 — avaliação da Portaria + picos de fluxo
-- Aplicado no Supabase de produção em 2026-10-02.
-- Mantém o RPC staff_live_checkin_v34 usado pelo Admin e acrescenta:
-- peak_inside, peak_entry_15m, peak_exit_15m, good_observations,
-- bad_observations e observations.
-- A Portaria grava avaliações pelo RPC portaria_device_observation_v59.

create table if not exists public.portaria_observations_v59 (
  id bigint generated by default as identity primary key,
  event_id bigint not null references public.events(id) on delete cascade,
  device_id uuid references public.portaria_devices_v18(id) on delete set null,
  sentiment text not null check (sentiment in ('BOA','RUIM')),
  description text not null,
  inside_now bigint not null default 0,
  entered_total bigint not null default 0,
  temporary_out bigint not null default 0,
  created_at timestamptz not null default now()
);

create index if not exists idx_portaria_observations_v59_event_created
  on public.portaria_observations_v59(event_id, created_at desc);

alter table public.portaria_observations_v59 enable row level security;
revoke all on public.portaria_observations_v59 from anon, authenticated;

create or replace function public.portaria_device_observation_v59(
  p_device_key text,
  p_event_id bigint,
  p_sentiment text,
  p_description text
)
returns table(
  observation_id bigint,
  sentiment text,
  description text,
  created_at timestamptz,
  inside_now bigint,
  entered_total bigint,
  temporary_out bigint
)
language plpgsql
security definer
set search_path=''
as $function$
declare
  v_device uuid := private.hype_device_id(p_device_key);
  v_sentiment text := upper(trim(coalesce(p_sentiment,'')));
  v_description text := regexp_replace(trim(coalesce(p_description,'')), '\\s+', ' ', 'g');
  v_inside bigint := 0;
  v_entered bigint := 0;
  v_out bigint := 0;
  v_row public.portaria_observations_v59%rowtype;
begin
  if v_device is null then raise exception 'Computador não autorizado'; end if;
  if not exists(select 1 from public.events e where e.id=p_event_id) then
    raise exception 'Evento não encontrado';
  end if;
  if v_sentiment not in ('BOA','RUIM') then
    raise exception 'Escolha avaliação BOA ou RUIM';
  end if;
  if length(v_description) < 3 then
    raise exception 'Descreva a observação com pelo menos 3 caracteres';
  end if;
  if length(v_description) > 500 then
    raise exception 'Descrição muito longa (máximo 500 caracteres)';
  end if;

  select
    count(*) filter(where t.payment_status='Pago' and t.entry_status='Entrada utilizada' and not coalesce(t.temporary_exit,false)),
    count(*) filter(where t.payment_status='Pago' and t.entry_at is not null),
    count(*) filter(where t.payment_status='Pago' and coalesce(t.temporary_exit,false))
  into v_inside,v_entered,v_out
  from public.tickets t
  where t.event_id=p_event_id;

  insert into public.portaria_observations_v59(
    event_id,device_id,sentiment,description,inside_now,entered_total,temporary_out
  )
  values(
    p_event_id,v_device,v_sentiment,v_description,
    coalesce(v_inside,0),coalesce(v_entered,0),coalesce(v_out,0)
  )
  returning * into v_row;

  return query
    select v_row.id,v_row.sentiment,v_row.description,v_row.created_at,
           v_row.inside_now,v_row.entered_total,v_row.temporary_out;
end;
$function$;

grant execute on function public.portaria_device_observation_v59(text,bigint,text,text) to anon, authenticated;

create or replace function public.staff_live_checkin_v34(
  p_username text,
  p_password text,
  p_event_id bigint
)
returns jsonb
language plpgsql
security definer
set search_path=''
as $function$
declare
  v_event public.events%rowtype;
  v_paid bigint := 0;
  v_entered bigint := 0;
  v_inside bigint := 0;
  v_out bigint := 0;
  v_remaining bigint := 0;
  v_reentries bigint := 0;
  v_last bigint := 0;
  v_timeline jsonb := '[]'::jsonb;
  v_peak_inside bigint := 0;
  v_peak_inside_at timestamptz;
  v_peak_entry_count bigint := 0;
  v_peak_entry_at timestamptz;
  v_peak_exit_count bigint := 0;
  v_peak_exit_at timestamptz;
  v_good bigint := 0;
  v_bad bigint := 0;
  v_observations jsonb := '[]'::jsonb;
begin
  perform private.hype_require_staff(p_username,p_password,array['admin','gerente','caixa']);

  select e.* into v_event from public.events e where e.id=p_event_id;
  if not found then raise exception 'Evento não encontrado'; end if;

  select
    count(*) filter(where t.payment_status='Pago'),
    count(*) filter(where t.payment_status='Pago' and t.entry_at is not null),
    count(*) filter(where t.payment_status='Pago' and t.entry_status='Entrada utilizada' and not coalesce(t.temporary_exit,false)),
    count(*) filter(where t.payment_status='Pago' and coalesce(t.temporary_exit,false)),
    count(*) filter(where t.payment_status='Pago' and t.entry_at is null),
    coalesce(sum(coalesce(t.reentry_count,0)) filter(where t.payment_status='Pago'),0)
  into v_paid,v_entered,v_inside,v_out,v_remaining,v_reentries
  from public.tickets t
  where t.event_id=p_event_id;

  select coalesce(max(l.id),0)
  into v_last
  from public.portaria_logs_v18 l
  join public.tickets t on t.id=l.ticket_id
  where t.event_id=p_event_id
    and l.action in('ENTRY','TEMPORARY_EXIT','REENTRY');

  with event_logs as (
    select l.id,l.created_at,l.action,
      case when l.action in('ENTRY','REENTRY') then 1
           when l.action='TEMPORARY_EXIT' then -1 else 0 end as delta
    from public.portaria_logs_v18 l
    join public.tickets t on t.id=l.ticket_id
    where t.event_id=p_event_id
      and l.action in('ENTRY','TEMPORARY_EXIT','REENTRY')
  ),
  running as (
    select id,created_at,action,
      greatest(sum(delta) over(order by created_at,id rows between unbounded preceding and current row),0)::bigint as inside_count
    from event_logs
  ),
  recent as (
    select * from running order by created_at desc,id desc limit 500
  )
  select coalesce(
    jsonb_agg(jsonb_build_object('id',r.id,'at',r.created_at,'action',r.action,'inside',r.inside_count)
      order by r.created_at,r.id),
    '[]'::jsonb
  )
  into v_timeline
  from recent r;

  with event_logs as (
    select l.id,l.created_at,l.action,
      case when l.action in('ENTRY','REENTRY') then 1
           when l.action='TEMPORARY_EXIT' then -1 else 0 end as delta
    from public.portaria_logs_v18 l
    join public.tickets t on t.id=l.ticket_id
    where t.event_id=p_event_id
      and l.action in('ENTRY','TEMPORARY_EXIT','REENTRY')
  ),
  running as (
    select id,created_at,
      greatest(sum(delta) over(order by created_at,id rows between unbounded preceding and current row),0)::bigint as inside_count
    from event_logs
  )
  select coalesce(r.inside_count,0),r.created_at
  into v_peak_inside,v_peak_inside_at
  from running r
  order by r.inside_count desc,r.created_at asc,r.id asc
  limit 1;

  select count(*)::bigint,b.bucket
  into v_peak_entry_count,v_peak_entry_at
  from (
    select date_bin('15 minutes'::interval,l.created_at,'2001-01-01 00:00:00+00'::timestamptz) as bucket
    from public.portaria_logs_v18 l
    join public.tickets t on t.id=l.ticket_id
    where t.event_id=p_event_id and l.action in('ENTRY','REENTRY')
  ) b
  group by b.bucket
  order by count(*) desc,b.bucket asc
  limit 1;

  select count(*)::bigint,b.bucket
  into v_peak_exit_count,v_peak_exit_at
  from (
    select date_bin('15 minutes'::interval,l.created_at,'2001-01-01 00:00:00+00'::timestamptz) as bucket
    from public.portaria_logs_v18 l
    join public.tickets t on t.id=l.ticket_id
    where t.event_id=p_event_id and l.action='TEMPORARY_EXIT'
  ) b
  group by b.bucket
  order by count(*) desc,b.bucket asc
  limit 1;

  select count(*) filter(where o.sentiment='BOA'),
         count(*) filter(where o.sentiment='RUIM')
  into v_good,v_bad
  from public.portaria_observations_v59 o
  where o.event_id=p_event_id;

  select coalesce(
    jsonb_agg(jsonb_build_object(
      'id',x.id,'sentiment',x.sentiment,'description',x.description,'created_at',x.created_at,
      'inside_now',x.inside_now,'entered_total',x.entered_total,'temporary_out',x.temporary_out,
      'device_label',x.device_label
    ) order by x.created_at desc,x.id desc),
    '[]'::jsonb
  )
  into v_observations
  from (
    select o.id,o.sentiment,o.description,o.created_at,
           o.inside_now,o.entered_total,o.temporary_out,
           coalesce(d.label,'Portaria') as device_label
    from public.portaria_observations_v59 o
    left join public.portaria_devices_v18 d on d.id=o.device_id
    where o.event_id=p_event_id
    order by o.created_at desc,o.id desc
    limit 50
  ) x;

  return jsonb_build_object(
    'event_id',v_event.id,'event_name',v_event.name,'event_date',v_event.event_date,
    'paid_total',coalesce(v_paid,0),'entered_total',coalesce(v_entered,0),
    'inside_now',coalesce(v_inside,0),'temporary_out',coalesce(v_out,0),
    'remaining',coalesce(v_remaining,0),'reentries',coalesce(v_reentries,0),
    'last_log_id',coalesce(v_last,0),'timeline',coalesce(v_timeline,'[]'::jsonb),
    'peak_inside',coalesce(v_peak_inside,0),'peak_inside_at',v_peak_inside_at,
    'peak_entry_15m',coalesce(v_peak_entry_count,0),'peak_entry_15m_at',v_peak_entry_at,
    'peak_exit_15m',coalesce(v_peak_exit_count,0),'peak_exit_15m_at',v_peak_exit_at,
    'good_observations',coalesce(v_good,0),'bad_observations',coalesce(v_bad,0),
    'observations',coalesce(v_observations,'[]'::jsonb),'server_time',now()
  );
end;
$function$;

grant execute on function public.staff_live_checkin_v34(text,text,bigint) to anon, authenticated;
