-- =============================================================
-- HYPE V16 - DASHBOARD + PROMOTERS + CUPONS + LOTES AUTOMATICOS
-- Execute UMA VEZ no Supabase > SQL Editor > New query > Run.
--
-- NAO apaga eventos, ingressos, lotes, usuarios ou pagamentos.
-- Mantem tickets.price como valor final cobrado pelo Asaas.
-- =============================================================

create extension if not exists pgcrypto;

-- 1) Novos campos, todos compativeis com o sistema atual.
alter table public.ticket_lots
  add column if not exists auto_sequence boolean not null default false;

alter table public.tickets
  add column if not exists original_price numeric(12,2),
  add column if not exists discount_amount numeric(12,2) not null default 0,
  add column if not exists coupon_code text,
  add column if not exists promoter_code text;

update public.tickets
set original_price = coalesce(original_price, price),
    discount_amount = coalesce(discount_amount, 0)
where original_price is null or discount_amount is null;

-- 2) Promoters por evento.
create table if not exists public.promoters_v16 (
  id bigint generated by default as identity primary key,
  event_id bigint not null references public.events(id) on delete cascade,
  name text not null,
  code text not null,
  active boolean not null default true,
  created_at timestamptz not null default now(),
  unique(event_id, code)
);

create index if not exists idx_promoters_v16_event on public.promoters_v16(event_id, active);

-- 3) Cupons por evento.
create table if not exists public.coupons_v16 (
  id bigint generated by default as identity primary key,
  event_id bigint not null references public.events(id) on delete cascade,
  code text not null,
  discount_type text not null default 'percent' check (discount_type in ('percent','fixed')),
  discount_value numeric(12,2) not null default 0 check (discount_value >= 0),
  usage_limit integer not null default 0 check (usage_limit >= 0),
  starts_at timestamptz,
  ends_at timestamptz,
  active boolean not null default true,
  created_at timestamptz not null default now(),
  unique(event_id, code)
);

create index if not exists idx_coupons_v16_event on public.coupons_v16(event_id, active);

-- Nenhuma leitura direta das tabelas de gestao pelo navegador.
revoke all on public.promoters_v16, public.coupons_v16 from anon, authenticated;

-- =============================================================
-- HELPERS
-- =============================================================

create or replace function public.hype_lot_sold_count_v16(p_lot_id bigint)
returns bigint
language sql
security definer
set search_path = public
as $$
  select count(*)::bigint
  from public.tickets t
  where t.lot_id = p_lot_id
    and t.payment_status in ('Pendente','Pago');
$$;

-- =============================================================
-- 4) Catalogo publico V16: traz bloqueio automatico por sequencia.
-- =============================================================

drop function if exists public.public_lots_by_event_v16(bigint);
create function public.public_lots_by_event_v16(p_event_id bigint)
returns table(
  id bigint,
  event_id bigint,
  name text,
  sector text,
  price numeric,
  price_female numeric,
  price_male numeric,
  quantity_total integer,
  quantity_sold bigint,
  quantity_available bigint,
  starts_at timestamptz,
  ends_at timestamptz,
  active boolean,
  sort_order integer,
  auto_sequence boolean,
  auto_locked boolean
)
language sql
security definer
set search_path = public
as $$
  with lot_stats as (
    select
      l.*,
      count(t.id) filter (where t.payment_status in ('Pendente','Pago'))::bigint as sold
    from public.ticket_lots l
    left join public.tickets t on t.lot_id = l.id
    where l.event_id = p_event_id
    group by l.id
  )
  select
    l.id,
    l.event_id,
    l.name,
    l.sector,
    coalesce(l.price_female, l.price)::numeric as price,
    coalesce(l.price_female, l.price)::numeric as price_female,
    coalesce(l.price_male, l.price)::numeric as price_male,
    l.quantity_total,
    l.sold as quantity_sold,
    case when l.quantity_total = 0 then null
         else greatest(l.quantity_total - l.sold, 0)::bigint
    end as quantity_available,
    l.starts_at,
    l.ends_at,
    l.active,
    l.sort_order,
    coalesce(l.auto_sequence,false) as auto_sequence,
    case
      when coalesce(l.auto_sequence,false) = false then false
      else exists (
        select 1
        from lot_stats p
        where p.event_id = l.event_id
          and lower(coalesce(p.sector,'')) = lower(coalesce(l.sector,''))
          and p.active = true
          and (p.sort_order < l.sort_order or (p.sort_order = l.sort_order and p.id < l.id))
          and (p.quantity_total = 0 or p.sold < p.quantity_total)
      )
    end as auto_locked
  from lot_stats l
  join public.events e on e.id = l.event_id
  where l.active = true
    and e.active = true
  order by l.sort_order, l.id;
$$;

grant execute on function public.public_lots_by_event_v16(bigint) to anon, authenticated;

-- =============================================================
-- 5) Lista de lotes no Admin, incluindo inativos e sequencia auto.
-- =============================================================

drop function if exists public.staff_list_lots_v16(text,text,bigint);
create function public.staff_list_lots_v16(p_username text, p_password text, p_event_id bigint)
returns table(
  id bigint,
  event_id bigint,
  name text,
  sector text,
  price numeric,
  price_female numeric,
  price_male numeric,
  quantity_total integer,
  quantity_sold bigint,
  quantity_available bigint,
  starts_at timestamptz,
  ends_at timestamptz,
  active boolean,
  sort_order integer,
  auto_sequence boolean,
  auto_locked boolean
)
language plpgsql
security definer
set search_path = public, extensions
as $$
declare v_staff public.staff_users%rowtype;
begin
  select s.* into v_staff
  from public.staff_users s
  where s.username = trim(p_username)
    and s.active = true
    and s.password_hash = crypt(p_password, s.password_hash)
  limit 1;

  if not found or v_staff.role not in ('admin','gerente') then
    raise exception 'Sem permissao';
  end if;

  return query
  with lot_stats as (
    select
      l.*,
      count(t.id) filter (where t.payment_status in ('Pendente','Pago'))::bigint as sold
    from public.ticket_lots l
    left join public.tickets t on t.lot_id = l.id
    where l.event_id = p_event_id
    group by l.id
  )
  select
    l.id,l.event_id,l.name,l.sector,
    coalesce(l.price_female,l.price)::numeric,
    coalesce(l.price_female,l.price)::numeric,
    coalesce(l.price_male,l.price)::numeric,
    l.quantity_total,
    l.sold,
    case when l.quantity_total=0 then null else greatest(l.quantity_total-l.sold,0)::bigint end,
    l.starts_at,l.ends_at,l.active,l.sort_order,
    coalesce(l.auto_sequence,false),
    case
      when coalesce(l.auto_sequence,false)=false then false
      else exists (
        select 1 from lot_stats p
        where p.event_id=l.event_id
          and lower(coalesce(p.sector,''))=lower(coalesce(l.sector,''))
          and p.active=true
          and (p.sort_order<l.sort_order or (p.sort_order=l.sort_order and p.id<l.id))
          and (p.quantity_total=0 or p.sold<p.quantity_total)
      )
    end
  from lot_stats l
  order by l.sort_order,l.id;
end;
$$;

grant execute on function public.staff_list_lots_v16(text,text,bigint) to anon, authenticated;

-- =============================================================
-- 6) Criar/editar lote V16.
-- =============================================================

drop function if exists public.staff_upsert_lot_v16(text,text,bigint,bigint,text,text,numeric,numeric,integer,timestamptz,timestamptz,boolean,integer,boolean);
create function public.staff_upsert_lot_v16(
  p_username text,
  p_password text,
  p_event_id bigint,
  p_id bigint,
  p_name text,
  p_sector text,
  p_price_female numeric,
  p_price_male numeric,
  p_quantity_total integer,
  p_starts_at timestamptz,
  p_ends_at timestamptz,
  p_active boolean,
  p_sort_order integer,
  p_auto_sequence boolean
)
returns public.ticket_lots
language plpgsql
security definer
set search_path = public, extensions
as $$
declare
  v_staff public.staff_users%rowtype;
  v_lot public.ticket_lots%rowtype;
begin
  select s.* into v_staff
  from public.staff_users s
  where s.username=trim(p_username)
    and s.active=true
    and s.password_hash=crypt(p_password,s.password_hash)
  limit 1;

  if not found or v_staff.role not in ('admin','gerente') then raise exception 'Sem permissao'; end if;
  if not exists(select 1 from public.events e where e.id=p_event_id) then raise exception 'Evento nao encontrado'; end if;
  if coalesce(trim(p_sector),'')='' then raise exception 'Informe a categoria/setor'; end if;
  if coalesce(p_price_female,0)<0 or coalesce(p_price_male,0)<0 then raise exception 'Preco invalido'; end if;
  if coalesce(p_quantity_total,0)<0 then raise exception 'Quantidade invalida'; end if;
  if coalesce(p_auto_sequence,false) and coalesce(p_quantity_total,0)=0 then
    raise exception 'Lote automatico precisa ter quantidade maior que zero';
  end if;
  if p_starts_at is not null and p_ends_at is not null and p_ends_at<=p_starts_at then
    raise exception 'A expiracao precisa ser depois do inicio';
  end if;

  if coalesce(p_id,0)=0 then
    insert into public.ticket_lots(
      event_id,name,sector,price,price_female,price_male,quantity_total,starts_at,ends_at,active,sort_order,auto_sequence
    ) values (
      p_event_id,coalesce(nullif(trim(p_name),''),'1o Lote'),trim(p_sector),
      coalesce(p_price_female,0),coalesce(p_price_female,0),coalesce(p_price_male,0),
      coalesce(p_quantity_total,0),p_starts_at,p_ends_at,coalesce(p_active,true),coalesce(p_sort_order,0),coalesce(p_auto_sequence,false)
    ) returning * into v_lot;
  else
    update public.ticket_lots l
    set name=coalesce(nullif(trim(p_name),''),l.name),
        sector=trim(p_sector),
        price=coalesce(p_price_female,0),
        price_female=coalesce(p_price_female,0),
        price_male=coalesce(p_price_male,0),
        quantity_total=coalesce(p_quantity_total,0),
        starts_at=p_starts_at,
        ends_at=p_ends_at,
        active=coalesce(p_active,true),
        sort_order=coalesce(p_sort_order,l.sort_order),
        auto_sequence=coalesce(p_auto_sequence,false)
    where l.id=p_id and l.event_id=p_event_id
    returning * into v_lot;
    if not found then raise exception 'Categoria nao encontrada neste evento'; end if;
  end if;

  return v_lot;
end;
$$;

grant execute on function public.staff_upsert_lot_v16(text,text,bigint,bigint,text,text,numeric,numeric,integer,timestamptz,timestamptz,boolean,integer,boolean) to anon, authenticated;

-- =============================================================
-- 7) Cotacao publica: calcula cupom no banco, sem confiar no JS.
-- =============================================================

drop function if exists public.public_quote_v16(bigint,text,text);
create function public.public_quote_v16(p_lot_id bigint, p_gender text, p_coupon_code text default null)
returns table(
  ok boolean,
  message text,
  original_price numeric,
  discount_amount numeric,
  final_price numeric,
  coupon_code text
)
language plpgsql
security definer
set search_path = public
as $$
declare
  v_lot public.ticket_lots%rowtype;
  v_coupon public.coupons_v16%rowtype;
  v_original numeric(12,2);
  v_discount numeric(12,2) := 0;
  v_used bigint := 0;
  v_code text := upper(trim(coalesce(p_coupon_code,'')));
begin
  if p_gender not in ('Feminino','Masculino') then
    return query select false,'Selecione Feminino ou Masculino',0::numeric,0::numeric,0::numeric,null::text; return;
  end if;

  select * into v_lot from public.ticket_lots where id=p_lot_id and active=true;
  if not found then return query select false,'Categoria indisponivel',0::numeric,0::numeric,0::numeric,null::text; return; end if;

  v_original := case when p_gender='Masculino' then coalesce(v_lot.price_male,v_lot.price,0)
                     else coalesce(v_lot.price_female,v_lot.price,0) end;

  if v_code='' then
    return query select true,'Sem cupom',v_original,0::numeric,v_original,null::text; return;
  end if;

  select * into v_coupon
  from public.coupons_v16 c
  where c.event_id=v_lot.event_id and upper(c.code)=v_code and c.active=true
  limit 1;

  if not found then
    return query select false,'Cupom invalido',v_original,0::numeric,v_original,null::text; return;
  end if;
  if v_coupon.starts_at is not null and now()<v_coupon.starts_at then
    return query select false,'Cupom ainda nao iniciou',v_original,0::numeric,v_original,null::text; return;
  end if;
  if v_coupon.ends_at is not null and now()>=v_coupon.ends_at then
    return query select false,'Cupom expirado',v_original,0::numeric,v_original,null::text; return;
  end if;

  select count(*)::bigint into v_used
  from public.tickets t
  where t.event_id=v_lot.event_id
    and upper(coalesce(t.coupon_code,''))=v_code
    and t.payment_status in ('Pendente','Pago');

  if v_coupon.usage_limit>0 and v_used>=v_coupon.usage_limit then
    return query select false,'Limite do cupom atingido',v_original,0::numeric,v_original,null::text; return;
  end if;

  if v_coupon.discount_type='percent' then
    v_discount := round(v_original * least(v_coupon.discount_value,100) / 100, 2);
  else
    v_discount := least(v_original,v_coupon.discount_value);
  end if;

  if greatest(v_original-v_discount,0) <= 0 then
    return query select false,'O desconto precisa deixar um valor maior que zero para pagamento PIX',v_original,v_discount,v_original,null::text; return;
  end if;
  return query select true,'Cupom aplicado',v_original,v_discount,greatest(v_original-v_discount,0),v_coupon.code;
end;
$$;

grant execute on function public.public_quote_v16(bigint,text,text) to anon, authenticated;

-- =============================================================
-- 8) Pedido V16: genero + cupom + promoter + lote automatico.
-- =============================================================

drop function if exists public.create_manual_order_v16(text,text,text,text,text,bigint,text,text);
create function public.create_manual_order_v16(
  p_name text,
  p_phone text,
  p_email text,
  p_cpf text,
  p_gender text,
  p_lot_id bigint,
  p_coupon_code text default null,
  p_promoter_code text default null
)
returns table(
  id bigint,event_id bigint,ticket_code text,qr_token text,customer_name text,phone text,email text,cpf text,gender text,
  lot_id bigint,lot_name text,sector text,price numeric,original_price numeric,discount_amount numeric,coupon_code text,promoter_code text,
  payment_status text,entry_status text,purchased_at timestamptz
)
language plpgsql
security definer
set search_path = public, extensions
as $$
declare
  v_lot public.ticket_lots%rowtype; v_event public.events%rowtype; v_coupon public.coupons_v16%rowtype; v_promoter public.promoters_v16%rowtype;
  v_used integer; v_previous_open integer:=0; v_original numeric(12,2); v_discount numeric(12,2):=0; v_final numeric(12,2);
  v_coupon_used bigint:=0; v_coupon_code text:=upper(trim(coalesce(p_coupon_code,''))); v_promoter_code text:=upper(trim(coalesce(p_promoter_code,'')));
  v_id bigint; v_code text; v_qr text; v_purchased timestamptz;
begin
  if coalesce(trim(p_name),'')='' then raise exception 'Nome do cliente e obrigatorio'; end if;
  if coalesce(trim(p_email),'')='' or position('@' in p_email)=0 then raise exception 'E-mail invalido'; end if;
  if p_gender not in ('Feminino','Masculino') then raise exception 'Selecione Feminino ou Masculino'; end if;
  select * into v_lot from public.ticket_lots where id=p_lot_id for update;
  if not found or not v_lot.active then raise exception 'Categoria indisponivel'; end if;
  select * into v_event from public.events where id=v_lot.event_id;
  if not found or not v_event.active then raise exception 'Evento indisponivel'; end if;
  if v_lot.starts_at is not null and now()<v_lot.starts_at then raise exception 'As vendas desta categoria ainda nao comecaram'; end if;
  if v_lot.ends_at is not null and now()>=v_lot.ends_at then raise exception 'As vendas desta categoria ja encerraram'; end if;
  if coalesce(v_lot.auto_sequence,false) then
    select count(*)::integer into v_previous_open
    from public.ticket_lots p
    where p.event_id=v_lot.event_id
      and lower(coalesce(p.sector,''))=lower(coalesce(v_lot.sector,''))
      and p.active=true
      and (p.sort_order<v_lot.sort_order or (p.sort_order=v_lot.sort_order and p.id<v_lot.id))
      and (p.quantity_total=0 or (select count(*) from public.tickets tp where tp.lot_id=p.id and tp.payment_status in ('Pendente','Pago'))<p.quantity_total);
    if v_previous_open>0 then raise exception 'Este lote sera liberado automaticamente quando o anterior esgotar'; end if;
  end if;
  select count(*)::integer into v_used from public.tickets t where t.lot_id=v_lot.id and t.payment_status in ('Pendente','Pago');
  if v_lot.quantity_total>0 and v_used>=v_lot.quantity_total then raise exception 'Categoria esgotada'; end if;
  v_original:=case when p_gender='Masculino' then coalesce(v_lot.price_male,v_lot.price,0) else coalesce(v_lot.price_female,v_lot.price,0) end;
  if v_coupon_code<>'' then
    select * into v_coupon from public.coupons_v16 c where c.event_id=v_lot.event_id and upper(c.code)=v_coupon_code and c.active=true for update;
    if not found then raise exception 'Cupom invalido'; end if;
    if v_coupon.starts_at is not null and now()<v_coupon.starts_at then raise exception 'Cupom ainda nao iniciou'; end if;
    if v_coupon.ends_at is not null and now()>=v_coupon.ends_at then raise exception 'Cupom expirado'; end if;
    select count(*)::bigint into v_coupon_used from public.tickets t where t.event_id=v_lot.event_id and upper(coalesce(t.coupon_code,''))=v_coupon_code and t.payment_status in ('Pendente','Pago');
    if v_coupon.usage_limit>0 and v_coupon_used>=v_coupon.usage_limit then raise exception 'Limite do cupom atingido'; end if;
    if v_coupon.discount_type='percent' then v_discount:=round(v_original*least(v_coupon.discount_value,100)/100,2); else v_discount:=least(v_original,v_coupon.discount_value); end if;
  end if;
  if v_promoter_code<>'' then
    select * into v_promoter from public.promoters_v16 p where p.event_id=v_lot.event_id and upper(p.code)=v_promoter_code and p.active=true limit 1;
    if not found then raise exception 'Codigo de promoter invalido'; end if;
  end if;
  v_final:=greatest(v_original-v_discount,0);
  if v_final<=0 then raise exception 'O desconto precisa deixar um valor maior que zero para pagamento PIX'; end if;
  loop v_code:='HYPE-'||upper(substr(md5(random()::text||clock_timestamp()::text),1,10)); exit when not exists(select 1 from public.tickets t where t.ticket_code=v_code); end loop;
  v_qr:=gen_random_uuid()::text;
  insert into public.tickets(event_id,lot_id,customer_name,phone,email,cpf,gender,price,original_price,discount_amount,coupon_code,promoter_code,ticket_code,qr_token,payment_status,entry_status)
  values(v_lot.event_id,v_lot.id,trim(p_name),trim(p_phone),lower(trim(p_email)),trim(p_cpf),p_gender,v_final,v_original,v_discount,nullif(v_coupon_code,''),nullif(v_promoter_code,''),v_code,v_qr,'Pendente','Não utilizado')
  returning tickets.id,tickets.purchased_at into v_id,v_purchased;
  return query select v_id,v_lot.event_id,v_code,v_qr,trim(p_name),trim(p_phone),lower(trim(p_email)),trim(p_cpf),p_gender,v_lot.id,v_lot.name,v_lot.sector,v_final,v_original,v_discount,nullif(v_coupon_code,''),nullif(v_promoter_code,''),'Pendente'::text,'Não utilizado'::text,v_purchased;
end;
$$;

grant execute on function public.create_manual_order_v16(text,text,text,text,text,bigint,text,text) to anon, authenticated;

-- =============================================================
-- 9) Gestao de promoters - somente ADMIN.
-- =============================================================

drop function if exists public.staff_list_promoters_v16(text,text,bigint);
create function public.staff_list_promoters_v16(p_username text,p_password text,p_event_id bigint)
returns table(id bigint,event_id bigint,name text,code text,active boolean,sales_count bigint,paid_count bigint,revenue numeric)
language plpgsql security definer set search_path=public,extensions as $$
declare v_staff public.staff_users%rowtype;
begin
  select * into v_staff from public.staff_users where username=trim(p_username) and active=true and password_hash=crypt(p_password,password_hash);
  if not found or v_staff.role<>'admin' then raise exception 'Sem permissao'; end if;
  return query
  select p.id,p.event_id,p.name,p.code,p.active,
         count(t.id) filter(where t.payment_status in ('Pendente','Pago'))::bigint,
         count(t.id) filter(where t.payment_status='Pago')::bigint,
         coalesce(sum(t.price) filter(where t.payment_status='Pago'),0)::numeric
  from public.promoters_v16 p
  left join public.tickets t on t.event_id=p.event_id and upper(coalesce(t.promoter_code,''))=upper(p.code)
  where p.event_id=p_event_id
  group by p.id order by p.created_at desc;
end; $$;

grant execute on function public.staff_list_promoters_v16(text,text,bigint) to anon, authenticated;

drop function if exists public.staff_upsert_promoter_v16(text,text,bigint,bigint,text,text,boolean);
create function public.staff_upsert_promoter_v16(p_username text,p_password text,p_event_id bigint,p_id bigint,p_name text,p_code text,p_active boolean)
returns public.promoters_v16
language plpgsql security definer set search_path=public,extensions as $$
declare v_staff public.staff_users%rowtype; v_row public.promoters_v16%rowtype; v_code text:=upper(trim(p_code));
begin
  select * into v_staff from public.staff_users where username=trim(p_username) and active=true and password_hash=crypt(p_password,password_hash);
  if not found or v_staff.role<>'admin' then raise exception 'Sem permissao'; end if;
  if coalesce(trim(p_name),'')='' or v_code='' then raise exception 'Informe nome e codigo do promoter'; end if;
  if coalesce(p_id,0)=0 then
    insert into public.promoters_v16(event_id,name,code,active) values(p_event_id,trim(p_name),v_code,coalesce(p_active,true)) returning * into v_row;
  else
    update public.promoters_v16 set name=trim(p_name),code=v_code,active=coalesce(p_active,true) where id=p_id and event_id=p_event_id returning * into v_row;
    if not found then raise exception 'Promoter nao encontrado'; end if;
  end if;
  return v_row;
exception when unique_violation then raise exception 'Este codigo de promoter ja existe neste evento';
end; $$;

grant execute on function public.staff_upsert_promoter_v16(text,text,bigint,bigint,text,text,boolean) to anon, authenticated;

-- =============================================================
-- 10) Gestao de cupons - somente ADMIN.
-- =============================================================

drop function if exists public.staff_list_coupons_v16(text,text,bigint);
create function public.staff_list_coupons_v16(p_username text,p_password text,p_event_id bigint)
returns table(id bigint,event_id bigint,code text,discount_type text,discount_value numeric,usage_limit integer,uses_count bigint,starts_at timestamptz,ends_at timestamptz,active boolean)
language plpgsql security definer set search_path=public,extensions as $$
declare v_staff public.staff_users%rowtype;
begin
  select * into v_staff from public.staff_users where username=trim(p_username) and active=true and password_hash=crypt(p_password,password_hash);
  if not found or v_staff.role<>'admin' then raise exception 'Sem permissao'; end if;
  return query
  select c.id,c.event_id,c.code,c.discount_type,c.discount_value,c.usage_limit,
         count(t.id) filter(where t.payment_status in ('Pendente','Pago'))::bigint,
         c.starts_at,c.ends_at,c.active
  from public.coupons_v16 c
  left join public.tickets t on t.event_id=c.event_id and upper(coalesce(t.coupon_code,''))=upper(c.code)
  where c.event_id=p_event_id
  group by c.id order by c.created_at desc;
end; $$;

grant execute on function public.staff_list_coupons_v16(text,text,bigint) to anon, authenticated;

drop function if exists public.staff_upsert_coupon_v16(text,text,bigint,bigint,text,text,numeric,integer,timestamptz,timestamptz,boolean);
create function public.staff_upsert_coupon_v16(
  p_username text,p_password text,p_event_id bigint,p_id bigint,p_code text,p_discount_type text,p_discount_value numeric,p_usage_limit integer,p_starts_at timestamptz,p_ends_at timestamptz,p_active boolean
)
returns public.coupons_v16
language plpgsql security definer set search_path=public,extensions as $$
declare v_staff public.staff_users%rowtype; v_row public.coupons_v16%rowtype; v_code text:=upper(trim(p_code));
begin
  select * into v_staff from public.staff_users where username=trim(p_username) and active=true and password_hash=crypt(p_password,password_hash);
  if not found or v_staff.role<>'admin' then raise exception 'Sem permissao'; end if;
  if v_code='' then raise exception 'Informe o codigo do cupom'; end if;
  if p_discount_type not in ('percent','fixed') then raise exception 'Tipo de desconto invalido'; end if;
  if coalesce(p_discount_value,0)<0 then raise exception 'Desconto invalido'; end if;
  if p_discount_type='percent' and p_discount_value>100 then raise exception 'Percentual maximo e 100'; end if;
  if coalesce(p_usage_limit,0)<0 then raise exception 'Limite invalido'; end if;
  if p_starts_at is not null and p_ends_at is not null and p_ends_at<=p_starts_at then raise exception 'Periodo do cupom invalido'; end if;
  if coalesce(p_id,0)=0 then
    insert into public.coupons_v16(event_id,code,discount_type,discount_value,usage_limit,starts_at,ends_at,active)
    values(p_event_id,v_code,p_discount_type,p_discount_value,coalesce(p_usage_limit,0),p_starts_at,p_ends_at,coalesce(p_active,true)) returning * into v_row;
  else
    update public.coupons_v16 set code=v_code,discount_type=p_discount_type,discount_value=p_discount_value,usage_limit=coalesce(p_usage_limit,0),starts_at=p_starts_at,ends_at=p_ends_at,active=coalesce(p_active,true)
    where id=p_id and event_id=p_event_id returning * into v_row;
    if not found then raise exception 'Cupom nao encontrado'; end if;
  end if;
  return v_row;
exception when unique_violation then raise exception 'Este cupom ja existe neste evento';
end; $$;

grant execute on function public.staff_upsert_coupon_v16(text,text,bigint,bigint,text,text,numeric,integer,timestamptz,timestamptz,boolean) to anon, authenticated;

-- =============================================================
-- 11) Pedidos completos para dashboard. PORTARIA nao tem acesso.
-- =============================================================

drop function if exists public.staff_list_tickets_v16(text,text,text);
create function public.staff_list_tickets_v16(p_username text,p_password text,p_search text default '')
returns table(
  id bigint,event_id bigint,event_name text,ticket_code text,customer_name text,phone text,email text,cpf text,gender text,
  lot_id bigint,lot_name text,sector text,price numeric,original_price numeric,discount_amount numeric,coupon_code text,promoter_code text,
  payment_method text,payment_status text,entry_status text,purchased_at timestamptz,paid_at timestamptz,entry_at timestamptz,email_sent_at timestamptz
)
language plpgsql security definer set search_path=public,extensions as $$
declare v_staff public.staff_users%rowtype;
begin
  select * into v_staff from public.staff_users where username=trim(p_username) and active=true and password_hash=crypt(p_password,password_hash);
  if not found or v_staff.role not in ('admin','gerente','caixa') then raise exception 'Sem permissao'; end if;
  return query
  select t.id,t.event_id,e.name,t.ticket_code,t.customer_name,t.phone,t.email,t.cpf,t.gender,t.lot_id,l.name,l.sector,t.price,
         coalesce(t.original_price,t.price),coalesce(t.discount_amount,0),t.coupon_code,t.promoter_code,t.payment_method,t.payment_status,t.entry_status,
         t.purchased_at,t.paid_at,t.entry_at,t.email_sent_at
  from public.tickets t
  join public.ticket_lots l on l.id=t.lot_id
  join public.events e on e.id=t.event_id
  where coalesce(p_search,'')=''
     or lower(t.customer_name) like '%'||lower(p_search)||'%'
     or lower(t.ticket_code) like '%'||lower(p_search)||'%'
     or lower(coalesce(t.phone,'')) like '%'||lower(p_search)||'%'
     or lower(coalesce(t.email,'')) like '%'||lower(p_search)||'%'
     or lower(coalesce(t.promoter_code,'')) like '%'||lower(p_search)||'%'
     or lower(coalesce(t.coupon_code,'')) like '%'||lower(p_search)||'%'
     or lower(coalesce(e.name,'')) like '%'||lower(p_search)||'%'
  order by t.created_at desc;
end; $$;

grant execute on function public.staff_list_tickets_v16(text,text,text) to anon, authenticated;

-- FIM V16

-- =============================================================
-- HYPE V16.1 - COMPATIBILIDADE COM CACHE/FRONTEND V12
-- Mantem o site funcionando mesmo se um navegador ainda estiver
-- com uma versao antiga do app.js em cache.
-- =============================================================

drop function if exists public.create_manual_order_v12(text,text,text,bigint,text,text);

create function public.create_manual_order_v12(
  p_cpf text,
  p_email text,
  p_gender text,
  p_lot_id bigint,
  p_name text,
  p_phone text
)
returns table(
  id bigint,
  event_id bigint,
  ticket_code text,
  qr_token text,
  customer_name text,
  phone text,
  email text,
  cpf text,
  gender text,
  lot_id bigint,
  lot_name text,
  sector text,
  price numeric,
  original_price numeric,
  discount_amount numeric,
  coupon_code text,
  promoter_code text,
  payment_status text,
  entry_status text,
  purchased_at timestamptz
)
language sql
security definer
set search_path = public, extensions
as $$
  select *
  from public.create_manual_order_v16(
    p_name,
    p_phone,
    p_email,
    p_cpf,
    p_gender,
    p_lot_id,
    null,
    null
  );
$$;

grant execute on function public.create_manual_order_v12(text,text,text,bigint,text,text)
to anon, authenticated;
