-- HYPE EVENT TICKETING - Supabase / PostgreSQL
-- Execute este arquivo inteiro no SQL Editor do Supabase.

create extension if not exists pgcrypto;

create table if not exists public.events (
  id bigint generated by default as identity primary key,
  name text not null,
  event_date date,
  opening_time time,
  closing_time time,
  venue text,
  pix_key text not null default '',
  active boolean not null default true,
  created_at timestamptz not null default now()
);

create table if not exists public.ticket_lots (
  id bigint generated by default as identity primary key,
  event_id bigint not null references public.events(id) on delete cascade,
  name text not null,
  sector text not null default 'Pista',
  price numeric(12,2) not null check (price >= 0),
  quantity_total integer not null default 0 check (quantity_total >= 0),
  starts_at timestamptz,
  ends_at timestamptz,
  active boolean not null default true,
  sort_order integer not null default 0,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.staff_users (
  id bigint generated by default as identity primary key,
  name text not null,
  username text not null unique,
  password_hash text not null,
  role text not null check (role in ('admin','gerente','caixa','portaria')),
  active boolean not null default true,
  created_at timestamptz not null default now()
);

create table if not exists public.tickets (
  id bigint generated by default as identity primary key,
  event_id bigint not null references public.events(id) on delete cascade,
  lot_id bigint not null references public.ticket_lots(id) on delete restrict,
  customer_name text not null,
  phone text,
  cpf text,
  gender text,
  price numeric(12,2) not null check (price >= 0),
  ticket_code text not null unique,
  qr_token text not null unique,
  payment_status text not null default 'Pendente' check (payment_status in ('Pendente','Pago','Cancelado')),
  entry_status text not null default 'Não utilizado' check (entry_status in ('Não utilizado','Entrada utilizada')),
  purchased_at timestamptz not null default now(),
  paid_at timestamptz,
  entry_at timestamptz,
  entry_by bigint,
  entry_device text,
  canceled_at timestamptz,
  created_at timestamptz not null default now()
);

create index if not exists idx_ticket_lots_event on public.ticket_lots(event_id, active, sort_order);
create index if not exists idx_tickets_event on public.tickets(event_id, created_at desc);
create index if not exists idx_tickets_lot on public.tickets(lot_id);
create index if not exists idx_tickets_name on public.tickets(lower(customer_name));
create index if not exists idx_tickets_phone on public.tickets(phone);
create index if not exists idx_tickets_code on public.tickets(ticket_code);

alter table public.tickets
  drop constraint if exists tickets_entry_by_fkey;
alter table public.tickets
  add constraint tickets_entry_by_fkey
  foreign key (entry_by) references public.staff_users(id) on delete set null;

create table if not exists public.audit_logs (
  id bigint generated by default as identity primary key,
  staff_user_id bigint references public.staff_users(id) on delete set null,
  action text not null,
  ticket_id bigint references public.tickets(id) on delete set null,
  metadata jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now()
);

create or replace function public.set_updated_at()
returns trigger language plpgsql as $$
begin
  new.updated_at = now();
  return new;
end;
$$;

drop trigger if exists trg_ticket_lots_updated on public.ticket_lots;
create trigger trg_ticket_lots_updated
before update on public.ticket_lots
for each row execute function public.set_updated_at();

-- RLS: ninguém acessa as tabelas diretamente pelo client.
alter table public.events enable row level security;
alter table public.ticket_lots enable row level security;
alter table public.tickets enable row level security;
alter table public.staff_users enable row level security;
alter table public.audit_logs enable row level security;

drop policy if exists deny_events_anon on public.events;
drop policy if exists deny_lots_anon on public.ticket_lots;
drop policy if exists deny_tickets_anon on public.tickets;
drop policy if exists deny_staff_anon on public.staff_users;
drop policy if exists deny_logs_anon on public.audit_logs;

create policy deny_events_anon on public.events for all to anon using (false) with check (false);
create policy deny_lots_anon on public.ticket_lots for all to anon using (false) with check (false);
create policy deny_tickets_anon on public.tickets for all to anon using (false) with check (false);
create policy deny_staff_anon on public.staff_users for all to anon using (false) with check (false);
create policy deny_logs_anon on public.audit_logs for all to anon using (false) with check (false);

grant usage on schema public to anon, authenticated;
revoke all on public.events, public.ticket_lots, public.tickets, public.staff_users, public.audit_logs from anon, authenticated;

-- Helper: autenticação da equipe. Senhas são armazenadas com bcrypt via crypt().
create or replace function public.verify_staff(p_username text, p_password text)
returns table(id bigint, name text, username text, role text)
language sql
security definer
set search_path = public, extensions
as $$
  select s.id, s.name, s.username, s.role
  from public.staff_users s
  where s.username = trim(p_username)
    and s.active = true
    and s.password_hash = crypt(p_password, s.password_hash)
  limit 1;
$$;

grant execute on function public.verify_staff(text,text) to anon, authenticated;

-- Consulta pública dos lotes disponíveis.
create or replace function public.public_lots()
returns table(
  id bigint,
  name text,
  sector text,
  price numeric,
  quantity_total integer,
  quantity_sold bigint,
  quantity_available bigint,
  starts_at timestamptz,
  ends_at timestamptz,
  active boolean
)
language sql
security definer
set search_path = public
as $$
  select
    l.id,
    l.name,
    l.sector,
    l.price,
    l.quantity_total,
    count(t.id) filter (where t.payment_status in ('Pendente','Pago'))::bigint as quantity_sold,
    case when l.quantity_total = 0 then null
         else greatest(l.quantity_total - count(t.id) filter (where t.payment_status in ('Pendente','Pago')), 0)::bigint
    end as quantity_available,
    l.starts_at,
    l.ends_at,
    l.active
  from public.ticket_lots l
  left join public.tickets t on t.lot_id = l.id
  join public.events e on e.id = l.event_id and e.active = true
  where l.active = true
  group by l.id
  order by l.sort_order, l.id;
$$;

grant execute on function public.public_lots() to anon, authenticated;

-- Cria ingresso com trava transacional para não estourar o estoque em compras simultâneas.
create or replace function public.create_ticket(
  p_name text,
  p_phone text,
  p_cpf text,
  p_gender text,
  p_lot_id bigint
)
returns table(
  id bigint,
  ticket_code text,
  qr_token text,
  customer_name text,
  phone text,
  cpf text,
  gender text,
  lot_id bigint,
  lot_name text,
  sector text,
  price numeric,
  payment_status text,
  entry_status text,
  purchased_at timestamptz
)
language plpgsql
security definer
set search_path = public, extensions
as $$
declare
  v_lot public.ticket_lots%rowtype;
  v_event public.events%rowtype;
  v_used integer;
  v_ticket_id bigint;
  v_code text;
  v_qr text;
begin
  if coalesce(trim(p_name),'') = '' then
    raise exception 'Nome do cliente é obrigatório';
  end if;

  select * into v_lot
  from public.ticket_lots
  where id = p_lot_id and active = true
  for update;

  if not found then
    raise exception 'Lote indisponível';
  end if;

  select * into v_event from public.events where id = v_lot.event_id and active = true;
  if not found then raise exception 'Evento indisponível'; end if;

  if v_lot.starts_at is not null and now() < v_lot.starts_at then
    raise exception 'Este lote ainda não abriu';
  end if;
  if v_lot.ends_at is not null and now() >= v_lot.ends_at then
    raise exception 'Este lote já encerrou';
  end if;

  select count(*)::integer into v_used
  from public.tickets
  where lot_id = v_lot.id and payment_status in ('Pendente','Pago');

  if v_lot.quantity_total > 0 and v_used >= v_lot.quantity_total then
    raise exception 'Lote esgotado';
  end if;

  v_code := 'HYPE-' || upper(substr(replace(gen_random_uuid()::text,'-',''),1,8));
  v_qr := gen_random_uuid()::text;

  insert into public.tickets(event_id, lot_id, customer_name, phone, cpf, gender, price, ticket_code, qr_token)
  values(v_lot.event_id, v_lot.id, trim(p_name), nullif(trim(p_phone),''), nullif(trim(p_cpf),''), nullif(trim(p_gender),''), v_lot.price, v_code, v_qr)
  returning tickets.id into v_ticket_id;

  return query
  select t.id, t.ticket_code, t.qr_token, t.customer_name, t.phone, t.cpf, t.gender,
         t.lot_id, l.name, l.sector, t.price, t.payment_status, t.entry_status, t.purchased_at
  from public.tickets t
  join public.ticket_lots l on l.id = t.lot_id
  where t.id = v_ticket_id;
end;
$$;

grant execute on function public.create_ticket(text,text,text,text,bigint) to anon, authenticated;

create or replace function public.public_get_ticket(p_code text)
returns table(
  id bigint,
  ticket_code text,
  customer_name text,
  phone text,
  gender text,
  lot_name text,
  sector text,
  price numeric,
  payment_status text,
  entry_status text,
  purchased_at timestamptz,
  paid_at timestamptz,
  entry_at timestamptz
)
language sql
security definer
set search_path = public
as $$
  select t.id, t.ticket_code, t.customer_name, t.phone, t.gender, l.name, l.sector,
         t.price, t.payment_status, t.entry_status, t.purchased_at, t.paid_at, t.entry_at
  from public.tickets t
  join public.ticket_lots l on l.id=t.lot_id
  where lower(t.ticket_code)=lower(trim(p_code))
  limit 1;
$$;

grant execute on function public.public_get_ticket(text) to anon, authenticated;

-- Lista para Admin/Caixa/Portaria.
create or replace function public.staff_list_tickets(p_username text, p_password text, p_search text default '')
returns table(
  id bigint,
  ticket_code text,
  customer_name text,
  phone text,
  cpf text,
  gender text,
  lot_id bigint,
  lot_name text,
  sector text,
  price numeric,
  payment_status text,
  entry_status text,
  purchased_at timestamptz,
  paid_at timestamptz,
  entry_at timestamptz
)
language plpgsql
security definer
set search_path = public
as $$
declare v_role text; begin
  select role into v_role from public.verify_staff(p_username,p_password) limit 1;
  if v_role is null then raise exception 'Acesso negado'; end if;
  return query
  select t.id,t.ticket_code,t.customer_name,t.phone,t.cpf,t.gender,t.lot_id,l.name,l.sector,t.price,
         t.payment_status,t.entry_status,t.purchased_at,t.paid_at,t.entry_at
  from public.tickets t join public.ticket_lots l on l.id=t.lot_id
  where coalesce(p_search,'')='' or lower(t.customer_name) like '%'||lower(p_search)||'%'
      or lower(t.ticket_code) like '%'||lower(p_search)||'%'
      or coalesce(t.phone,'') like '%'||p_search||'%'
  order by t.created_at desc;
end; $$;

grant execute on function public.staff_list_tickets(text,text,text) to anon, authenticated;

create or replace function public.staff_set_payment(p_username text, p_password text, p_ticket_id bigint, p_status text)
returns public.tickets
language plpgsql
security definer
set search_path = public, extensions
as $$
declare v_staff public.staff_users%rowtype; v_ticket public.tickets%rowtype;
begin
  select * into v_staff from public.staff_users where username=trim(p_username) and active=true and password_hash=crypt(p_password,password_hash);
  if not found then raise exception 'Acesso negado'; end if;
  if v_staff.role not in ('admin','gerente','caixa') then raise exception 'Sem permissão'; end if;
  if p_status not in ('Pendente','Pago','Cancelado') then raise exception 'Status inválido'; end if;

  update public.tickets
  set payment_status=p_status,
      paid_at=case when p_status='Pago' then coalesce(paid_at,now()) else null end,
      canceled_at=case when p_status='Cancelado' then coalesce(canceled_at,now()) else null end
  where id=p_ticket_id
  returning * into v_ticket;
  if not found then raise exception 'Ingresso não encontrado'; end if;

  insert into public.audit_logs(staff_user_id, action, ticket_id, metadata)
  values(v_staff.id, 'ALTERAR_PAGAMENTO', v_ticket.id, jsonb_build_object('status',p_status));
  return v_ticket;
end; $$;

grant execute on function public.staff_set_payment(text,text,bigint,text) to anon, authenticated;

-- Validação ATÔMICA: duas portarias tentando o mesmo QR ao mesmo tempo não conseguem liberar duas vezes.
create or replace function public.staff_validate_entry(
  p_username text,
  p_password text,
  p_code text,
  p_device text default null
)
returns table(
  ok boolean,
  message text,
  ticket_id bigint,
  ticket_code text,
  customer_name text,
  lot_name text,
  sector text,
  price numeric,
  payment_status text,
  entry_status text,
  entry_at timestamptz
)
language plpgsql
security definer
set search_path = public
as $$
declare
  v_staff public.staff_users%rowtype;
  v_ticket public.tickets%rowtype;
  v_lot text;
begin
  select * into v_staff from public.staff_users where username=trim(p_username) and active=true and password_hash=crypt(p_password,password_hash);
  if not found then raise exception 'Acesso negado'; end if;
  if v_staff.role not in ('admin','gerente','portaria') then raise exception 'Sem permissão'; end if;

  select t.* into v_ticket
  from public.tickets t
  where lower(t.ticket_code)=lower(trim(p_code)) or lower(t.qr_token)=lower(trim(p_code))
  for update;

  if not found then
    return query select false,'INGRESSO NÃO ENCONTRADO',null::bigint,null::text,null::text,null::text,null::text,null::numeric,null::text,null::text,null::timestamptz;
    return;
  end if;

  select name into v_lot from public.ticket_lots where id=v_ticket.lot_id;

  if v_ticket.payment_status='Cancelado' then
    return query select false,'INGRESSO CANCELADO',v_ticket.id,v_ticket.ticket_code,v_ticket.customer_name,v_lot,(select sector from ticket_lots where id=v_ticket.lot_id),v_ticket.price,v_ticket.payment_status,v_ticket.entry_status,v_ticket.entry_at;
    return;
  end if;
  if v_ticket.payment_status<>'Pago' then
    return query select false,'PAGAMENTO NÃO CONFIRMADO',v_ticket.id,v_ticket.ticket_code,v_ticket.customer_name,v_lot,(select sector from ticket_lots where id=v_ticket.lot_id),v_ticket.price,v_ticket.payment_status,v_ticket.entry_status,v_ticket.entry_at;
    return;
  end if;
  if v_ticket.entry_status='Entrada utilizada' then
    return query select false,'INGRESSO JÁ UTILIZADO',v_ticket.id,v_ticket.ticket_code,v_ticket.customer_name,v_lot,(select sector from ticket_lots where id=v_ticket.lot_id),v_ticket.price,v_ticket.payment_status,v_ticket.entry_status,v_ticket.entry_at;
    return;
  end if;

  update public.tickets
  set entry_status='Entrada utilizada', entry_at=now(), entry_by=v_staff.id, entry_device=coalesce(nullif(trim(p_device),''),'Portaria')
  where id=v_ticket.id;

  insert into public.audit_logs(staff_user_id, action, ticket_id, metadata)
  values(v_staff.id,'ENTRADA_LIBERADA',v_ticket.id,jsonb_build_object('device',p_device));

  return query
  select true,'ENTRADA LIBERADA',v_ticket.id,v_ticket.ticket_code,v_ticket.customer_name,v_lot,
         (select sector from ticket_lots where id=v_ticket.lot_id),v_ticket.price,'Pago','Entrada utilizada',now();
end; $$;

grant execute on function public.staff_validate_entry(text,text,text,text) to anon, authenticated;

create or replace function public.staff_save_pix(p_username text,p_password text,p_pix text)
returns boolean language plpgsql security definer set search_path=public as $$
declare v_role text; begin
  select role into v_role from public.verify_staff(p_username,p_password) limit 1;
  if v_role is null or v_role not in ('admin','gerente') then raise exception 'Sem permissão'; end if;
  update public.events set pix_key=coalesce(p_pix,'') where active=true;
  return true;
end; $$;

grant execute on function public.staff_save_pix(text,text,text) to anon, authenticated;

create or replace function public.public_pix_key()
returns text language sql security definer set search_path=public as $$
  select coalesce((select pix_key from public.events where active=true order by id limit 1),'');
$$;
grant execute on function public.public_pix_key() to anon, authenticated;

create or replace function public.staff_upsert_lot(
  p_username text,p_password text,p_id bigint,p_name text,p_sector text,p_price numeric,
  p_quantity_total integer,p_starts_at timestamptz,p_ends_at timestamptz,p_active boolean,p_sort_order integer
)
returns public.ticket_lots
language plpgsql security definer set search_path=public as $$
declare v_staff public.staff_users%rowtype; v_lot public.ticket_lots%rowtype; v_event_id bigint;
begin
  select * into v_staff from public.staff_users where username=trim(p_username) and active=true and password_hash=crypt(p_password,password_hash);
  if not found or v_staff.role not in ('admin','gerente') then raise exception 'Sem permissão'; end if;
  select id into v_event_id from public.events where active=true order by id limit 1;
  if v_event_id is null then raise exception 'Nenhum evento ativo'; end if;
  if coalesce(p_name,'')='' then raise exception 'Nome do lote é obrigatório'; end if;
  if p_price<0 or p_quantity_total<0 then raise exception 'Preço/quantidade inválidos'; end if;
  if p_starts_at is not null and p_ends_at is not null and p_ends_at<=p_starts_at then raise exception 'Horários inválidos'; end if;

  if coalesce(p_id,0)=0 then
    insert into public.ticket_lots(event_id,name,sector,price,quantity_total,starts_at,ends_at,active,sort_order)
    values(v_event_id,p_name,coalesce(nullif(p_sector,''),'Pista'),p_price,p_quantity_total,p_starts_at,p_ends_at,coalesce(p_active,true),coalesce(p_sort_order,0))
    returning * into v_lot;
  else
    update public.ticket_lots set name=p_name,sector=coalesce(nullif(p_sector,''),'Pista'),price=p_price,quantity_total=p_quantity_total,
      starts_at=p_starts_at,ends_at=p_ends_at,active=coalesce(p_active,true),sort_order=coalesce(p_sort_order,sort_order)
    where id=p_id returning * into v_lot;
    if not found then raise exception 'Lote não encontrado'; end if;
  end if;
  return v_lot;
end; $$;

grant execute on function public.staff_upsert_lot(text,text,bigint,text,text,numeric,integer,timestamptz,timestamptz,boolean,integer) to anon, authenticated;

create or replace function public.staff_add_user(
  p_username text,p_password text,p_name text,p_new_username text,p_new_password text,p_role text
)
returns public.staff_users
language plpgsql security definer set search_path=public,extensions as $$
declare v_staff public.staff_users%rowtype; v_new public.staff_users%rowtype;
begin
  select * into v_staff from public.staff_users where username=trim(p_username) and active=true and password_hash=crypt(p_password,password_hash);
  if not found or v_staff.role not in ('admin','gerente') then raise exception 'Sem permissão'; end if;
  if p_role not in ('admin','gerente','caixa','portaria') then raise exception 'Perfil inválido'; end if;
  insert into public.staff_users(name,username,password_hash,role) values(trim(p_name),trim(p_new_username),crypt(p_new_password,gen_salt('bf')),p_role) returning * into v_new;
  return v_new;
exception when unique_violation then raise exception 'Usuário já existe';
end; $$;

grant execute on function public.staff_add_user(text,text,text,text,text,text) to anon, authenticated;

create or replace function public.staff_list_users(p_username text,p_password text)
returns table(id bigint,name text,username text,role text,active boolean,created_at timestamptz)
language plpgsql security definer set search_path=public as $$
declare v_role text; begin
  select role into v_role from public.verify_staff(p_username,p_password) limit 1;
  if v_role is null or v_role not in ('admin','gerente') then raise exception 'Sem permissão'; end if;
  return query select s.id,s.name,s.username,s.role,s.active,s.created_at from public.staff_users s order by s.created_at;
end; $$;

grant execute on function public.staff_list_users(text,text) to anon, authenticated;

create or replace function public.staff_delete_user(p_username text,p_password text,p_user_id bigint)
returns boolean language plpgsql security definer set search_path=public as $$
declare v_role text; begin
  select role into v_role from public.verify_staff(p_username,p_password) limit 1;
  if v_role is null or v_role not in ('admin','gerente') then raise exception 'Sem permissão'; end if;
  update public.staff_users set active=false where id=p_user_id;
  return true;
end; $$;

grant execute on function public.staff_delete_user(text,text,bigint) to anon, authenticated;

-- Dados iniciais: evento HYPE e três lotes.
insert into public.events(name,event_date,venue,pix_key,active)
select 'BOATE HYPE', current_date, 'Carazinho/RS', '', true
where not exists (select 1 from public.events);

insert into public.ticket_lots(event_id,name,sector,price,quantity_total,sort_order)
select e.id, x.name,x.sector,x.price,x.qty,x.ord
from public.events e
cross join (values
  ('Pista - 1º Lote','Pista',30.00,100,1),
  ('Área VIP - 1º Lote','VIP',60.00,100,2),
  ('Camarote Open Bar','Camarote',120.00,50,3)
) x(name,sector,price,qty,ord)
where e.active=true
  and not exists (select 1 from public.ticket_lots);

-- Usuário inicial. TROQUE a senha depois de entrar.
insert into public.staff_users(name,username,password_hash,role)
select 'Administrador HYPE','admin',crypt('Hype@2026',gen_salt('bf')),'admin'
where not exists (select 1 from public.staff_users where username='admin');

insert into public.staff_users(name,username,password_hash,role)
select 'Portaria HYPE','portaria',crypt('portaria2026',gen_salt('bf')),'portaria'
where not exists (select 1 from public.staff_users where username='portaria');

-- Sequências são gerenciadas pelo identity do Postgres.

create or replace function public.staff_cancel_all(p_username text,p_password text)
returns integer language plpgsql security definer set search_path=public as $$
declare v_role text; v_count integer;
begin
  select role into v_role from public.verify_staff(p_username,p_password) limit 1;
  if v_role is null or v_role not in ('admin','gerente') then raise exception 'Sem permissão'; end if;
  update public.tickets set payment_status='Cancelado', canceled_at=coalesce(canceled_at,now()) where payment_status<>'Cancelado';
  get diagnostics v_count = row_count;
  return v_count;
end; $$;
grant execute on function public.staff_cancel_all(text,text) to anon, authenticated;
