-- =============================================================
-- HYPE V16.8 - PROMOTER GLOBAL
-- Um unico promoter/link funciona em TODOS os eventos atuais e futuros.
-- Execute UMA VEZ no Supabase > SQL Editor > New query > Run.
-- NAO apaga ingressos, pagamentos, eventos, lotes ou historico de vendas.
-- =============================================================

create extension if not exists pgcrypto;

alter table public.tickets
  add column if not exists service_fee numeric(12,2) not null default 0;

-- 1) Cadastro global de promoters, sem vinculo obrigatorio com evento.
create table if not exists public.promoters_global_v16 (
  id bigint generated by default as identity primary key,
  name text not null,
  code text not null unique,
  active boolean not null default true,
  created_at timestamptz not null default now()
);

create index if not exists idx_promoters_global_v16_active
  on public.promoters_global_v16(active, created_at desc);

-- Migra os promoters ja existentes. Se o mesmo codigo existir em mais de
-- um evento, vira um unico promoter global.
insert into public.promoters_global_v16(name, code, active)
select
  min(trim(p.name)) as name,
  upper(trim(p.code)) as code,
  bool_or(p.active) as active
from public.promoters_v16 p
where coalesce(trim(p.code),'') <> ''
group by upper(trim(p.code))
on conflict (code) do nothing;

revoke all on public.promoters_global_v16 from anon, authenticated;

-- 2) Lista global + ranking calculado por TODAS as vendas.
drop function if exists public.staff_list_promoters_global_v16(text,text);
create function public.staff_list_promoters_global_v16(
  p_username text,
  p_password text
)
returns table(
  id bigint,
  name text,
  code text,
  active boolean,
  sales_count bigint,
  paid_count bigint,
  revenue numeric
)
language plpgsql
security definer
set search_path=public,extensions
as $$
declare v_staff public.staff_users%rowtype;
begin
  select s.* into v_staff
  from public.staff_users s
  where s.username=trim(p_username)
    and s.active=true
    and s.password_hash=crypt(p_password,s.password_hash)
  limit 1;

  if not found or v_staff.role<>'admin' then raise exception 'Sem permissao'; end if;

  return query
  select
    p.id,p.name,p.code,p.active,
    count(t.id) filter(where t.payment_status in ('Pendente','Pago'))::bigint,
    count(t.id) filter(where t.payment_status='Pago')::bigint,
    coalesce(sum(t.price) filter(where t.payment_status='Pago'),0)::numeric
  from public.promoters_global_v16 p
  left join public.tickets t
    on upper(coalesce(t.promoter_code,''))=upper(p.code)
  group by p.id
  order by 6 desc, 5 desc, p.created_at desc;
end;
$$;

grant execute on function public.staff_list_promoters_global_v16(text,text)
to anon, authenticated;

-- 3) Criar/editar/desativar promoter global.
drop function if exists public.staff_upsert_promoter_global_v16(text,text,bigint,text,text,boolean);
create function public.staff_upsert_promoter_global_v16(
  p_username text,
  p_password text,
  p_id bigint,
  p_name text,
  p_code text,
  p_active boolean
)
returns public.promoters_global_v16
language plpgsql
security definer
set search_path=public,extensions
as $$
declare
  v_staff public.staff_users%rowtype;
  v_row public.promoters_global_v16%rowtype;
  v_code text:=upper(trim(p_code));
begin
  select s.* into v_staff
  from public.staff_users s
  where s.username=trim(p_username)
    and s.active=true
    and s.password_hash=crypt(p_password,s.password_hash)
  limit 1;

  if not found or v_staff.role<>'admin' then raise exception 'Sem permissao'; end if;
  if coalesce(trim(p_name),'')='' or v_code='' then raise exception 'Informe nome e codigo do promoter'; end if;

  if coalesce(p_id,0)=0 then
    insert into public.promoters_global_v16(name,code,active)
    values(trim(p_name),v_code,coalesce(p_active,true))
    returning * into v_row;
  else
    update public.promoters_global_v16 p
    set name=trim(p_name), code=v_code, active=coalesce(p_active,true)
    where p.id=p_id
    returning * into v_row;
    if not found then raise exception 'Promoter nao encontrado'; end if;
  end if;

  return v_row;
exception when unique_violation then
  raise exception 'Este codigo de promoter ja existe';
end;
$$;

grant execute on function public.staff_upsert_promoter_global_v16(text,text,bigint,text,text,boolean)
to anon, authenticated;

-- 4) Excluir promoter global. Vendas antigas continuam com promoter_code.
drop function if exists public.staff_delete_promoter_global_v16(text,text,bigint);
create function public.staff_delete_promoter_global_v16(
  p_username text,
  p_password text,
  p_id bigint
)
returns boolean
language plpgsql
security definer
set search_path=public,extensions
as $$
declare v_staff public.staff_users%rowtype;
begin
  select s.* into v_staff
  from public.staff_users s
  where s.username=trim(p_username)
    and s.active=true
    and s.password_hash=crypt(p_password,s.password_hash)
  limit 1;

  if not found or v_staff.role<>'admin' then raise exception 'Sem permissao'; end if;

  delete from public.promoters_global_v16 p where p.id=p_id;
  if not found then raise exception 'Promoter nao encontrado'; end if;
  return true;
end;
$$;

grant execute on function public.staff_delete_promoter_global_v16(text,text,bigint)
to anon, authenticated;

-- 5) Pedido V16 atualizado: o promoter agora e validado GLOBALMENTE.
-- Mantem cupom por evento, lotes automaticos e taxa de servico R$ 1,98.
drop function if exists public.create_manual_order_v12(text,text,text,bigint,text,text);
drop function if exists public.create_manual_order_v16(text,text,text,text,text,bigint,text,text);

create function public.create_manual_order_v16(
  p_name text,
  p_phone text,
  p_email text,
  p_cpf text,
  p_gender text,
  p_lot_id bigint,
  p_coupon_code text default null,
  p_promoter_code text default null
)
returns table(
  id bigint,event_id bigint,ticket_code text,qr_token text,customer_name text,phone text,email text,cpf text,gender text,
  lot_id bigint,lot_name text,sector text,price numeric,original_price numeric,discount_amount numeric,coupon_code text,promoter_code text,
  payment_status text,entry_status text,purchased_at timestamptz
)
language plpgsql
security definer
set search_path = public, extensions
as $$
declare
  v_lot public.ticket_lots%rowtype;
  v_event public.events%rowtype;
  v_coupon public.coupons_v16%rowtype;
  v_promoter public.promoters_global_v16%rowtype;
  v_used integer;
  v_previous_open integer := 0;
  v_original numeric(12,2);
  v_discount numeric(12,2) := 0;
  v_ticket_value numeric(12,2);
  v_service_fee numeric(12,2) := 1.98;
  v_final numeric(12,2);
  v_coupon_used bigint := 0;
  v_coupon_code text := upper(trim(coalesce(p_coupon_code,'')));
  v_promoter_code text := upper(trim(coalesce(p_promoter_code,'')));
  v_id bigint;
  v_code text;
  v_qr text;
  v_purchased timestamptz;
begin
  if coalesce(trim(p_name),'')='' then raise exception 'Nome do cliente e obrigatorio'; end if;
  if coalesce(trim(p_email),'')='' or position('@' in p_email)=0 then raise exception 'E-mail invalido'; end if;
  if p_gender not in ('Feminino','Masculino') then raise exception 'Selecione Feminino ou Masculino'; end if;

  select l.* into v_lot
  from public.ticket_lots l
  where l.id=p_lot_id
  for update;

  if not found or not v_lot.active then raise exception 'Categoria indisponivel'; end if;

  select e.* into v_event
  from public.events e
  where e.id=v_lot.event_id;

  if not found or not v_event.active then raise exception 'Evento indisponivel'; end if;
  if v_lot.starts_at is not null and now()<v_lot.starts_at then raise exception 'As vendas desta categoria ainda nao comecaram'; end if;
  if v_lot.ends_at is not null and now()>=v_lot.ends_at then raise exception 'As vendas desta categoria ja encerraram'; end if;

  if coalesce(v_lot.auto_sequence,false) then
    select count(*)::integer into v_previous_open
    from public.ticket_lots p
    where p.event_id=v_lot.event_id
      and lower(coalesce(p.sector,''))=lower(coalesce(v_lot.sector,''))
      and p.active=true
      and (p.sort_order<v_lot.sort_order or (p.sort_order=v_lot.sort_order and p.id<v_lot.id))
      and (
        p.quantity_total=0
        or (
          select count(*) from public.tickets tp
          where tp.lot_id=p.id and tp.payment_status in ('Pendente','Pago')
        ) < p.quantity_total
      );
    if v_previous_open>0 then raise exception 'Este lote sera liberado automaticamente quando o anterior esgotar'; end if;
  end if;

  select count(*)::integer into v_used
  from public.tickets t
  where t.lot_id=v_lot.id and t.payment_status in ('Pendente','Pago');

  if v_lot.quantity_total>0 and v_used>=v_lot.quantity_total then raise exception 'Categoria esgotada'; end if;

  v_original := case
    when p_gender='Masculino' then coalesce(v_lot.price_male,v_lot.price,0)
    else coalesce(v_lot.price_female,v_lot.price,0)
  end;

  if v_coupon_code<>'' then
    select c.* into v_coupon
    from public.coupons_v16 c
    where c.event_id=v_lot.event_id
      and upper(c.code)=v_coupon_code
      and c.active=true
    for update;

    if not found then raise exception 'Cupom invalido'; end if;
    if v_coupon.starts_at is not null and now()<v_coupon.starts_at then raise exception 'Cupom ainda nao iniciou'; end if;
    if v_coupon.ends_at is not null and now()>=v_coupon.ends_at then raise exception 'Cupom expirado'; end if;

    select count(*)::bigint into v_coupon_used
    from public.tickets t
    where t.event_id=v_lot.event_id
      and upper(coalesce(t.coupon_code,''))=v_coupon_code
      and t.payment_status in ('Pendente','Pago');

    if v_coupon.usage_limit>0 and v_coupon_used>=v_coupon.usage_limit then raise exception 'Limite do cupom atingido'; end if;

    if v_coupon.discount_type='percent' then
      v_discount := round(v_original*least(v_coupon.discount_value,100)/100,2);
    else
      v_discount := least(v_original,v_coupon.discount_value);
    end if;
  end if;

  -- V16.8: valida o promoter na lista GLOBAL, sem comparar event_id.
  if v_promoter_code<>'' then
    select p.* into v_promoter
    from public.promoters_global_v16 p
    where upper(p.code)=v_promoter_code
      and p.active=true
    limit 1;
    if not found then raise exception 'Codigo de promoter invalido'; end if;
  end if;

  v_ticket_value := greatest(v_original-v_discount,0);
  if v_ticket_value<=0 then raise exception 'O desconto precisa deixar um valor maior que zero para pagamento PIX'; end if;
  v_final := round(v_ticket_value + v_service_fee, 2);

  loop
    v_code := 'HYPE-'||upper(substr(md5(random()::text||clock_timestamp()::text),1,10));
    exit when not exists(select 1 from public.tickets t where t.ticket_code=v_code);
  end loop;

  v_qr := gen_random_uuid()::text;

  insert into public.tickets(
    event_id,lot_id,customer_name,phone,email,cpf,gender,
    price,original_price,discount_amount,service_fee,
    coupon_code,promoter_code,ticket_code,qr_token,payment_status,entry_status
  ) values(
    v_lot.event_id,v_lot.id,trim(p_name),trim(p_phone),lower(trim(p_email)),trim(p_cpf),p_gender,
    v_final,v_original,v_discount,v_service_fee,
    nullif(v_coupon_code,''),nullif(v_promoter_code,''),v_code,v_qr,'Pendente','Não utilizado'
  )
  returning tickets.id,tickets.purchased_at into v_id,v_purchased;

  return query select
    v_id,v_lot.event_id,v_code,v_qr,trim(p_name),trim(p_phone),lower(trim(p_email)),trim(p_cpf),p_gender,
    v_lot.id,v_lot.name,v_lot.sector,v_final,v_original,v_discount,
    nullif(v_coupon_code,''),nullif(v_promoter_code,''),
    'Pendente'::text,'Não utilizado'::text,v_purchased;
end;
$$;

grant execute on function public.create_manual_order_v16(text,text,text,text,text,bigint,text,text)
to anon, authenticated;

-- Compatibilidade com navegador antigo em cache.
create function public.create_manual_order_v12(
  p_cpf text,
  p_email text,
  p_gender text,
  p_lot_id bigint,
  p_name text,
  p_phone text
)
returns table(
  id bigint,event_id bigint,ticket_code text,qr_token text,customer_name text,phone text,email text,cpf text,gender text,
  lot_id bigint,lot_name text,sector text,price numeric,original_price numeric,discount_amount numeric,coupon_code text,promoter_code text,
  payment_status text,entry_status text,purchased_at timestamptz
)
language sql
security definer
set search_path = public, extensions
as $$
  select * from public.create_manual_order_v16(
    p_name,p_phone,p_email,p_cpf,p_gender,p_lot_id,null,null
  );
$$;

grant execute on function public.create_manual_order_v12(text,text,text,bigint,text,text)
to anon, authenticated;
