-- ============================================================
-- HYPE V41 — CHAT ÚNICO DA EQUIPE SEM SENHA DO ADMIN
-- - Conversa única Admin <-> Portaria, sem separar por evento
-- - Não apaga mensagens antigas do V38
-- - Chat funciona mesmo antes de logar no Admin
-- ATENÇÃO: por ser sem senha, qualquer pessoa que abrir a tela do Admin/Portaria
-- poderá mandar mensagem no chat. Use apenas se o link dessas telas for restrito.
-- ============================================================

create table if not exists public.internal_chat_v41 (
  id bigint generated by default as identity primary key,
  sender_role text not null check (sender_role in ('admin','portaria')),
  sender_name text not null,
  message_text text not null,
  created_at timestamptz not null default now()
);

create index if not exists idx_internal_chat_v41_id
  on public.internal_chat_v41(id);

revoke all on public.internal_chat_v41 from anon, authenticated;

create or replace function public.hype_chat_send_v41(
  p_sender_role text,
  p_sender_name text,
  p_message text
)
returns bigint
language plpgsql
security definer
set search_path=public,extensions
as $$
declare
  v_role text := lower(trim(coalesce(p_sender_role,'')));
  v_name text := trim(coalesce(p_sender_name,''));
  v_msg text := trim(coalesce(p_message,''));
  v_id bigint;
begin
  if v_role not in ('admin','portaria') then
    raise exception 'Origem do chat invalida';
  end if;

  if v_name = '' then
    v_name := case when v_role='admin' then 'Admin' else 'Portaria' end;
  end if;

  if v_msg = '' then
    raise exception 'Digite uma mensagem';
  end if;

  if length(v_msg) > 1200 then
    raise exception 'Mensagem muito longa';
  end if;

  insert into public.internal_chat_v41(sender_role, sender_name, message_text)
  values(v_role, v_name, v_msg)
  returning id into v_id;

  return v_id;
end;
$$;

grant execute on function public.hype_chat_send_v41(text,text,text)
to anon, authenticated;

create or replace function public.hype_chat_list_v41(
  p_after_id bigint default 0
)
returns table(
  message_id bigint,
  sender_role text,
  sender_name text,
  message_text text,
  created_at timestamptz
)
language plpgsql
security definer
set search_path=public,extensions
as $$
begin
  if coalesce(p_after_id,0) > 0 then
    return query
    select c.id, c.sender_role, c.sender_name, c.message_text, c.created_at
    from public.internal_chat_v41 c
    where c.id > p_after_id
    order by c.id asc
    limit 120;
  else
    return query
    select x.id, x.sender_role, x.sender_name, x.message_text, x.created_at
    from (
      select c.*
      from public.internal_chat_v41 c
      order by c.id desc
      limit 120
    ) x
    order by x.id asc;
  end if;
end;
$$;

grant execute on function public.hype_chat_list_v41(bigint)
to anon, authenticated;

select 'HYPE V41 OK - chat unico sem senha do Admin' as status;
