-- ============================================================
-- HYPE LOUNGE CLUB // V24 - SORTEIOS MULTIPLOS + PARTICIPANTES MANUAIS
-- Execute UMA VEZ no SQL Editor do Supabase.
--
-- O que muda:
-- 1) O mesmo participante continua elegivel nos proximos sorteios da noite.
-- 2) Admin pode adicionar nomes manualmente e definir quantas chances cada um tera.
-- 3) Historico registra cada sorteio, inclusive vencedores manuais.
-- 4) Ingressos PAGOS continuam entrando automaticamente.
-- ============================================================

create extension if not exists pgcrypto;

do $$
begin
  if to_regclass('public.raffle_draws_v18') is null then
    raise exception 'Tabela raffle_draws_v18 nao encontrada. Execute primeiro a atualizacao V18/V19 do sistema HYPE.';
  end if;
end $$;

-- ------------------------------------------------------------
-- PARTICIPANTES MANUAIS
-- ------------------------------------------------------------
create table if not exists public.raffle_manual_participants_v24 (
  id bigint generated by default as identity primary key,
  event_id bigint not null references public.events(id) on delete cascade,
  customer_name text not null,
  phone text,
  chances integer not null default 1 check (chances between 1 and 100),
  active boolean not null default true,
  created_by text not null,
  created_at timestamptz not null default now()
);

create index if not exists idx_raffle_manual_v24_event_active
  on public.raffle_manual_participants_v24(event_id, active, created_at desc);

alter table public.raffle_manual_participants_v24 enable row level security;
revoke all on public.raffle_manual_participants_v24 from anon, authenticated;

-- ------------------------------------------------------------
-- HISTORICO: permite vencedor vindo de ingresso OU cadastro manual
-- ------------------------------------------------------------
alter table public.raffle_draws_v18
  alter column winner_ticket_id drop not null;

alter table public.raffle_draws_v18
  add column if not exists winner_manual_id bigint references public.raffle_manual_participants_v24(id) on delete set null,
  add column if not exists winner_name text,
  add column if not exists winner_code text,
  add column if not exists winner_phone text,
  add column if not exists winner_promoter_code text,
  add column if not exists winner_source text not null default 'ticket';

-- Preenche snapshots dos sorteios antigos para preservar o historico.
update public.raffle_draws_v18 d
set
  winner_name = coalesce(d.winner_name, t.customer_name),
  winner_code = coalesce(d.winner_code, t.ticket_code),
  winner_phone = coalesce(d.winner_phone, t.phone),
  winner_promoter_code = coalesce(d.winner_promoter_code, t.promoter_code),
  winner_source = coalesce(nullif(d.winner_source,''), 'ticket')
from public.tickets t
where d.winner_ticket_id = t.id
  and (
    d.winner_name is null
    or d.winner_code is null
    or d.winner_source is null
    or d.winner_source = ''
  );

-- ------------------------------------------------------------
-- STATUS DO SORTEIO
-- participant_count = total de CHANCES:
-- 1 por ingresso pago + chances configuradas manualmente.
-- ------------------------------------------------------------
create or replace function public.staff_raffle_status_v24(
  p_username text,
  p_password text,
  p_event_id bigint
)
returns table(
  event_id bigint,
  event_name text,
  enabled boolean,
  prize text,
  participant_count bigint,
  last_winner_name text,
  last_winner_code text,
  last_draw_at timestamptz
)
language plpgsql
security definer
set search_path=public,extensions
as $$
declare
  s public.staff_users%rowtype;
begin
  select u.* into s
  from public.staff_users u
  where u.username=trim(p_username)
    and u.active=true
    and u.password_hash=crypt(p_password,u.password_hash)
  limit 1;

  if not found or s.role<>'admin' then
    raise exception 'Sem permissao';
  end if;

  return query
  select
    e.id,
    e.name,
    coalesce(e.raffle_enabled,false),
    coalesce(e.raffle_prize,''),
    (
      (select count(*)::bigint
       from public.tickets t
       where t.event_id=e.id
         and t.payment_status='Pago')
      +
      (select coalesce(sum(m.chances),0)::bigint
       from public.raffle_manual_participants_v24 m
       where m.event_id=e.id
         and m.active=true)
    )::bigint,
    last_draw.customer_name,
    last_draw.ticket_code,
    last_draw.drawn_at
  from public.events e
  left join lateral (
    select
      coalesce(d.winner_name, t.customer_name, 'Participante')::text as customer_name,
      coalesce(d.winner_code, t.ticket_code, 'MANUAL')::text as ticket_code,
      d.drawn_at
    from public.raffle_draws_v18 d
    left join public.tickets t on t.id=d.winner_ticket_id
    where d.event_id=e.id
    order by d.drawn_at desc,d.id desc
    limit 1
  ) last_draw on true
  where e.id=p_event_id;
end;
$$;

grant execute on function public.staff_raffle_status_v24(text,text,bigint)
to anon, authenticated;

-- ------------------------------------------------------------
-- LISTA UNIFICADA: ingressos pagos + nomes manuais
-- Uma linha por ingresso/pessoa. O campo chances informa o peso.
-- ------------------------------------------------------------
create or replace function public.staff_raffle_participants_v24(
  p_username text,
  p_password text,
  p_event_id bigint
)
returns table(
  participant_key text,
  ticket_id bigint,
  manual_id bigint,
  customer_name text,
  ticket_code text,
  phone text,
  cpf text,
  promoter_code text,
  source text,
  chances integer,
  created_at timestamptz
)
language plpgsql
security definer
set search_path=public,extensions
as $$
declare
  s public.staff_users%rowtype;
begin
  select u.* into s
  from public.staff_users u
  where u.username=trim(p_username)
    and u.active=true
    and u.password_hash=crypt(p_password,u.password_hash)
  limit 1;

  if not found or s.role<>'admin' then
    raise exception 'Sem permissao';
  end if;

  return query
  select *
  from (
    select
      ('T:'||t.id::text)::text as participant_key,
      t.id::bigint as ticket_id,
      null::bigint as manual_id,
      t.customer_name::text,
      t.ticket_code::text,
      t.phone::text,
      t.cpf::text,
      t.promoter_code::text,
      'ticket'::text as source,
      1::integer as chances,
      coalesce(t.paid_at,t.purchased_at)::timestamptz as created_at
    from public.tickets t
    where t.event_id=p_event_id
      and t.payment_status='Pago'

    union all

    select
      ('M:'||m.id::text)::text as participant_key,
      null::bigint as ticket_id,
      m.id::bigint as manual_id,
      m.customer_name::text,
      ('MANUAL-'||m.id::text)::text as ticket_code,
      m.phone::text,
      null::text as cpf,
      null::text as promoter_code,
      'manual'::text as source,
      m.chances::integer,
      m.created_at::timestamptz
    from public.raffle_manual_participants_v24 m
    where m.event_id=p_event_id
      and m.active=true
  ) x
  order by x.created_at desc nulls last, x.participant_key desc;
end;
$$;

grant execute on function public.staff_raffle_participants_v24(text,text,bigint)
to anon, authenticated;

-- ------------------------------------------------------------
-- ADICIONAR / LISTAR / REMOVER PARTICIPANTE MANUAL
-- ------------------------------------------------------------
create or replace function public.staff_add_raffle_manual_v24(
  p_username text,
  p_password text,
  p_event_id bigint,
  p_name text,
  p_chances integer default 1
)
returns table(
  id bigint,
  customer_name text,
  chances integer,
  created_at timestamptz
)
language plpgsql
security definer
set search_path=public,extensions
as $$
declare
  s public.staff_users%rowtype;
  m public.raffle_manual_participants_v24%rowtype;
begin
  select u.* into s
  from public.staff_users u
  where u.username=trim(p_username)
    and u.active=true
    and u.password_hash=crypt(p_password,u.password_hash)
  limit 1;

  if not found or s.role<>'admin' then
    raise exception 'Sem permissao';
  end if;

  if not exists(select 1 from public.events e where e.id=p_event_id) then
    raise exception 'Evento nao encontrado';
  end if;

  if coalesce(length(trim(p_name)),0)<2 then
    raise exception 'Informe o nome da pessoa';
  end if;

  if coalesce(p_chances,0)<1 or p_chances>100 then
    raise exception 'Chances devem ficar entre 1 e 100';
  end if;

  insert into public.raffle_manual_participants_v24(
    event_id,customer_name,chances,active,created_by
  ) values(
    p_event_id,left(trim(p_name),120),p_chances,true,s.username
  )
  returning * into m;

  return query
  select m.id,m.customer_name,m.chances,m.created_at;
end;
$$;

grant execute on function public.staff_add_raffle_manual_v24(text,text,bigint,text,integer)
to anon, authenticated;

create or replace function public.staff_list_raffle_manual_v24(
  p_username text,
  p_password text,
  p_event_id bigint
)
returns table(
  id bigint,
  customer_name text,
  chances integer,
  created_by text,
  created_at timestamptz
)
language plpgsql
security definer
set search_path=public,extensions
as $$
declare
  s public.staff_users%rowtype;
begin
  select u.* into s
  from public.staff_users u
  where u.username=trim(p_username)
    and u.active=true
    and u.password_hash=crypt(p_password,u.password_hash)
  limit 1;

  if not found or s.role<>'admin' then
    raise exception 'Sem permissao';
  end if;

  return query
  select m.id,m.customer_name,m.chances,m.created_by,m.created_at
  from public.raffle_manual_participants_v24 m
  where m.event_id=p_event_id
    and m.active=true
  order by m.created_at desc,m.id desc;
end;
$$;

grant execute on function public.staff_list_raffle_manual_v24(text,text,bigint)
to anon, authenticated;

create or replace function public.staff_remove_raffle_manual_v24(
  p_username text,
  p_password text,
  p_manual_id bigint
)
returns boolean
language plpgsql
security definer
set search_path=public,extensions
as $$
declare
  s public.staff_users%rowtype;
begin
  select u.* into s
  from public.staff_users u
  where u.username=trim(p_username)
    and u.active=true
    and u.password_hash=crypt(p_password,u.password_hash)
  limit 1;

  if not found or s.role<>'admin' then
    raise exception 'Sem permissao';
  end if;

  update public.raffle_manual_participants_v24 m
  set active=false
  where m.id=p_manual_id
    and m.active=true;

  if not found then
    raise exception 'Participante manual nao encontrado';
  end if;

  return true;
end;
$$;

grant execute on function public.staff_remove_raffle_manual_v24(text,text,bigint)
to anon, authenticated;

-- ------------------------------------------------------------
-- NOVO SORTEIO V24
-- IMPORTANTE: NAO exclui vencedor anterior.
-- Assim a mesma pessoa continua no pool nos sorteios seguintes.
-- ------------------------------------------------------------
create or replace function public.staff_draw_raffle_v24(
  p_username text,
  p_password text,
  p_event_id bigint,
  p_prize text
)
returns table(
  draw_id bigint,
  winner_ticket_id bigint,
  customer_name text,
  ticket_code text,
  phone text,
  cpf text,
  promoter_code text,
  prize text,
  drawn_at timestamptz,
  source text
)
language plpgsql
security definer
set search_path=public,extensions
as $$
declare
  s public.staff_users%rowtype;
  e public.events%rowtype;
  d public.raffle_draws_v18%rowtype;

  v_source text;
  v_ticket_id bigint;
  v_manual_id bigint;
  v_name text;
  v_code text;
  v_phone text;
  v_cpf text;
  v_promoter text;
  v_prize text;
begin
  select u.* into s
  from public.staff_users u
  where u.username=trim(p_username)
    and u.active=true
    and u.password_hash=crypt(p_password,u.password_hash)
  limit 1;

  if not found or s.role<>'admin' then
    raise exception 'Sem permissao';
  end if;

  select ev.* into e
  from public.events ev
  where ev.id=p_event_id
  for update;

  if not found then
    raise exception 'Evento nao encontrado';
  end if;

  if not coalesce(e.raffle_enabled,false) then
    raise exception 'Ative o sorteio antes de sortear';
  end if;

  v_prize:=coalesce(nullif(trim(p_prize),''),nullif(trim(e.raffle_prize),''));
  if coalesce(v_prize,'')='' then
    raise exception 'Informe o premio do sorteio';
  end if;

  -- Cada ingresso pago gera 1 linha/chance.
  -- Cada participante manual gera N linhas conforme "chances".
  select
    pool.source,
    pool.ticket_id,
    pool.manual_id,
    pool.customer_name,
    pool.ticket_code,
    pool.phone,
    pool.cpf,
    pool.promoter_code
  into
    v_source,
    v_ticket_id,
    v_manual_id,
    v_name,
    v_code,
    v_phone,
    v_cpf,
    v_promoter
  from (
    select
      'ticket'::text as source,
      t.id::bigint as ticket_id,
      null::bigint as manual_id,
      t.customer_name::text,
      t.ticket_code::text,
      t.phone::text,
      t.cpf::text,
      t.promoter_code::text,
      1::integer as chance_no
    from public.tickets t
    where t.event_id=p_event_id
      and t.payment_status='Pago'

    union all

    select
      'manual'::text as source,
      null::bigint as ticket_id,
      m.id::bigint as manual_id,
      m.customer_name::text,
      ('MANUAL-'||m.id::text)::text as ticket_code,
      m.phone::text,
      null::text as cpf,
      null::text as promoter_code,
      gs::integer as chance_no
    from public.raffle_manual_participants_v24 m
    cross join lateral generate_series(1,m.chances) gs
    where m.event_id=p_event_id
      and m.active=true
  ) pool
  order by random()
  limit 1;

  if not found then
    raise exception 'Nenhum participante disponivel para o sorteio';
  end if;

  -- Mantem no evento o ultimo premio digitado.
  update public.events ev
  set raffle_prize=v_prize
  where ev.id=p_event_id;

  insert into public.raffle_draws_v18(
    event_id,
    winner_ticket_id,
    winner_manual_id,
    winner_name,
    winner_code,
    winner_phone,
    winner_promoter_code,
    winner_source,
    prize,
    drawn_by
  )
  values(
    p_event_id,
    v_ticket_id,
    v_manual_id,
    v_name,
    v_code,
    v_phone,
    v_promoter,
    v_source,
    v_prize,
    s.username
  )
  returning * into d;

  return query
  select
    d.id,
    v_ticket_id,
    v_name,
    v_code,
    v_phone,
    v_cpf,
    v_promoter,
    d.prize,
    d.drawn_at,
    v_source;
end;
$$;

grant execute on function public.staff_draw_raffle_v24(text,text,bigint,text)
to anon, authenticated;

-- ------------------------------------------------------------
-- HISTORICO DA NOITE
-- ------------------------------------------------------------
create or replace function public.staff_raffle_history_v24(
  p_username text,
  p_password text,
  p_event_id bigint
)
returns table(
  draw_id bigint,
  customer_name text,
  ticket_code text,
  source text,
  prize text,
  drawn_by text,
  drawn_at timestamptz
)
language plpgsql
security definer
set search_path=public,extensions
as $$
declare
  s public.staff_users%rowtype;
begin
  select u.* into s
  from public.staff_users u
  where u.username=trim(p_username)
    and u.active=true
    and u.password_hash=crypt(p_password,u.password_hash)
  limit 1;

  if not found or s.role<>'admin' then
    raise exception 'Sem permissao';
  end if;

  return query
  select
    d.id,
    coalesce(d.winner_name,t.customer_name,'Participante')::text,
    coalesce(d.winner_code,t.ticket_code,'MANUAL')::text,
    coalesce(nullif(d.winner_source,''),'ticket')::text,
    d.prize,
    d.drawn_by,
    d.drawn_at
  from public.raffle_draws_v18 d
  left join public.tickets t on t.id=d.winner_ticket_id
  where d.event_id=p_event_id
  order by d.drawn_at desc,d.id desc
  limit 100;
end;
$$;

grant execute on function public.staff_raffle_history_v24(text,text,bigint)
to anon, authenticated;

-- ============================================================
-- FIM V24
-- ============================================================
