-- =============================================================
-- HYPE V17 - CONTINGENCIA / DOCUMENTO / REENTRADA / AUDITORIA
-- Rode UMA VEZ no Supabase > SQL Editor > New query > Run.
-- Nao apaga eventos, ingressos, lotes, promoters ou pagamentos.
-- =============================================================

create extension if not exists pgcrypto;

alter table public.events
  add column if not exists max_tickets_per_cpf integer not null default 0,
  add column if not exists closed_at timestamptz,
  add column if not exists closed_by text;

alter table public.tickets
  add column if not exists document_checked boolean not null default false,
  add column if not exists document_checked_at timestamptz,
  add column if not exists document_checked_by text,
  add column if not exists temporary_exit boolean not null default false,
  add column if not exists temporary_exit_at timestamptz,
  add column if not exists reentry_authorized boolean not null default false,
  add column if not exists reentry_authorized_at timestamptz,
  add column if not exists reentry_authorized_by text,
  add column if not exists reentry_count integer not null default 0,
  add column if not exists last_entry_device text;

create table if not exists public.hype_action_logs_v17 (
  id bigint generated by default as identity primary key,
  event_id bigint references public.events(id) on delete set null,
  ticket_id bigint references public.tickets(id) on delete set null,
  actor_username text,
  actor_role text,
  action text not null,
  details jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now()
);

create index if not exists idx_hype_logs_event on public.hype_action_logs_v17(event_id, created_at desc);
create index if not exists idx_hype_logs_ticket on public.hype_action_logs_v17(ticket_id, created_at desc);
revoke all on public.hype_action_logs_v17 from anon, authenticated;

create or replace function public.hype_staff_v17(p_username text, p_password text)
returns public.staff_users
language plpgsql security definer set search_path=public,extensions as $$
declare v public.staff_users%rowtype;
begin
  select s.* into v from public.staff_users s
  where s.username=trim(p_username) and s.active=true
    and s.password_hash=crypt(p_password,s.password_hash)
  limit 1;
  if not found then raise exception 'Acesso negado'; end if;
  return v;
end; $$;

revoke all on function public.hype_staff_v17(text,text) from public;

create or replace function public.hype_log_v17(
  p_event_id bigint, p_ticket_id bigint, p_actor text, p_role text,
  p_action text, p_details jsonb default '{}'::jsonb
) returns void
language sql security definer set search_path=public as $$
  insert into public.hype_action_logs_v17(event_id,ticket_id,actor_username,actor_role,action,details)
  values(p_event_id,p_ticket_id,p_actor,p_role,p_action,coalesce(p_details,'{}'::jsonb));
$$;
revoke all on function public.hype_log_v17(bigint,bigint,text,text,text,jsonb) from public;

-- Bloqueio transacional por CPF quando o evento estiver com limite = 1.
create or replace function public.hype_block_duplicate_cpf_v17()
returns trigger
language plpgsql set search_path=public as $$
declare v_limit integer; v_cpf text;
begin
  select coalesce(e.max_tickets_per_cpf,0) into v_limit from public.events e where e.id=new.event_id;
  if v_limit = 1 then
    v_cpf := regexp_replace(coalesce(new.cpf,''),'\D','','g');
    if length(v_cpf) <> 11 then raise exception 'CPF obrigatório para este evento'; end if;
    if exists(
      select 1 from public.tickets t
      where t.event_id=new.event_id
        and regexp_replace(coalesce(t.cpf,''),'\D','','g')=v_cpf
        and t.payment_status in ('Pendente','Pago')
        and (tg_op='INSERT' or t.id<>new.id)
    ) then
      raise exception 'Este CPF já possui ingresso neste evento';
    end if;
  end if;
  return new;
end; $$;

drop trigger if exists trg_hype_duplicate_cpf_v17 on public.tickets;
create trigger trg_hype_duplicate_cpf_v17
before insert or update of cpf,event_id,payment_status on public.tickets
for each row execute function public.hype_block_duplicate_cpf_v17();

create or replace function public.staff_set_event_cpf_limit_v17(
  p_username text,p_password text,p_event_id bigint,p_limit_one boolean
) returns boolean
language plpgsql security definer set search_path=public,extensions as $$
declare s public.staff_users%rowtype;
begin
  s:=public.hype_staff_v17(p_username,p_password);
  if s.role not in ('admin','gerente') then raise exception 'Sem permissão'; end if;
  update public.events set max_tickets_per_cpf=case when p_limit_one then 1 else 0 end where id=p_event_id;
  perform public.hype_log_v17(p_event_id,null,s.username,s.role,'EVENT_CPF_LIMIT',jsonb_build_object('limit_one',p_limit_one));
  return true;
end; $$;
grant execute on function public.staff_set_event_cpf_limit_v17(text,text,bigint,boolean) to anon,authenticated;

create or replace function public.staff_mark_document_v17(
  p_username text,p_password text,p_ticket_id bigint,p_checked boolean
) returns boolean
language plpgsql security definer set search_path=public,extensions as $$
declare s public.staff_users%rowtype; t public.tickets%rowtype;
begin
  s:=public.hype_staff_v17(p_username,p_password);
  if s.role not in ('admin','portaria') then raise exception 'Sem permissão'; end if;
  update public.tickets set document_checked=p_checked,
    document_checked_at=case when p_checked then now() else null end,
    document_checked_by=case when p_checked then s.username else null end
  where id=p_ticket_id returning * into t;
  if not found then raise exception 'Ingresso não encontrado'; end if;
  perform public.hype_log_v17(t.event_id,t.id,s.username,s.role,'DOCUMENT_CHECK',jsonb_build_object('checked',p_checked,'cpf',t.cpf));
  return true;
end; $$;
grant execute on function public.staff_mark_document_v17(text,text,bigint,boolean) to anon,authenticated;

create or replace function public.staff_temporary_exit_v17(
  p_username text,p_password text,p_ticket_id bigint
) returns boolean
language plpgsql security definer set search_path=public,extensions as $$
declare s public.staff_users%rowtype; t public.tickets%rowtype;
begin
  s:=public.hype_staff_v17(p_username,p_password);
  if s.role not in ('admin','portaria') then raise exception 'Sem permissão'; end if;
  update public.tickets set temporary_exit=true,temporary_exit_at=now(),reentry_authorized=false,reentry_authorized_at=null,reentry_authorized_by=null
  where id=p_ticket_id and payment_status='Pago' and entry_status='Entrada utilizada'
  returning * into t;
  if not found then raise exception 'Somente quem já entrou pode registrar saída temporária'; end if;
  perform public.hype_log_v17(t.event_id,t.id,s.username,s.role,'TEMPORARY_EXIT','{}'::jsonb);
  return true;
end; $$;
grant execute on function public.staff_temporary_exit_v17(text,text,bigint) to anon,authenticated;

create or replace function public.staff_authorize_reentry_v17(
  p_username text,p_password text,p_ticket_id bigint,p_authorized boolean
) returns boolean
language plpgsql security definer set search_path=public,extensions as $$
declare s public.staff_users%rowtype; t public.tickets%rowtype;
begin
  s:=public.hype_staff_v17(p_username,p_password);
  if s.role not in ('admin','portaria') then raise exception 'Sem permissão'; end if;
  update public.tickets set reentry_authorized=p_authorized,
    reentry_authorized_at=case when p_authorized then now() else null end,
    reentry_authorized_by=case when p_authorized then s.username else null end
  where id=p_ticket_id and temporary_exit=true returning * into t;
  if not found then raise exception 'Saída temporária não registrada'; end if;
  perform public.hype_log_v17(t.event_id,t.id,s.username,s.role,'REENTRY_AUTH',jsonb_build_object('authorized',p_authorized));
  return true;
end; $$;
grant execute on function public.staff_authorize_reentry_v17(text,text,bigint,boolean) to anon,authenticated;

create or replace function public.staff_validate_entry_v17(
  p_username text,p_password text,p_code text,p_device text default null,p_offline_sync boolean default false
) returns table(ok boolean,message text,id bigint,event_id bigint,ticket_code text,customer_name text,cpf text,lot_name text,sector text,
  payment_status text,entry_status text,entry_at timestamptz,document_checked boolean,temporary_exit boolean,reentry_authorized boolean,reentry_count integer)
language plpgsql security definer set search_path=public,extensions as $$
declare s public.staff_users%rowtype; t public.tickets%rowtype; l public.ticket_lots%rowtype; code text:=trim(coalesce(p_code,''));
begin
  s:=public.hype_staff_v17(p_username,p_password);
  if s.role not in ('admin','portaria') then raise exception 'Sem permissão'; end if;
  select * into t from public.tickets x where x.ticket_code=code or x.qr_token=code or ('#'||x.ticket_code)=code limit 1 for update;
  if not found then return query select false,'INGRESSO NÃO ENCONTRADO',null::bigint,null::bigint,null::text,null::text,null::text,null::text,null::text,null::text,null::text,null::timestamptz,false,false,false,0; return; end if;
  select * into l from public.ticket_lots where id=t.lot_id;
  if t.payment_status<>'Pago' then return query select false,'PAGAMENTO NÃO CONFIRMADO',t.id,t.event_id,t.ticket_code,t.customer_name,t.cpf,l.name,l.sector,t.payment_status,t.entry_status,t.entry_at,t.document_checked,t.temporary_exit,t.reentry_authorized,t.reentry_count; return; end if;
  if not t.document_checked then return query select false,'CONFIRA O DOCUMENTO/CPF ANTES DE LIBERAR',t.id,t.event_id,t.ticket_code,t.customer_name,t.cpf,l.name,l.sector,t.payment_status,t.entry_status,t.entry_at,t.document_checked,t.temporary_exit,t.reentry_authorized,t.reentry_count; return; end if;
  if t.entry_status='Entrada utilizada' and not t.temporary_exit then
    return query select false,'INGRESSO JÁ UTILIZADO',t.id,t.event_id,t.ticket_code,t.customer_name,t.cpf,l.name,l.sector,t.payment_status,t.entry_status,t.entry_at,t.document_checked,t.temporary_exit,t.reentry_authorized,t.reentry_count; return;
  end if;
  if t.temporary_exit and not t.reentry_authorized then
    return query select false,'REENTRADA NÃO AUTORIZADA',t.id,t.event_id,t.ticket_code,t.customer_name,t.cpf,l.name,l.sector,t.payment_status,t.entry_status,t.entry_at,t.document_checked,t.temporary_exit,t.reentry_authorized,t.reentry_count; return;
  end if;
  if t.temporary_exit and t.reentry_authorized then
    update public.tickets set temporary_exit=false,reentry_authorized=false,reentry_count=coalesce(reentry_count,0)+1,last_entry_device=p_device where id=t.id returning * into t;
    perform public.hype_log_v17(t.event_id,t.id,s.username,s.role,case when p_offline_sync then 'OFFLINE_REENTRY_SYNC' else 'REENTRY' end,jsonb_build_object('device',p_device));
    return query select true,'REENTRADA LIBERADA',t.id,t.event_id,t.ticket_code,t.customer_name,t.cpf,l.name,l.sector,t.payment_status,t.entry_status,t.entry_at,t.document_checked,t.temporary_exit,t.reentry_authorized,t.reentry_count; return;
  end if;
  update public.tickets set entry_status='Entrada utilizada',entry_at=coalesce(entry_at,now()),last_entry_device=p_device where id=t.id returning * into t;
  perform public.hype_log_v17(t.event_id,t.id,s.username,s.role,case when p_offline_sync then 'OFFLINE_ENTRY_SYNC' else 'ENTRY' end,jsonb_build_object('device',p_device));
  return query select true,'ENTRADA LIBERADA',t.id,t.event_id,t.ticket_code,t.customer_name,t.cpf,l.name,l.sector,t.payment_status,t.entry_status,t.entry_at,t.document_checked,t.temporary_exit,t.reentry_authorized,t.reentry_count;
end; $$;
grant execute on function public.staff_validate_entry_v17(text,text,text,text,boolean) to anon,authenticated;

create or replace function public.staff_offline_snapshot_v17(p_username text,p_password text,p_event_id bigint)
returns table(id bigint,event_id bigint,ticket_code text,qr_token text,customer_name text,cpf text,lot_name text,sector text,payment_status text,entry_status text,entry_at timestamptz,document_checked boolean,temporary_exit boolean,reentry_authorized boolean,reentry_count integer)
language plpgsql security definer set search_path=public,extensions as $$
declare s public.staff_users%rowtype;
begin
  s:=public.hype_staff_v17(p_username,p_password);
  if s.role not in ('admin','portaria') then raise exception 'Sem permissão'; end if;
  return query select t.id,t.event_id,t.ticket_code,t.qr_token,t.customer_name,t.cpf,l.name,l.sector,t.payment_status,t.entry_status,t.entry_at,t.document_checked,t.temporary_exit,t.reentry_authorized,t.reentry_count
  from public.tickets t join public.ticket_lots l on l.id=t.lot_id where t.event_id=p_event_id and t.payment_status='Pago';
end; $$;
grant execute on function public.staff_offline_snapshot_v17(text,text,bigint) to anon,authenticated;

create or replace function public.staff_log_action_v17(p_username text,p_password text,p_ticket_id bigint,p_action text,p_details jsonb default '{}'::jsonb)
returns boolean language plpgsql security definer set search_path=public,extensions as $$
declare s public.staff_users%rowtype; ev bigint;
begin
 s:=public.hype_staff_v17(p_username,p_password);
 select event_id into ev from public.tickets where id=p_ticket_id;
 perform public.hype_log_v17(ev,p_ticket_id,s.username,s.role,p_action,p_details);
 return true;
end; $$;
grant execute on function public.staff_log_action_v17(text,text,bigint,text,jsonb) to anon,authenticated;

create or replace function public.staff_close_event_v17(p_username text,p_password text,p_event_id bigint)
returns boolean language plpgsql security definer set search_path=public,extensions as $$
declare s public.staff_users%rowtype;
begin
 s:=public.hype_staff_v17(p_username,p_password);
 if s.role not in ('admin','gerente') then raise exception 'Sem permissão'; end if;
 update public.events set closed_at=now(),closed_by=s.username,active=false where id=p_event_id;
 perform public.hype_log_v17(p_event_id,null,s.username,s.role,'EVENT_CLOSED','{}'::jsonb);
 return true;
end; $$;
grant execute on function public.staff_close_event_v17(text,text,bigint) to anon,authenticated;

create or replace function public.staff_event_summary_v17(p_username text,p_password text,p_event_id bigint)
returns jsonb language plpgsql security definer set search_path=public,extensions as $$
declare s public.staff_users%rowtype; r jsonb;
begin
 s:=public.hype_staff_v17(p_username,p_password);
 if s.role not in ('admin','gerente','caixa') then raise exception 'Sem permissão'; end if;
 select jsonb_build_object(
   'event_id',e.id,'event_name',e.name,'event_date',e.event_date,'closed_at',e.closed_at,
   'sold',count(t.id) filter(where t.payment_status='Pago'),
   'revenue',coalesce(sum(t.price) filter(where t.payment_status='Pago'),0),
   'entered',count(t.id) filter(where t.payment_status='Pago' and t.entry_status='Entrada utilizada'),
   'not_entered',count(t.id) filter(where t.payment_status='Pago' and t.entry_status<>'Entrada utilizada'),
   'canceled',count(t.id) filter(where t.payment_status='Cancelado'),
   'female',count(t.id) filter(where t.payment_status='Pago' and t.gender='Feminino'),
   'male',count(t.id) filter(where t.payment_status='Pago' and t.gender='Masculino'),
   'reentries',coalesce(sum(t.reentry_count),0),
   'temporary_out',count(t.id) filter(where t.temporary_exit=true)
 ) into r from public.events e left join public.tickets t on t.event_id=e.id where e.id=p_event_id group by e.id;
 return coalesce(r,'{}'::jsonb);
end; $$;
grant execute on function public.staff_event_summary_v17(text,text,bigint) to anon,authenticated;

create or replace function public.staff_action_logs_v17(p_username text,p_password text,p_event_id bigint,p_limit integer default 100)
returns table(id bigint,created_at timestamptz,actor_username text,actor_role text,action text,ticket_id bigint,ticket_code text,customer_name text,details jsonb)
language plpgsql security definer set search_path=public,extensions as $$
declare s public.staff_users%rowtype;
begin
 s:=public.hype_staff_v17(p_username,p_password);
 if s.role not in ('admin','gerente') then raise exception 'Sem permissão'; end if;
 return query select l.id,l.created_at,l.actor_username,l.actor_role,l.action,l.ticket_id,t.ticket_code,t.customer_name,l.details
 from public.hype_action_logs_v17 l left join public.tickets t on t.id=l.ticket_id where l.event_id=p_event_id
 order by l.created_at desc limit greatest(1,least(coalesce(p_limit,100),500));
end; $$;
grant execute on function public.staff_action_logs_v17(text,text,bigint,integer) to anon,authenticated;

-- Leitura pública mínima para o botão "salvar no celular" do próprio ingresso.
-- Usa o RPC public_get_ticket já existente; nenhum dado extra é aberto aqui.
