-- HYPE V60 — saída definitiva + feedback do cliente na hora
-- Aplicado no Supabase de produção em 2026-10-02.
-- O cliente pode deixar comentário BOM e RUIM ao mesmo tempo na saída.
-- O check-in ao vivo passa a contabilizar ENTRY / REENTRY / TEMPORARY_EXIT / EXIT.

alter table public.tickets
  add column if not exists final_exit_at timestamptz,
  add column if not exists final_exit_device uuid references public.portaria_devices_v18(id) on delete set null;

create table if not exists public.portaria_exit_feedback_v60 (
  id bigint generated by default as identity primary key,
  event_id bigint not null references public.events(id) on delete cascade,
  ticket_id bigint not null unique references public.tickets(id) on delete cascade,
  device_id uuid references public.portaria_devices_v18(id) on delete set null,
  good_comment text,
  bad_comment text,
  inside_after bigint not null default 0,
  exit_at timestamptz not null default now(),
  created_at timestamptz not null default now()
);

alter table public.portaria_exit_feedback_v60 enable row level security;
revoke all on public.portaria_exit_feedback_v60 from anon, authenticated;

-- A implementação completa das RPCs V60 está aplicada no Supabase.
-- Principais RPCs:
-- public.portaria_device_final_exit_v60(text,bigint,text,text)
-- public.portaria_device_search_v60(text,bigint,text)
-- public.portaria_device_lookup_event_v60(text,bigint,text)
-- public.portaria_device_snapshot_v60(text,bigint)
-- public.staff_live_checkin_v34(text,text,bigint)
