-- Hype Ingressos: isolated core schema.
-- This migration intentionally creates no events, tickets, or staff credentials.

create extension if not exists pgcrypto with schema extensions;

create schema if not exists private;
revoke all on schema private from public, anon, authenticated;

grant usage on schema public to anon, authenticated, service_role;
alter default privileges in schema public revoke execute on functions from public, anon, authenticated;

create or replace function private.hype_valid_cover_image(p_value text)
returns boolean
language plpgsql
immutable
set search_path = ''
as $$
declare
  v_payload text;
begin
  if coalesce(p_value, '') = '' then
    return true;
  end if;

  if octet_length(p_value) > 4 * 1024 * 1024 then
    return false;
  end if;

  if octet_length(p_value) <= 2048 and p_value ~ '^https://[^[:space:]]+$' then
    return true;
  end if;

  if p_value !~ '^data:image/(jpeg|png|webp);base64,[A-Za-z0-9+/]+={0,2}$' then
    return false;
  end if;

  v_payload := split_part(p_value, ',', 2);
  begin
    perform decode(v_payload, 'base64');
  exception when others then
    return false;
  end;
  return true;
end;
$$;

create table public.events (
  id bigint generated by default as identity primary key,
  name text not null check (length(trim(name)) between 1 and 160),
  artist_name text not null default '',
  event_date date,
  opening_time time,
  closing_time time,
  venue text not null default '',
  description text not null default '',
  cover_image text not null default '',
  theme_color text not null default '' check (theme_color = '' or theme_color ~ '^#[0-9A-F]{6}$'),
  pix_key text not null default '',
  active boolean not null default true,
  sort_order integer not null default 0,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  check (private.hype_valid_cover_image(cover_image))
);

create table public.ticket_lots (
  id bigint generated by default as identity primary key,
  event_id bigint not null references public.events(id) on delete cascade,
  name text not null check (length(trim(name)) between 1 and 120),
  sector text not null default 'Pista' check (length(trim(sector)) between 1 and 120),
  price numeric(12,2) not null default 0 check (price >= 0),
  price_female numeric(12,2) not null default 0 check (price_female >= 0),
  price_male numeric(12,2) not null default 0 check (price_male >= 0),
  quantity_total integer not null default 0 check (quantity_total >= 0),
  starts_at timestamptz,
  ends_at timestamptz,
  active boolean not null default true,
  sort_order integer not null default 0,
  auto_sequence boolean not null default false,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  check (starts_at is null or ends_at is null or ends_at > starts_at),
  check (not auto_sequence or quantity_total > 0)
);

create table public.staff_users (
  id bigint generated by default as identity primary key,
  name text not null check (length(trim(name)) between 2 and 120),
  username text not null unique check (username = lower(trim(username)) and length(username) between 3 and 80),
  password_hash text not null check (password_hash like '$2%'),
  role text not null check (role in ('admin','gerente','caixa','portaria')),
  active boolean not null default true,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table public.tickets (
  id bigint generated by default as identity primary key,
  event_id bigint not null references public.events(id) on delete cascade,
  lot_id bigint not null references public.ticket_lots(id) on delete restrict,
  customer_name text not null check (length(trim(customer_name)) between 2 and 160),
  phone text,
  email text,
  cpf text,
  gender text check (gender is null or gender in ('Feminino','Masculino','Outro','Não informado')),
  price numeric(12,2) not null check (price >= 0),
  original_price numeric(12,2) not null default 0 check (original_price >= 0),
  discount_amount numeric(12,2) not null default 0 check (discount_amount >= 0),
  coupon_code text,
  promoter_code text,
  payment_method text not null default 'Manual',
  ticket_code text not null unique,
  qr_token text not null unique,
  payment_status text not null default 'Pendente' check (payment_status in ('Pendente','Pago','Cancelado','Estornado')),
  entry_status text not null default 'Não utilizado' check (entry_status in ('Não utilizado','Entrada utilizada','Saída temporária','Reentrada autorizada')),
  purchased_at timestamptz not null default now(),
  paid_at timestamptz,
  entry_at timestamptz,
  entry_by bigint references public.staff_users(id) on delete set null,
  entry_device text,
  temporary_exit_at timestamptz,
  reentry_authorized_at timestamptz,
  canceled_at timestamptz,
  refunded_at timestamptz,
  email_sent_at timestamptz,
  asaas_payment_id text unique,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  check (discount_amount <= original_price or original_price = 0)
);

create table public.audit_logs (
  id bigint generated by default as identity primary key,
  staff_user_id bigint references public.staff_users(id) on delete set null,
  action text not null,
  ticket_id bigint references public.tickets(id) on delete set null,
  metadata jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now()
);

create index hype_ticket_lots_event_idx on public.ticket_lots(event_id, active, sort_order, id);
create index hype_tickets_event_created_idx on public.tickets(event_id, created_at desc);
create index hype_tickets_lot_status_idx on public.tickets(lot_id, payment_status);
create index hype_tickets_customer_name_idx on public.tickets(lower(customer_name));
create index hype_tickets_phone_idx on public.tickets(phone);
create index hype_tickets_cpf_idx on public.tickets(cpf);
create index hype_tickets_entry_by_idx on public.tickets(entry_by) where entry_by is not null;
create index hype_audit_logs_ticket_idx on public.audit_logs(ticket_id, created_at desc);
create index hype_audit_logs_staff_idx on public.audit_logs(staff_user_id, created_at desc) where staff_user_id is not null;

alter table public.events enable row level security;
alter table public.ticket_lots enable row level security;
alter table public.staff_users enable row level security;
alter table public.tickets enable row level security;
alter table public.audit_logs enable row level security;

revoke all on all tables in schema public from anon, authenticated;
revoke all on all sequences in schema public from anon, authenticated;

create or replace function private.hype_touch_updated_at()
returns trigger
language plpgsql
set search_path = ''
as $$
begin
  new.updated_at := now();
  return new;
end;
$$;

create trigger hype_events_updated_at
before update on public.events
for each row execute function private.hype_touch_updated_at();

create trigger hype_ticket_lots_updated_at
before update on public.ticket_lots
for each row execute function private.hype_touch_updated_at();

create trigger hype_staff_users_updated_at
before update on public.staff_users
for each row execute function private.hype_touch_updated_at();

create trigger hype_tickets_updated_at
before update on public.tickets
for each row execute function private.hype_touch_updated_at();

create or replace function private.hype_password_hash(p_password text)
returns text
language plpgsql
security definer
set search_path = ''
as $$
begin
  if length(coalesce(p_password, '')) < 12 then
    raise exception 'A senha deve ter pelo menos 12 caracteres';
  end if;
  return extensions.crypt(p_password, extensions.gen_salt('bf', 12));
end;
$$;

create or replace function private.hype_require_staff(
  p_username text,
  p_password text,
  p_roles text[] default null
)
returns public.staff_users
language plpgsql
security definer
set search_path = ''
as $$
declare
  v_staff public.staff_users%rowtype;
begin
  select s.* into v_staff
  from public.staff_users s
  where s.username = lower(trim(p_username))
    and s.active is true
    and s.password_hash = extensions.crypt(p_password, s.password_hash)
  limit 1;

  if not found then
    raise exception 'Acesso negado' using errcode = '28000';
  end if;
  if p_roles is not null and not (v_staff.role = any(p_roles)) then
    raise exception 'Sem permissão' using errcode = '42501';
  end if;
  return v_staff;
end;
$$;

create or replace function private.hype_lot_available_at(
  p_lot public.ticket_lots,
  p_at timestamptz
)
returns boolean
language sql
stable
security definer
set search_path = ''
as $$
  select p_lot.active is true
    and (p_lot.starts_at is null or p_at >= p_lot.starts_at)
    and (p_lot.ends_at is null or p_at < p_lot.ends_at)
    and exists (
      select 1
      from public.events e
      where e.id = p_lot.event_id
        and e.active is true
    );
$$;

create or replace function private.hype_check_ticket_inventory()
returns trigger
language plpgsql
security definer
set search_path = ''
as $$
declare
  v_lot public.ticket_lots%rowtype;
  v_used bigint;
begin
  if new.payment_status not in ('Pendente','Pago') then
    return new;
  end if;

  select l.* into v_lot
  from public.ticket_lots l
  where l.id = new.lot_id
  for update;

  if not found or new.event_id <> v_lot.event_id then
    raise exception 'Lote inválido para este evento';
  end if;
  if v_lot.quantity_total = 0 then
    return new;
  end if;

  select count(*) into v_used
  from public.tickets t
  where t.lot_id = new.lot_id
    and t.payment_status in ('Pendente','Pago')
    and (tg_op = 'INSERT' or t.id <> new.id);

  if v_used >= v_lot.quantity_total then
    raise exception 'Lote esgotado' using errcode = 'P0001';
  end if;
  return new;
end;
$$;

create trigger hype_enforce_ticket_inventory
before insert or update of lot_id, event_id, payment_status on public.tickets
for each row execute function private.hype_check_ticket_inventory();

create or replace function public.verify_staff(p_username text, p_password text)
returns table(id bigint, name text, username text, role text)
language sql
security definer
set search_path = ''
as $$
  select s.id, s.name, s.username, s.role
  from public.staff_users s
  where s.username = lower(trim(p_username))
    and s.active is true
    and s.password_hash = extensions.crypt(p_password, s.password_hash)
  limit 1;
$$;

create or replace function public.public_events_v13()
returns table(
  id bigint,
  name text,
  artist_name text,
  event_date date,
  opening_time time,
  closing_time time,
  venue text,
  description text,
  cover_image text,
  active boolean,
  sort_order integer,
  theme_color text
)
language sql
stable
security definer
set search_path = ''
as $$
  select e.id, e.name, e.artist_name, e.event_date, e.opening_time, e.closing_time,
         e.venue, e.description, e.cover_image, e.active, e.sort_order, e.theme_color
  from public.events e
  where e.active is true
  order by e.sort_order, e.event_date nulls last, e.id;
$$;

create or replace function public.public_events()
returns table(
  id bigint,
  name text,
  artist_name text,
  event_date date,
  opening_time time,
  closing_time time,
  venue text,
  description text,
  cover_image text,
  active boolean,
  sort_order integer,
  theme_color text
)
language sql
stable
security definer
set search_path = ''
as $$
  select * from public.public_events_v13();
$$;

create or replace function public.staff_list_events_v13(p_username text, p_password text)
returns table(
  id bigint,
  name text,
  artist_name text,
  event_date date,
  opening_time time,
  closing_time time,
  venue text,
  description text,
  cover_image text,
  active boolean,
  sort_order integer,
  theme_color text
)
language plpgsql
security definer
set search_path = ''
as $$
begin
  perform private.hype_require_staff(p_username, p_password, array['admin','gerente']);
  return query
  select e.id, e.name, e.artist_name, e.event_date, e.opening_time, e.closing_time,
         e.venue, e.description, e.cover_image, e.active, e.sort_order, e.theme_color
  from public.events e
  order by e.sort_order, e.event_date nulls last, e.id;
end;
$$;

create or replace function public.staff_list_events(p_username text, p_password text)
returns table(
  id bigint,
  name text,
  artist_name text,
  event_date date,
  opening_time time,
  closing_time time,
  venue text,
  description text,
  cover_image text,
  active boolean,
  sort_order integer,
  theme_color text
)
language sql
security definer
set search_path = ''
as $$
  select * from public.staff_list_events_v13(p_username, p_password);
$$;

create or replace function public.staff_save_event_v13(
  p_username text,
  p_password text,
  p_event_id bigint,
  p_name text,
  p_artist_name text,
  p_event_date date,
  p_opening_time time,
  p_closing_time time,
  p_venue text,
  p_description text,
  p_cover_image text,
  p_active boolean,
  p_sort_order integer,
  p_theme_color text
)
returns public.events
language plpgsql
security definer
set search_path = ''
as $$
declare
  v_staff public.staff_users%rowtype;
  v_event public.events%rowtype;
  v_color text := upper(trim(coalesce(p_theme_color, '')));
  v_cover text := coalesce(p_cover_image, '');
begin
  v_staff := private.hype_require_staff(p_username, p_password, array['admin','gerente']);
  if coalesce(trim(p_name), '') = '' then
    raise exception 'Nome do evento é obrigatório';
  end if;
  if v_color <> '' and v_color !~ '^#[0-9A-F]{6}$' then
    raise exception 'Cor do evento inválida. Use #RRGGBB';
  end if;
  if v_cover <> '' and not private.hype_valid_cover_image(v_cover) then
    raise exception 'Imagem inválida, corrompida, incompatível ou maior que 4 MB';
  end if;

  if coalesce(p_event_id, 0) = 0 then
    insert into public.events(
      name, artist_name, event_date, opening_time, closing_time, venue,
      description, cover_image, active, sort_order, theme_color
    ) values (
      trim(p_name), coalesce(trim(p_artist_name), ''), p_event_date,
      p_opening_time, p_closing_time, coalesce(trim(p_venue), ''),
      coalesce(trim(p_description), ''), v_cover, coalesce(p_active, true),
      coalesce(p_sort_order, 0), v_color
    ) returning * into v_event;
  else
    update public.events e
    set name = trim(p_name),
        artist_name = coalesce(trim(p_artist_name), ''),
        event_date = p_event_date,
        opening_time = p_opening_time,
        closing_time = p_closing_time,
        venue = coalesce(trim(p_venue), ''),
        description = coalesce(trim(p_description), ''),
        cover_image = case when v_cover = '' then e.cover_image else v_cover end,
        active = coalesce(p_active, true),
        sort_order = coalesce(p_sort_order, e.sort_order),
        theme_color = v_color
    where e.id = p_event_id
    returning * into v_event;
    if not found then raise exception 'Evento não encontrado'; end if;
  end if;

  insert into public.audit_logs(staff_user_id, action, metadata)
  values (v_staff.id, 'EVENTO_SALVO', jsonb_build_object('event_id', v_event.id));
  return v_event;
end;
$$;

create or replace function public.staff_save_event_v2(
  p_username text,
  p_password text,
  p_event_id bigint,
  p_name text,
  p_artist_name text,
  p_event_date date,
  p_opening_time time,
  p_closing_time time,
  p_venue text,
  p_description text,
  p_cover_image text,
  p_active boolean,
  p_sort_order integer
)
returns public.events
language sql
security definer
set search_path = ''
as $$
  select public.staff_save_event_v13(
    p_username, p_password, p_event_id, p_name, p_artist_name, p_event_date,
    p_opening_time, p_closing_time, p_venue, p_description, p_cover_image,
    p_active, p_sort_order,
    coalesce((select e.theme_color from public.events e where e.id = p_event_id), '')
  );
$$;

create or replace function public.staff_list_lots_v16(
  p_username text,
  p_password text,
  p_event_id bigint
)
returns table(
  id bigint,
  event_id bigint,
  name text,
  sector text,
  price numeric,
  price_female numeric,
  price_male numeric,
  quantity_total integer,
  quantity_sold bigint,
  quantity_available bigint,
  starts_at timestamptz,
  ends_at timestamptz,
  active boolean,
  sort_order integer,
  auto_sequence boolean,
  auto_locked boolean
)
language plpgsql
security definer
set search_path = ''
as $$
begin
  perform private.hype_require_staff(p_username, p_password, array['admin','gerente']);
  return query
  with lot_stats as (
    select l.*,
           count(t.id) filter (where t.payment_status in ('Pendente','Pago'))::bigint as sold
    from public.ticket_lots l
    left join public.tickets t on t.lot_id = l.id
    where l.event_id = p_event_id
    group by l.id
  )
  select l.id, l.event_id, l.name, l.sector, l.price,
         l.price_female, l.price_male, l.quantity_total, l.sold,
         case when l.quantity_total = 0 then null
              else greatest(l.quantity_total - l.sold, 0)::bigint end,
         l.starts_at, l.ends_at, l.active, l.sort_order, l.auto_sequence,
         case when not l.auto_sequence then false else exists (
           select 1 from lot_stats earlier
           where earlier.event_id = l.event_id
             and lower(earlier.sector) = lower(l.sector)
             and earlier.active is true
             and (earlier.sort_order < l.sort_order or (earlier.sort_order = l.sort_order and earlier.id < l.id))
             and (earlier.quantity_total = 0 or earlier.sold < earlier.quantity_total)
         ) end
  from lot_stats l
  order by l.sort_order, l.id;
end;
$$;

create or replace function public.staff_upsert_lot_v16(
  p_username text,
  p_password text,
  p_event_id bigint,
  p_id bigint,
  p_name text,
  p_sector text,
  p_price_female numeric,
  p_price_male numeric,
  p_quantity_total integer,
  p_starts_at timestamptz,
  p_ends_at timestamptz,
  p_active boolean,
  p_sort_order integer,
  p_auto_sequence boolean
)
returns public.ticket_lots
language plpgsql
security definer
set search_path = ''
as $$
declare
  v_lot public.ticket_lots%rowtype;
begin
  perform private.hype_require_staff(p_username, p_password, array['admin','gerente']);
  if not exists (select 1 from public.events e where e.id = p_event_id) then
    raise exception 'Evento não encontrado';
  end if;
  if coalesce(trim(p_name), '') = '' or coalesce(trim(p_sector), '') = '' then
    raise exception 'Informe nome e setor do lote';
  end if;
  if coalesce(p_price_female, 0) < 0 or coalesce(p_price_male, 0) < 0 then
    raise exception 'Preço inválido';
  end if;
  if coalesce(p_quantity_total, 0) < 0 then raise exception 'Quantidade inválida'; end if;
  if coalesce(p_auto_sequence, false) and coalesce(p_quantity_total, 0) = 0 then
    raise exception 'Lote automático precisa ter estoque limitado';
  end if;
  if p_starts_at is not null and p_ends_at is not null and p_ends_at <= p_starts_at then
    raise exception 'O fim das vendas deve ser posterior ao início';
  end if;

  if coalesce(p_id, 0) = 0 then
    insert into public.ticket_lots(
      event_id, name, sector, price, price_female, price_male, quantity_total,
      starts_at, ends_at, active, sort_order, auto_sequence
    ) values (
      p_event_id, trim(p_name), trim(p_sector), coalesce(p_price_female, 0),
      coalesce(p_price_female, 0), coalesce(p_price_male, 0),
      coalesce(p_quantity_total, 0), p_starts_at, p_ends_at,
      coalesce(p_active, true), coalesce(p_sort_order, 0), coalesce(p_auto_sequence, false)
    ) returning * into v_lot;
  else
    update public.ticket_lots l
    set name = trim(p_name), sector = trim(p_sector),
        price = coalesce(p_price_female, 0),
        price_female = coalesce(p_price_female, 0),
        price_male = coalesce(p_price_male, 0),
        quantity_total = coalesce(p_quantity_total, 0),
        starts_at = p_starts_at, ends_at = p_ends_at,
        active = coalesce(p_active, true),
        sort_order = coalesce(p_sort_order, l.sort_order),
        auto_sequence = coalesce(p_auto_sequence, false)
    where l.id = p_id and l.event_id = p_event_id
    returning * into v_lot;
    if not found then raise exception 'Lote não encontrado neste evento'; end if;
  end if;
  return v_lot;
end;
$$;

create or replace function public.public_pix_key()
returns text
language sql
stable
security definer
set search_path = ''
as $$
  select coalesce((
    select e.pix_key from public.events e
    where e.active is true
    order by e.sort_order, e.id
    limit 1
  ), '');
$$;

create or replace function public.staff_save_pix(p_username text, p_password text, p_pix text)
returns boolean
language plpgsql
security definer
set search_path = ''
as $$
declare
  v_staff public.staff_users%rowtype;
begin
  v_staff := private.hype_require_staff(p_username, p_password, array['admin','gerente']);
  update public.events set pix_key = trim(coalesce(p_pix, '')) where active is true;
  insert into public.audit_logs(staff_user_id, action)
  values (v_staff.id, 'PIX_ATUALIZADO');
  return true;
end;
$$;

create or replace function public.public_get_ticket(p_code text)
returns table(
  id bigint,
  event_id bigint,
  event_name text,
  ticket_code text,
  customer_name text,
  phone text,
  email text,
  gender text,
  lot_id bigint,
  lot_name text,
  sector text,
  price numeric,
  payment_status text,
  entry_status text,
  purchased_at timestamptz,
  paid_at timestamptz,
  entry_at timestamptz,
  email_sent_at timestamptz
)
language sql
stable
security definer
set search_path = ''
as $$
  select t.id, t.event_id, e.name, t.ticket_code, t.customer_name, t.phone,
         t.email, t.gender, t.lot_id, l.name, l.sector, t.price,
         t.payment_status, t.entry_status, t.purchased_at, t.paid_at,
         t.entry_at, t.email_sent_at
  from public.tickets t
  join public.ticket_lots l on l.id = t.lot_id
  join public.events e on e.id = t.event_id
  where lower(t.ticket_code) = lower(trim(p_code))
     or lower(t.qr_token) = lower(trim(p_code))
  limit 1;
$$;

create or replace function public.staff_list_tickets_v16(
  p_username text,
  p_password text,
  p_search text default ''
)
returns table(
  id bigint,
  event_id bigint,
  event_name text,
  ticket_code text,
  customer_name text,
  phone text,
  email text,
  cpf text,
  gender text,
  lot_id bigint,
  lot_name text,
  sector text,
  price numeric,
  original_price numeric,
  discount_amount numeric,
  coupon_code text,
  promoter_code text,
  payment_method text,
  payment_status text,
  entry_status text,
  purchased_at timestamptz,
  paid_at timestamptz,
  entry_at timestamptz,
  email_sent_at timestamptz
)
language plpgsql
security definer
set search_path = ''
as $$
begin
  perform private.hype_require_staff(p_username, p_password, array['admin','gerente','caixa']);
  return query
  select t.id, t.event_id, e.name, t.ticket_code, t.customer_name, t.phone,
         t.email, t.cpf, t.gender, t.lot_id, l.name, l.sector, t.price,
         t.original_price, t.discount_amount, t.coupon_code, t.promoter_code,
         t.payment_method, t.payment_status, t.entry_status, t.purchased_at,
         t.paid_at, t.entry_at, t.email_sent_at
  from public.tickets t
  join public.ticket_lots l on l.id = t.lot_id
  join public.events e on e.id = t.event_id
  where coalesce(p_search, '') = ''
     or lower(t.customer_name) like '%' || lower(p_search) || '%'
     or lower(t.ticket_code) like '%' || lower(p_search) || '%'
     or lower(coalesce(t.phone, '')) like '%' || lower(p_search) || '%'
     or lower(coalesce(t.email, '')) like '%' || lower(p_search) || '%'
     or lower(coalesce(t.cpf, '')) like '%' || lower(p_search) || '%'
     or lower(coalesce(t.promoter_code, '')) like '%' || lower(p_search) || '%'
     or lower(coalesce(t.coupon_code, '')) like '%' || lower(p_search) || '%'
     or lower(e.name) like '%' || lower(p_search) || '%'
  order by t.created_at desc;
end;
$$;

create or replace function public.staff_list_tickets_manual(
  p_username text,
  p_password text,
  p_search text default ''
)
returns table(
  id bigint, event_id bigint, event_name text, ticket_code text, customer_name text,
  phone text, email text, cpf text, gender text, lot_id bigint, lot_name text,
  sector text, price numeric, original_price numeric, discount_amount numeric,
  coupon_code text, promoter_code text, payment_method text, payment_status text,
  entry_status text, purchased_at timestamptz, paid_at timestamptz,
  entry_at timestamptz, email_sent_at timestamptz
)
language sql
security definer
set search_path = ''
as $$
  select * from public.staff_list_tickets_v16(p_username, p_password, p_search);
$$;

create or replace function public.staff_list_tickets(
  p_username text,
  p_password text,
  p_search text default ''
)
returns table(
  id bigint, event_id bigint, event_name text, ticket_code text, customer_name text,
  phone text, email text, cpf text, gender text, lot_id bigint, lot_name text,
  sector text, price numeric, original_price numeric, discount_amount numeric,
  coupon_code text, promoter_code text, payment_method text, payment_status text,
  entry_status text, purchased_at timestamptz, paid_at timestamptz,
  entry_at timestamptz, email_sent_at timestamptz
)
language sql
security definer
set search_path = ''
as $$
  select * from public.staff_list_tickets_v16(p_username, p_password, p_search);
$$;

create or replace function public.staff_set_payment(
  p_username text,
  p_password text,
  p_ticket_id bigint,
  p_status text
)
returns public.tickets
language plpgsql
security definer
set search_path = ''
as $$
declare
  v_staff public.staff_users%rowtype;
  v_ticket public.tickets%rowtype;
begin
  v_staff := private.hype_require_staff(p_username, p_password, array['admin','gerente','caixa']);
  if p_status not in ('Pendente','Pago','Cancelado') then raise exception 'Status inválido'; end if;
  update public.tickets t
  set payment_status = p_status,
      paid_at = case when p_status = 'Pago' then coalesce(t.paid_at, now()) else null end,
      canceled_at = case when p_status = 'Cancelado' then coalesce(t.canceled_at, now()) else null end
  where t.id = p_ticket_id
  returning * into v_ticket;
  if not found then raise exception 'Ingresso não encontrado'; end if;
  insert into public.audit_logs(staff_user_id, action, ticket_id, metadata)
  values (v_staff.id, 'PAGAMENTO_ALTERADO', v_ticket.id, jsonb_build_object('status', p_status));
  return v_ticket;
end;
$$;

revoke execute on all functions in schema public from public, anon, authenticated;
revoke execute on all functions in schema private from public, anon, authenticated;

grant execute on function public.verify_staff(text,text) to anon, authenticated;
grant execute on function public.public_events() to anon, authenticated;
grant execute on function public.public_events_v13() to anon, authenticated;
grant execute on function public.public_pix_key() to anon, authenticated;
grant execute on function public.public_get_ticket(text) to anon, authenticated;
grant execute on function public.staff_list_events(text,text) to anon, authenticated;
grant execute on function public.staff_list_events_v13(text,text) to anon, authenticated;
grant execute on function public.staff_save_event_v2(text,text,bigint,text,text,date,time,time,text,text,text,boolean,integer) to anon, authenticated;
grant execute on function public.staff_save_event_v13(text,text,bigint,text,text,date,time,time,text,text,text,boolean,integer,text) to anon, authenticated;
grant execute on function public.staff_list_lots_v16(text,text,bigint) to anon, authenticated;
grant execute on function public.staff_upsert_lot_v16(text,text,bigint,bigint,text,text,numeric,numeric,integer,timestamptz,timestamptz,boolean,integer,boolean) to anon, authenticated;
grant execute on function public.staff_save_pix(text,text,text) to anon, authenticated;
grant execute on function public.staff_list_tickets(text,text,text) to anon, authenticated;
grant execute on function public.staff_list_tickets_manual(text,text,text) to anon, authenticated;
grant execute on function public.staff_list_tickets_v16(text,text,text) to anon, authenticated;
grant execute on function public.staff_set_payment(text,text,bigint,text) to anon, authenticated;

notify pgrst, 'reload schema';
