-- Hype Ingressos: sales, administration, lists, raffles, and surveys.

alter table public.events
  add column raffle_enabled boolean not null default false,
  add column raffle_prize text not null default '',
  add column closed_at timestamptz,
  add column closed_by text,
  add column max_tickets_per_cpf integer not null default 0 check (max_tickets_per_cpf >= 0);

alter table public.tickets
  add column service_fee numeric(12,2) not null default 0 check (service_fee >= 0),
  add column refund_amount numeric(12,2) not null default 0 check (refund_amount >= 0),
  add column refund_status text,
  add column refund_mode text,
  add column free_after_refund boolean not null default false;

create table public.promoters_v16 (
  id bigint generated by default as identity primary key,
  event_id bigint not null references public.events(id) on delete cascade,
  name text not null check (length(trim(name)) between 2 and 120),
  code text not null check (code = upper(trim(code)) and length(code) between 2 and 48),
  active boolean not null default true,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  unique(event_id, code)
);

create table public.promoters_global_v16 (
  id bigint generated by default as identity primary key,
  name text not null check (length(trim(name)) between 2 and 120),
  code text not null unique check (code = upper(trim(code)) and length(code) between 2 and 48),
  active boolean not null default true,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table public.coupons_v16 (
  id bigint generated by default as identity primary key,
  event_id bigint not null references public.events(id) on delete cascade,
  code text not null check (code = upper(trim(code)) and length(code) between 2 and 48),
  discount_type text not null check (discount_type in ('percent','fixed')),
  discount_value numeric(12,2) not null check (discount_value >= 0),
  usage_limit integer not null default 0 check (usage_limit >= 0),
  starts_at timestamptz,
  ends_at timestamptz,
  active boolean not null default true,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  unique(event_id, code),
  check (discount_type <> 'percent' or discount_value <= 100),
  check (starts_at is null or ends_at is null or ends_at > starts_at)
);

create table public.lot_free_rules_v38 (
  lot_id bigint primary key references public.ticket_lots(id) on delete cascade,
  female_free_until timestamptz,
  male_free_until timestamptz,
  updated_at timestamptz not null default now()
);

create table public.guest_list_simple_v406 (
  id bigint generated by default as identity primary key,
  event_id bigint not null references public.events(id) on delete cascade,
  name text not null check (length(trim(name)) between 2 and 160),
  name_key text not null,
  cpf text,
  gender text,
  status text not null default 'Liberado' check (status in ('Liberado','Entrou','Cancelado')),
  added_by text not null default '',
  created_at timestamptz not null default now(),
  entered_at timestamptz,
  entry_device_id uuid,
  unique(event_id, name_key)
);

create table public.raffle_draws_v18 (
  id bigint generated by default as identity primary key,
  event_id bigint not null references public.events(id) on delete cascade,
  winner_ticket_id bigint references public.tickets(id) on delete set null,
  winner_name text not null default '',
  winner_code text not null default '',
  winner_cpf text,
  winner_phone text,
  winner_promoter_code text,
  winner_source text not null default 'ticket',
  prize text not null,
  drawn_by text not null,
  drawn_at timestamptz not null default now(),
  unique(event_id, winner_ticket_id)
);

create table public.event_survey_invites_v34 (
  token uuid primary key default extensions.gen_random_uuid(),
  event_id bigint not null references public.events(id) on delete cascade,
  ticket_id bigint not null unique references public.tickets(id) on delete cascade,
  sent_at timestamptz,
  sent_count integer not null default 0,
  email_sent_at timestamptz,
  whatsapp_sent_at timestamptz,
  whatsapp_error text,
  responded_at timestamptz,
  created_at timestamptz not null default now()
);

create table public.event_survey_responses_v34 (
  id bigint generated by default as identity primary key,
  invite_token uuid not null unique references public.event_survey_invites_v34(token) on delete cascade,
  event_id bigint not null references public.events(id) on delete cascade,
  ticket_id bigint not null references public.tickets(id) on delete cascade,
  rating integer not null check (rating between 1 and 5),
  would_return boolean not null,
  comment text not null default '' check (length(comment) <= 1200),
  submitted_at timestamptz not null default now()
);

create index hype_promoters_event_idx on public.promoters_v16(event_id, active);
create index hype_coupons_event_idx on public.coupons_v16(event_id, active);
create index hype_guest_list_event_status_idx on public.guest_list_simple_v406(event_id, status, created_at desc);
create index hype_raffle_event_idx on public.raffle_draws_v18(event_id, drawn_at desc);
create index hype_raffle_winner_ticket_idx on public.raffle_draws_v18(winner_ticket_id);
create index hype_survey_invites_event_idx on public.event_survey_invites_v34(event_id, created_at desc);
create index hype_survey_responses_event_idx on public.event_survey_responses_v34(event_id, submitted_at desc);
create index hype_survey_responses_ticket_idx on public.event_survey_responses_v34(ticket_id);

alter table public.promoters_v16 enable row level security;
alter table public.promoters_global_v16 enable row level security;
alter table public.coupons_v16 enable row level security;
alter table public.lot_free_rules_v38 enable row level security;
alter table public.guest_list_simple_v406 enable row level security;
alter table public.raffle_draws_v18 enable row level security;
alter table public.event_survey_invites_v34 enable row level security;
alter table public.event_survey_responses_v34 enable row level security;

revoke all on all tables in schema public from anon, authenticated;
revoke all on all sequences in schema public from anon, authenticated;

create trigger hype_promoters_v16_updated_at
before update on public.promoters_v16
for each row execute function private.hype_touch_updated_at();

create trigger hype_promoters_global_v16_updated_at
before update on public.promoters_global_v16
for each row execute function private.hype_touch_updated_at();

create trigger hype_coupons_v16_updated_at
before update on public.coupons_v16
for each row execute function private.hype_touch_updated_at();

create or replace function private.hype_name_key(p_name text)
returns text
language sql
immutable
set search_path = ''
as $$
  select regexp_replace(
    translate(lower(trim(coalesce(p_name, ''))),
      'áàâãäéèêëíìîïóòôõöúùûüçñ',
      'aaaaaeeeeiiiiooooouuuucn'),
    '[^a-z0-9]+', '', 'g'
  );
$$;

create or replace function private.hype_effective_price(
  p_lot public.ticket_lots,
  p_gender text,
  p_at timestamptz
)
returns numeric
language plpgsql
stable
security definer
set search_path = ''
as $$
declare
  v_free_until timestamptz;
  v_price numeric(12,2);
begin
  if p_gender not in ('Feminino','Masculino') then
    raise exception 'Selecione Feminino ou Masculino';
  end if;
  v_price := case when p_gender = 'Masculino' then p_lot.price_male else p_lot.price_female end;
  select case when p_gender = 'Masculino' then r.male_free_until else r.female_free_until end
  into v_free_until
  from public.lot_free_rules_v38 r
  where r.lot_id = p_lot.id;
  if v_free_until is not null and p_at < v_free_until then return 0; end if;
  return coalesce(v_price, p_lot.price, 0);
end;
$$;

create or replace function public.staff_add_user(
  p_username text, p_password text, p_name text, p_new_username text,
  p_new_password text, p_role text
)
returns public.staff_users
language plpgsql
security definer
set search_path = ''
as $$
declare v_new public.staff_users%rowtype;
begin
  perform private.hype_require_staff(p_username, p_password, array['admin']);
  if p_role not in ('admin','gerente','caixa','portaria') then raise exception 'Perfil inválido'; end if;
  insert into public.staff_users(name, username, password_hash, role)
  values (trim(p_name), lower(trim(p_new_username)), private.hype_password_hash(p_new_password), p_role)
  returning * into v_new;
  return v_new;
exception when unique_violation then raise exception 'Usuário já existe';
end;
$$;

create or replace function public.staff_list_users(p_username text, p_password text)
returns table(id bigint, name text, username text, role text, active boolean, created_at timestamptz)
language plpgsql
security definer
set search_path = ''
as $$
begin
  perform private.hype_require_staff(p_username, p_password, array['admin']);
  return query select s.id, s.name, s.username, s.role, s.active, s.created_at
  from public.staff_users s order by s.created_at, s.id;
end;
$$;

create or replace function public.staff_delete_user(p_username text, p_password text, p_user_id bigint)
returns boolean
language plpgsql
security definer
set search_path = ''
as $$
declare v_staff public.staff_users%rowtype;
begin
  v_staff := private.hype_require_staff(p_username, p_password, array['admin']);
  if v_staff.id = p_user_id then raise exception 'Você não pode desativar o próprio usuário'; end if;
  update public.staff_users set active = false where id = p_user_id;
  if not found then raise exception 'Usuário não encontrado'; end if;
  return true;
end;
$$;

create or replace function public.staff_upsert_promoter_v16(
  p_username text, p_password text, p_event_id bigint, p_id bigint,
  p_name text, p_code text, p_active boolean
)
returns public.promoters_v16
language plpgsql
security definer
set search_path = ''
as $$
declare v_row public.promoters_v16%rowtype; v_code text := upper(trim(p_code));
begin
  perform private.hype_require_staff(p_username, p_password, array['admin']);
  if coalesce(trim(p_name), '') = '' or v_code = '' then raise exception 'Informe nome e código'; end if;
  if coalesce(p_id, 0) = 0 then
    insert into public.promoters_v16(event_id, name, code, active)
    values (p_event_id, trim(p_name), v_code, coalesce(p_active, true)) returning * into v_row;
  else
    update public.promoters_v16 p set name=trim(p_name), code=v_code, active=coalesce(p_active,true)
    where p.id=p_id and p.event_id=p_event_id returning * into v_row;
    if not found then raise exception 'Promoter não encontrado'; end if;
  end if;
  return v_row;
exception when unique_violation then raise exception 'Código de promoter já existe';
end;
$$;

create or replace function public.staff_list_promoters_v16(p_username text, p_password text, p_event_id bigint)
returns table(id bigint,event_id bigint,name text,code text,active boolean,sales_count bigint,paid_count bigint,revenue numeric)
language plpgsql
security definer
set search_path = ''
as $$
begin
  perform private.hype_require_staff(p_username,p_password,array['admin']);
  return query
  select p.id,p.event_id,p.name,p.code,p.active,count(t.id)::bigint,
    count(t.id) filter(where t.payment_status='Pago')::bigint,
    coalesce(sum(t.price) filter(where t.payment_status='Pago'),0)::numeric
  from public.promoters_v16 p left join public.tickets t
    on t.event_id=p.event_id and upper(t.promoter_code)=p.code
  where p.event_id=p_event_id group by p.id order by p.name;
end;
$$;

create or replace function public.staff_delete_promoter_v16(p_username text,p_password text,p_event_id bigint,p_id bigint)
returns boolean language plpgsql security definer set search_path='' as $$
begin
  perform private.hype_require_staff(p_username,p_password,array['admin']);
  delete from public.promoters_v16 where id=p_id and event_id=p_event_id;
  return found;
end; $$;

create or replace function public.staff_upsert_promoter_global_v16(
  p_username text,p_password text,p_id bigint,p_name text,p_code text,p_active boolean
)
returns public.promoters_global_v16
language plpgsql security definer set search_path='' as $$
declare v_row public.promoters_global_v16%rowtype; v_code text:=upper(trim(p_code));
begin
  perform private.hype_require_staff(p_username,p_password,array['admin']);
  if coalesce(trim(p_name),'')='' or v_code='' then raise exception 'Informe nome e código'; end if;
  if coalesce(p_id,0)=0 then
    insert into public.promoters_global_v16(name,code,active)
    values(trim(p_name),v_code,coalesce(p_active,true)) returning * into v_row;
  else
    update public.promoters_global_v16 p set name=trim(p_name),code=v_code,active=coalesce(p_active,true)
    where p.id=p_id returning * into v_row;
    if not found then raise exception 'Promoter não encontrado'; end if;
  end if;
  return v_row;
exception when unique_violation then raise exception 'Código de promoter já existe';
end; $$;

create or replace function public.staff_list_promoters_global_v16(p_username text,p_password text)
returns table(id bigint,name text,code text,active boolean,sales_count bigint,paid_count bigint,revenue numeric)
language plpgsql security definer set search_path='' as $$
begin
  perform private.hype_require_staff(p_username,p_password,array['admin']);
  return query select p.id,p.name,p.code,p.active,count(t.id)::bigint,
    count(t.id) filter(where t.payment_status='Pago')::bigint,
    coalesce(sum(t.price) filter(where t.payment_status='Pago'),0)::numeric
  from public.promoters_global_v16 p left join public.tickets t on upper(t.promoter_code)=p.code
  group by p.id order by p.name;
end; $$;

create or replace function public.staff_delete_promoter_global_v16(p_username text,p_password text,p_id bigint)
returns boolean language plpgsql security definer set search_path='' as $$
begin
  perform private.hype_require_staff(p_username,p_password,array['admin']);
  delete from public.promoters_global_v16 where id=p_id;
  return found;
end; $$;

create or replace function public.staff_upsert_coupon_v16(
  p_username text,p_password text,p_event_id bigint,p_id bigint,p_code text,
  p_discount_type text,p_discount_value numeric,p_usage_limit integer,
  p_starts_at timestamptz,p_ends_at timestamptz,p_active boolean
)
returns public.coupons_v16
language plpgsql security definer set search_path='' as $$
declare v_row public.coupons_v16%rowtype; v_code text:=upper(trim(p_code));
begin
  perform private.hype_require_staff(p_username,p_password,array['admin']);
  if v_code='' then raise exception 'Informe o código do cupom'; end if;
  if p_discount_type not in('percent','fixed') then raise exception 'Tipo de desconto inválido'; end if;
  if coalesce(p_discount_value,0)<0 or (p_discount_type='percent' and p_discount_value>100) then raise exception 'Desconto inválido'; end if;
  if coalesce(p_usage_limit,0)<0 then raise exception 'Limite inválido'; end if;
  if p_starts_at is not null and p_ends_at is not null and p_ends_at<=p_starts_at then raise exception 'Período inválido'; end if;
  if coalesce(p_id,0)=0 then
    insert into public.coupons_v16(event_id,code,discount_type,discount_value,usage_limit,starts_at,ends_at,active)
    values(p_event_id,v_code,p_discount_type,p_discount_value,coalesce(p_usage_limit,0),p_starts_at,p_ends_at,coalesce(p_active,true)) returning * into v_row;
  else
    update public.coupons_v16 c set code=v_code,discount_type=p_discount_type,discount_value=p_discount_value,
      usage_limit=coalesce(p_usage_limit,0),starts_at=p_starts_at,ends_at=p_ends_at,active=coalesce(p_active,true)
    where c.id=p_id and c.event_id=p_event_id returning * into v_row;
    if not found then raise exception 'Cupom não encontrado'; end if;
  end if;
  return v_row;
exception when unique_violation then raise exception 'Cupom já existe neste evento';
end; $$;

create or replace function public.staff_list_coupons_v16(p_username text,p_password text,p_event_id bigint)
returns table(id bigint,event_id bigint,code text,discount_type text,discount_value numeric,usage_limit integer,usage_count bigint,starts_at timestamptz,ends_at timestamptz,active boolean)
language plpgsql security definer set search_path='' as $$
begin
  perform private.hype_require_staff(p_username,p_password,array['admin']);
  return query select c.id,c.event_id,c.code,c.discount_type,c.discount_value,c.usage_limit,
    count(t.id) filter(where t.payment_status in('Pendente','Pago'))::bigint,
    c.starts_at,c.ends_at,c.active
  from public.coupons_v16 c left join public.tickets t
    on t.event_id=c.event_id and upper(t.coupon_code)=c.code
  where c.event_id=p_event_id group by c.id order by c.created_at desc;
end; $$;

create or replace function public.staff_lot_free_rules_v38(p_username text,p_password text,p_event_id bigint)
returns table(lot_id bigint,female_free_until timestamptz,male_free_until timestamptz)
language plpgsql security definer set search_path='' as $$
begin
  perform private.hype_require_staff(p_username,p_password,array['admin','gerente']);
  return query select r.lot_id,r.female_free_until,r.male_free_until
  from public.lot_free_rules_v38 r join public.ticket_lots l on l.id=r.lot_id
  where l.event_id=p_event_id order by l.sort_order,l.id;
end; $$;

create or replace function public.staff_set_lot_free_until_v38(
  p_username text,p_password text,p_lot_id bigint,
  p_female_free_until timestamptz,p_male_free_until timestamptz
)
returns boolean language plpgsql security definer set search_path='' as $$
begin
  perform private.hype_require_staff(p_username,p_password,array['admin','gerente']);
  if not exists(select 1 from public.ticket_lots where id=p_lot_id) then raise exception 'Categoria não encontrada'; end if;
  if p_female_free_until is null and p_male_free_until is null then
    delete from public.lot_free_rules_v38 where lot_id=p_lot_id;
  else
    insert into public.lot_free_rules_v38(lot_id,female_free_until,male_free_until)
    values(p_lot_id,p_female_free_until,p_male_free_until)
    on conflict(lot_id) do update set female_free_until=excluded.female_free_until,
      male_free_until=excluded.male_free_until,updated_at=now();
  end if;
  return true;
end; $$;

create or replace function private.hype_device_authorized(p_device_key text)
returns boolean
language sql
stable
security definer
set search_path = ''
as $$
  select false;
$$;

create or replace function public.public_lots_by_event_v16(p_event_id bigint)
returns table(
  id bigint, event_id bigint, name text, sector text, price numeric,
  price_female numeric, price_male numeric, quantity_total integer,
  quantity_sold bigint, quantity_available bigint, starts_at timestamptz,
  ends_at timestamptz, active boolean, sort_order integer,
  auto_sequence boolean, auto_locked boolean
)
language sql
stable
security definer
set search_path = ''
as $$
  with lot_stats as (
    select l.*, count(t.id) filter (where t.payment_status in ('Pendente','Pago'))::bigint as sold
    from public.ticket_lots l
    left join public.tickets t on t.lot_id = l.id
    where l.event_id = p_event_id
    group by l.id
  )
  select l.id, l.event_id, l.name, l.sector,
         private.hype_effective_price((select base from public.ticket_lots base where base.id=l.id), 'Feminino', clock_timestamp()),
         private.hype_effective_price((select base from public.ticket_lots base where base.id=l.id), 'Feminino', clock_timestamp()),
         private.hype_effective_price((select base from public.ticket_lots base where base.id=l.id), 'Masculino', clock_timestamp()),
         l.quantity_total, l.sold,
         case when l.quantity_total = 0 then null else greatest(l.quantity_total - l.sold, 0)::bigint end,
         l.starts_at, l.ends_at, l.active, l.sort_order, l.auto_sequence,
         case when not l.auto_sequence then false else exists (
           select 1 from lot_stats earlier
           where earlier.event_id = l.event_id
             and lower(earlier.sector) = lower(l.sector)
             and earlier.active is true
             and (earlier.sort_order < l.sort_order or (earlier.sort_order = l.sort_order and earlier.id < l.id))
             and (earlier.quantity_total = 0 or earlier.sold < earlier.quantity_total)
         ) end
  from lot_stats l
  join public.events e on e.id = l.event_id
  where l.active is true and e.active is true
  order by l.sort_order, l.id;
$$;

create or replace function public.public_lot_free_rules_v38(p_event_id bigint)
returns table(lot_id bigint, female_free_until timestamptz, male_free_until timestamptz)
language sql
stable
security definer
set search_path = ''
as $$
  select r.lot_id, r.female_free_until, r.male_free_until
  from public.lot_free_rules_v38 r
  join public.ticket_lots l on l.id = r.lot_id
  join public.events e on e.id = l.event_id
  where l.event_id = p_event_id and l.active is true and e.active is true;
$$;

create or replace function public.public_quote_v16(
  p_lot_id bigint,
  p_gender text,
  p_coupon_code text default null
)
returns table(ok boolean, message text, original_price numeric, discount_amount numeric, final_price numeric, coupon_code text)
language plpgsql
security definer
set search_path = ''
as $$
declare
  v_lot public.ticket_lots%rowtype;
  c public.coupons_v16%rowtype;
  v_original numeric(12,2);
  v_discount numeric(12,2) := 0;
  v_coupon_used bigint := 0;
  v_code text := upper(trim(coalesce(p_coupon_code, '')));
begin
  select l.* into v_lot from public.ticket_lots l where l.id = p_lot_id;
  if not found or not private.hype_lot_available_at(v_lot, clock_timestamp()) then
    return query select false, 'Categoria indisponível', 0::numeric, 0::numeric, 0::numeric, null::text;
    return;
  end if;
  v_original := private.hype_effective_price(v_lot, p_gender, clock_timestamp());
  if v_original = 0 then
    return query select true, 'FREE até o horário configurado', 0::numeric, 0::numeric, 0::numeric, null::text;
    return;
  end if;
  if v_code = '' then
    return query select true, 'Sem cupom', v_original, 0::numeric, v_original, null::text;
    return;
  end if;

  select x.* into c from public.coupons_v16 x
  where x.event_id = v_lot.event_id and x.code = v_code and x.active is true;
  if not found then return query select false, 'Cupom inválido', v_original, 0::numeric, v_original, null::text; return; end if;
  if c.starts_at is not null and clock_timestamp() < c.starts_at then return query select false, 'Cupom ainda não iniciou', v_original, 0::numeric, v_original, null::text; return; end if;
  if c.ends_at is not null and clock_timestamp() >= c.ends_at then return query select false, 'Cupom expirado', v_original, 0::numeric, v_original, null::text; return; end if;
  select count(*) into v_coupon_used from public.tickets t
  where t.event_id = v_lot.event_id and upper(coalesce(t.coupon_code, '')) = v_code
    and t.payment_status in ('Pendente','Pago');
  if c.usage_limit > 0 and v_coupon_used >= c.usage_limit then
    return query select false, 'Limite do cupom atingido', v_original, 0::numeric, v_original, null::text;
    return;
  end if;
  v_discount := case when c.discount_type = 'percent'
    then round(v_original * least(c.discount_value, 100) / 100, 2)
    else least(v_original, c.discount_value) end;
  if v_original - v_discount <= 0 then
    return query select false, 'O desconto precisa deixar saldo para pagamento', v_original, v_discount, v_original, null::text;
    return;
  end if;
  return query select true, 'Cupom aplicado', v_original, v_discount, v_original - v_discount, c.code;
end;
$$;

create or replace function public.create_manual_order_v16(
  p_name text,
  p_phone text,
  p_email text,
  p_cpf text,
  p_gender text,
  p_lot_id bigint,
  p_coupon_code text default null,
  p_promoter_code text default null
)
returns table(
  id bigint, event_id bigint, ticket_code text, qr_token text, customer_name text,
  phone text, email text, cpf text, gender text, lot_id bigint, lot_name text,
  sector text, price numeric, original_price numeric, discount_amount numeric,
  coupon_code text, promoter_code text, payment_status text, entry_status text,
  purchased_at timestamptz
)
language plpgsql
security definer
set search_path = ''
as $$
declare
  v_lot public.ticket_lots%rowtype;
  v_event public.events%rowtype;
  c public.coupons_v16%rowtype;
  v_original numeric(12,2);
  v_discount numeric(12,2) := 0;
  v_service_fee numeric(12,2) := 1.98;
  v_final numeric(12,2);
  v_coupon_used bigint := 0;
  v_code text := upper(trim(coalesce(p_coupon_code, '')));
  v_promoter text := upper(trim(coalesce(p_promoter_code, '')));
  v_cpf text := nullif(regexp_replace(coalesce(p_cpf, ''), '[^0-9]', '', 'g'), '');
  v_id bigint;
  v_ticket_code text;
  v_qr text;
  v_purchased timestamptz;
  v_payment_status text := 'Pendente';
  v_payment_method text := 'PIX Asaas';
begin
  if length(trim(coalesce(p_name, ''))) < 2 then raise exception 'Nome do cliente é obrigatório'; end if;
  if position('@' in coalesce(p_email, '')) < 2 then raise exception 'E-mail inválido'; end if;
  if p_gender not in ('Feminino','Masculino') then raise exception 'Selecione Feminino ou Masculino'; end if;
  if v_cpf is not null and length(v_cpf) <> 11 then raise exception 'CPF precisa ter 11 números'; end if;

  select l.* into v_lot from public.ticket_lots l where l.id = p_lot_id for update;
  if not found or not private.hype_lot_available_at(v_lot, clock_timestamp()) then raise exception 'Categoria indisponível'; end if;
  select e.* into v_event from public.events e where e.id = v_lot.event_id for update;
  if not found or not v_event.active then raise exception 'Evento indisponível'; end if;

  if v_cpf is not null and v_event.max_tickets_per_cpf > 0 then
    perform pg_advisory_xact_lock(hashtextextended(v_event.id::text || ':' || v_cpf, 0));
    if (select count(*) from public.tickets t where t.event_id = v_event.id and t.cpf = v_cpf and t.payment_status in ('Pendente','Pago')) >= v_event.max_tickets_per_cpf then
      raise exception 'Limite de ingressos por CPF atingido';
    end if;
  end if;

  if v_lot.auto_sequence and exists (
    select 1 from public.ticket_lots earlier
    where earlier.event_id = v_lot.event_id and lower(earlier.sector) = lower(v_lot.sector)
      and earlier.active is true
      and (earlier.sort_order < v_lot.sort_order or (earlier.sort_order = v_lot.sort_order and earlier.id < v_lot.id))
      and (earlier.quantity_total = 0 or (select count(*) from public.tickets et where et.lot_id = earlier.id and et.payment_status in ('Pendente','Pago')) < earlier.quantity_total)
  ) then raise exception 'Este lote será liberado quando o anterior esgotar'; end if;

  v_original := private.hype_effective_price(v_lot, p_gender, clock_timestamp());
  if v_original = 0 then
    v_code := ''; v_service_fee := 0; v_final := 0;
    v_payment_status := 'Pago'; v_payment_method := p_gender || ' FREE';
  else
    if v_code <> '' then
      select x.* into c from public.coupons_v16 x
      where x.event_id = v_lot.event_id and x.code = v_code and x.active is true for update;
      if not found then raise exception 'Cupom inválido'; end if;
      if c.starts_at is not null and clock_timestamp() < c.starts_at then raise exception 'Cupom ainda não iniciou'; end if;
      if c.ends_at is not null and clock_timestamp() >= c.ends_at then raise exception 'Cupom expirado'; end if;
      select count(*) into v_coupon_used from public.tickets t
      where t.event_id = v_lot.event_id and upper(coalesce(t.coupon_code, '')) = v_code
        and t.payment_status in ('Pendente','Pago');
      if c.usage_limit > 0 and v_coupon_used >= c.usage_limit then raise exception 'Limite do cupom atingido'; end if;
      v_discount := case when c.discount_type = 'percent'
        then round(v_original * least(c.discount_value, 100) / 100, 2)
        else least(v_original, c.discount_value) end;
    end if;
    if v_original - v_discount <= 0 then raise exception 'O desconto precisa deixar saldo para pagamento'; end if;
    v_final := round(v_original - v_discount + v_service_fee, 2);
  end if;

  if v_promoter <> '' and not exists (
    select 1 from public.promoters_global_v16 p where p.code = v_promoter and p.active is true
  ) then raise exception 'Código de promoter inválido'; end if;

  loop
    v_ticket_code := 'HYPE-' || upper(substr(md5(random()::text || clock_timestamp()::text), 1, 10));
    exit when not exists (select 1 from public.tickets t where t.ticket_code = v_ticket_code);
  end loop;
  v_qr := extensions.gen_random_uuid()::text;

  insert into public.tickets(
    event_id, lot_id, customer_name, phone, email, cpf, gender, price,
    original_price, discount_amount, service_fee, coupon_code, promoter_code,
    ticket_code, qr_token, payment_status, payment_method, paid_at
  ) values (
    v_lot.event_id, v_lot.id, trim(p_name), nullif(trim(p_phone), ''), lower(trim(p_email)),
    v_cpf, p_gender, v_final, v_original, v_discount, v_service_fee,
    nullif(v_code, ''), nullif(v_promoter, ''), v_ticket_code, v_qr,
    v_payment_status, v_payment_method,
    case when v_payment_status = 'Pago' then now() else null end
  ) returning tickets.id, tickets.purchased_at into v_id, v_purchased;

  return query select v_id, v_lot.event_id, v_ticket_code, v_qr, trim(p_name),
    nullif(trim(p_phone), ''), lower(trim(p_email)), v_cpf, p_gender,
    v_lot.id, v_lot.name, v_lot.sector, v_final, v_original, v_discount,
    nullif(v_code, ''), nullif(v_promoter, ''), v_payment_status,
    'Não utilizado'::text, v_purchased;
end;
$$;

create or replace function public.staff_log_action_v17(
  p_username text,p_password text,p_ticket_id bigint,p_action text,p_details jsonb default '{}'::jsonb
)
returns boolean language plpgsql security definer set search_path='' as $$
declare v_staff public.staff_users%rowtype; v_event_id bigint;
begin
  v_staff:=private.hype_require_staff(p_username,p_password,null);
  select event_id into v_event_id from public.tickets where id=p_ticket_id;
  insert into public.audit_logs(staff_user_id,action,ticket_id,metadata)
  values(v_staff.id,upper(trim(p_action)),p_ticket_id,
    coalesce(p_details,'{}'::jsonb)||jsonb_build_object('event_id',v_event_id,'actor_username',v_staff.username,'actor_role',v_staff.role));
  return true;
end; $$;

create or replace function public.staff_action_logs_v17(
  p_username text,p_password text,p_event_id bigint,p_limit integer default 100
)
returns table(id bigint,created_at timestamptz,actor_username text,actor_role text,action text,ticket_id bigint,ticket_code text,customer_name text,details jsonb)
language plpgsql security definer set search_path='' as $$
begin
  perform private.hype_require_staff(p_username,p_password,array['admin','gerente']);
  return query select a.id,a.created_at,coalesce(s.username,a.metadata->>'actor_username',''),
    coalesce(s.role,a.metadata->>'actor_role',''),a.action,a.ticket_id,t.ticket_code,t.customer_name,a.metadata
  from public.audit_logs a left join public.staff_users s on s.id=a.staff_user_id
  left join public.tickets t on t.id=a.ticket_id
  where coalesce((a.metadata->>'event_id')::bigint,t.event_id)=p_event_id
  order by a.created_at desc limit greatest(1,least(coalesce(p_limit,100),500));
end; $$;

create or replace function public.staff_event_summary_v17(p_username text,p_password text,p_event_id bigint)
returns jsonb language plpgsql security definer set search_path='' as $$
declare v_result jsonb;
begin
  perform private.hype_require_staff(p_username,p_password,array['admin','gerente','caixa']);
  select jsonb_build_object('event_id',e.id,'event_name',e.name,'event_date',e.event_date,
    'closed_at',e.closed_at,'sold',count(t.id) filter(where t.payment_status='Pago'),
    'revenue',coalesce(sum(t.price) filter(where t.payment_status='Pago'),0),
    'entered',count(t.id) filter(where t.payment_status='Pago' and t.entry_status='Entrada utilizada'),
    'not_entered',count(t.id) filter(where t.payment_status='Pago' and t.entry_status<>'Entrada utilizada'),
    'canceled',count(t.id) filter(where t.payment_status in('Cancelado','Estornado')),
    'female',count(t.id) filter(where t.payment_status='Pago' and t.gender='Feminino'),
    'male',count(t.id) filter(where t.payment_status='Pago' and t.gender='Masculino'))
  into v_result from public.events e left join public.tickets t on t.event_id=e.id
  where e.id=p_event_id group by e.id;
  return coalesce(v_result,'{}'::jsonb);
end; $$;

create or replace function public.staff_close_event_v17(p_username text,p_password text,p_event_id bigint)
returns boolean language plpgsql security definer set search_path='' as $$
declare v_staff public.staff_users%rowtype;
begin
  v_staff:=private.hype_require_staff(p_username,p_password,array['admin','gerente']);
  update public.events set closed_at=now(),closed_by=v_staff.username,active=false where id=p_event_id;
  if not found then raise exception 'Evento não encontrado'; end if;
  insert into public.audit_logs(staff_user_id,action,metadata)
  values(v_staff.id,'EVENTO_ENCERRADO',jsonb_build_object('event_id',p_event_id));
  return true;
end; $$;

create or replace function public.staff_set_event_cpf_limit_v17(p_username text,p_password text,p_event_id bigint,p_limit_one boolean)
returns boolean language plpgsql security definer set search_path='' as $$
begin
  perform private.hype_require_staff(p_username,p_password,array['admin','gerente']);
  update public.events set max_tickets_per_cpf=case when p_limit_one then 1 else 0 end where id=p_event_id;
  if not found then raise exception 'Evento não encontrado'; end if;
  return true;
end; $$;

create or replace function public.staff_purge_ticket_v25(p_username text,p_password text,p_ticket_id bigint)
returns boolean language plpgsql security definer set search_path='' as $$
begin
  perform private.hype_require_staff(p_username,p_password,array['admin']);
  update public.raffle_draws_v18 d set winner_name=coalesce(nullif(d.winner_name,''),t.customer_name),
    winner_code=coalesce(nullif(d.winner_code,''),t.ticket_code),winner_phone=coalesce(d.winner_phone,t.phone),
    winner_promoter_code=coalesce(d.winner_promoter_code,t.promoter_code),winner_ticket_id=null
  from public.tickets t where t.id=p_ticket_id and d.winner_ticket_id=t.id;
  delete from public.tickets where id=p_ticket_id;
  if not found then raise exception 'Ingresso não encontrado'; end if;
  return true;
end; $$;

create or replace function public.staff_purge_all_tickets(p_username text,p_password text)
returns integer language plpgsql security definer set search_path='' as $$
declare v_count integer;
begin
  perform private.hype_require_staff(p_username,p_password,array['admin']);
  update public.raffle_draws_v18 d set winner_name=coalesce(nullif(d.winner_name,''),t.customer_name),
    winner_code=coalesce(nullif(d.winner_code,''),t.ticket_code),winner_ticket_id=null
  from public.tickets t where d.winner_ticket_id=t.id;
  delete from public.tickets;
  get diagnostics v_count=row_count;
  return v_count;
end; $$;

create or replace function public.staff_refund_list_v38(p_username text,p_password text,p_event_id bigint)
returns table(ticket_id bigint,customer_name text,gender text,ticket_code text,lot_name text,email text,price numeric,payment_method text,entry_status text,refund_amount numeric,refund_status text,refund_mode text,free_after_refund boolean,eligible boolean)
language plpgsql security definer set search_path='' as $$
begin
  perform private.hype_require_staff(p_username,p_password,array['admin']);
  return query select t.id,t.customer_name,t.gender,t.ticket_code,l.name,t.email,t.price,t.payment_method,t.entry_status,
    t.refund_amount,t.refund_status,t.refund_mode,t.free_after_refund,
    (t.payment_status='Pago' and coalesce(t.asaas_payment_id,'')<>'' and t.refund_amount=0)
  from public.tickets t join public.ticket_lots l on l.id=t.lot_id
  where t.event_id=p_event_id and (t.payment_status='Pago' or t.refund_amount>0)
  order by t.purchased_at desc;
end; $$;

create or replace function public.staff_guest_simple_add_v408(p_username text,p_password text,p_event_id bigint,p_name text)
returns table(list_id bigint,name text,already_exists boolean,message text,status text)
language plpgsql security definer set search_path='' as $$
declare v_staff public.staff_users%rowtype; v_key text; v_row public.guest_list_simple_v406%rowtype;
begin
  v_staff:=private.hype_require_staff(p_username,p_password,array['admin','gerente','caixa']);
  v_key:=private.hype_name_key(p_name);
  if length(v_key)<2 then raise exception 'Nome inválido'; end if;
  if exists(select 1 from public.tickets t where t.event_id=p_event_id and private.hype_name_key(t.customer_name)=v_key and t.payment_status in('Pendente','Pago')) then
    return query select null::bigint,trim(p_name),true,'Já possui ingresso neste evento','Com ingresso'; return;
  end if;
  select g.* into v_row from public.guest_list_simple_v406 g where g.event_id=p_event_id and g.name_key=v_key;
  if found then return query select v_row.id,v_row.name,true,'Já estava na lista',v_row.status; return; end if;
  insert into public.guest_list_simple_v406(event_id,name,name_key,added_by)
  values(p_event_id,trim(p_name),v_key,v_staff.username) returning * into v_row;
  return query select v_row.id,v_row.name,false,'Nome adicionado',v_row.status;
end; $$;

create or replace function public.staff_guest_simple_delete_v423(p_username text,p_password text,p_list_id bigint)
returns boolean language plpgsql security definer set search_path='' as $$
begin
  perform private.hype_require_staff(p_username,p_password,array['admin','gerente']);
  delete from public.guest_list_simple_v406 where id=p_list_id;
  return found;
end; $$;

create or replace function public.staff_guest_simple_list_v406(p_username text,p_password text,p_event_id bigint)
returns table(list_id bigint,name text,status text,created_at timestamptz,entered_at timestamptz,added_by text)
language plpgsql security definer set search_path='' as $$
begin
  perform private.hype_require_staff(p_username,p_password,array['admin','gerente','caixa','portaria']);
  return query select g.id,g.name,g.status,g.created_at,g.entered_at,g.added_by
  from public.guest_list_simple_v406 g where g.event_id=p_event_id and g.status<>'Cancelado'
  order by g.status,g.created_at desc;
end; $$;

create or replace function public.portaria_guest_simple_search_v406(p_device_key text,p_event_id bigint,p_query text)
returns table(list_id bigint,name text,cpf text,gender text,status text,created_at timestamptz,entered_at timestamptz)
language plpgsql security definer set search_path='' as $$
declare v_query text:=lower(trim(coalesce(p_query,'')));
begin
  if not private.hype_device_authorized(p_device_key) then raise exception 'Computador não autorizado'; end if;
  if length(v_query)<1 then raise exception 'Digite um nome para buscar'; end if;
  return query select g.id,g.name,coalesce(g.cpf,''),coalesce(g.gender,''),g.status,g.created_at,g.entered_at
  from public.guest_list_simple_v406 g where g.event_id=p_event_id and g.status<>'Cancelado'
    and (lower(g.name) like '%'||v_query||'%' or regexp_replace(coalesce(g.cpf,''),'[^0-9]','','g') like '%'||regexp_replace(v_query,'[^0-9]','','g')||'%')
  order by case when lower(g.name)=v_query then 0 else 1 end,g.status,g.created_at desc limit 30;
end; $$;

create or replace function public.portaria_guest_simple_enter_v406(p_device_key text,p_list_id bigint)
returns table(ok boolean,message text,list_id bigint,name text,status text,entered_at timestamptz)
language plpgsql security definer set search_path='' as $$
declare v_row public.guest_list_simple_v406%rowtype;
begin
  if not private.hype_device_authorized(p_device_key) then raise exception 'Computador não autorizado'; end if;
  select g.* into v_row from public.guest_list_simple_v406 g where g.id=p_list_id for update;
  if not found then return query select false,'NOME NÃO ENCONTRADO',null::bigint,null::text,null::text,null::timestamptz; return; end if;
  if v_row.status='Entrou' then return query select false,'NOME JÁ ENTROU',v_row.id,v_row.name,v_row.status,v_row.entered_at; return; end if;
  update public.guest_list_simple_v406 set status='Entrou',entered_at=now() where id=v_row.id returning * into v_row;
  return query select true,'ENTRADA DA LISTA LIBERADA',v_row.id,v_row.name,v_row.status,v_row.entered_at;
end; $$;

create or replace function public.staff_add_guest_ticket_v40(
  p_username text,p_password text,p_event_id bigint,p_lot_id bigint,p_name text,p_gender text,p_cpf text default null
)
returns table(ticket_id bigint,event_id bigint,event_name text,ticket_code text,qr_token text,customer_name text,cpf text,gender text,lot_id bigint,lot_name text,sector text,payment_status text,payment_method text,purchased_at timestamptz)
language plpgsql security definer set search_path='' as $$
declare v_lot public.ticket_lots%rowtype; v_event public.events%rowtype; v_id bigint; v_code text; v_qr text; v_at timestamptz; v_cpf text:=nullif(regexp_replace(coalesce(p_cpf,''),'[^0-9]','','g'),'');
begin
  perform private.hype_require_staff(p_username,p_password,array['admin','gerente','caixa']);
  if length(trim(coalesce(p_name,'')))<2 then raise exception 'Informe o nome'; end if;
  if p_gender not in('Feminino','Masculino') then raise exception 'Selecione o gênero'; end if;
  select l.* into v_lot from public.ticket_lots l where l.id=p_lot_id and l.event_id=p_event_id for update;
  if not found or not v_lot.active then raise exception 'Lote indisponível'; end if;
  select e.* into v_event from public.events e where e.id=p_event_id;
  loop v_code:='HYPE-'||upper(substr(md5(random()::text||clock_timestamp()::text),1,10)); exit when not exists(select 1 from public.tickets existing where existing.ticket_code=v_code); end loop;
  v_qr:=extensions.gen_random_uuid()::text;
  insert into public.tickets as inserted(event_id,lot_id,customer_name,cpf,gender,price,original_price,service_fee,ticket_code,qr_token,payment_status,payment_method,paid_at)
  values(p_event_id,p_lot_id,trim(p_name),v_cpf,p_gender,0,0,0,v_code,v_qr,'Pago','Cortesia Admin',now())
  returning inserted.id,inserted.purchased_at into v_id,v_at;
  return query select v_id,p_event_id,v_event.name,v_code,v_qr,trim(p_name),v_cpf,p_gender,p_lot_id,v_lot.name,v_lot.sector,'Pago','Cortesia Admin',v_at;
end; $$;

create or replace function public.staff_list_raffle_events_v23(p_username text,p_password text)
returns table(id bigint,name text,artist_name text,event_date date,active boolean,raffle_enabled boolean,raffle_prize text)
language plpgsql security definer set search_path='' as $$
begin
  perform private.hype_require_staff(p_username,p_password,array['admin','gerente','caixa']);
  return query select e.id,e.name,e.artist_name,e.event_date,e.active,e.raffle_enabled,e.raffle_prize
  from public.events e order by e.event_date nulls last,e.id;
end; $$;

create or replace function public.staff_save_raffle_v18(p_username text,p_password text,p_event_id bigint,p_enabled boolean,p_prize text)
returns boolean language plpgsql security definer set search_path='' as $$
begin
  perform private.hype_require_staff(p_username,p_password,array['admin']);
  if coalesce(p_enabled,false) and coalesce(trim(p_prize),'')='' then raise exception 'Informe o prêmio'; end if;
  update public.events set raffle_enabled=coalesce(p_enabled,false),raffle_prize=coalesce(trim(p_prize),'') where id=p_event_id;
  if not found then raise exception 'Evento não encontrado'; end if;
  return true;
end; $$;

create or replace function public.public_raffle_info_v18(p_event_id bigint)
returns table(event_id bigint,enabled boolean,prize text,participant_count bigint)
language sql stable security definer set search_path='' as $$
  select e.id,e.raffle_enabled,e.raffle_prize,count(t.id) filter(where t.payment_status='Pago')::bigint
  from public.events e left join public.tickets t on t.event_id=e.id
  where e.id=p_event_id and e.active is true group by e.id;
$$;

create or replace function public.staff_raffle_status_v18(p_username text,p_password text,p_event_id bigint)
returns table(event_id bigint,event_name text,enabled boolean,prize text,participant_count bigint,last_winner_name text,last_winner_code text,last_draw_at timestamptz)
language plpgsql security definer set search_path='' as $$
begin
  perform private.hype_require_staff(p_username,p_password,array['admin']);
  return query select e.id,e.name,e.raffle_enabled,e.raffle_prize,
    count(t.id) filter(where t.payment_status='Pago')::bigint,
    d.winner_name,d.winner_code,d.drawn_at
  from public.events e left join public.tickets t on t.event_id=e.id
  left join lateral(select x.* from public.raffle_draws_v18 x where x.event_id=e.id order by x.drawn_at desc,x.id desc limit 1)d on true
  where e.id=p_event_id group by e.id,d.winner_name,d.winner_code,d.drawn_at;
end; $$;

create or replace function public.staff_raffle_participants_v18(p_username text,p_password text,p_event_id bigint)
returns table(ticket_id bigint,customer_name text,ticket_code text,phone text,cpf text,promoter_code text,purchased_at timestamptz,paid_at timestamptz)
language plpgsql security definer set search_path='' as $$
begin
  perform private.hype_require_staff(p_username,p_password,array['admin']);
  return query select t.id,t.customer_name,t.ticket_code,t.phone,t.cpf,t.promoter_code,t.purchased_at,t.paid_at
  from public.tickets t where t.event_id=p_event_id and t.payment_status='Pago'
  order by coalesce(t.paid_at,t.purchased_at) desc,t.id desc;
end; $$;

create or replace function public.staff_draw_raffle_v18(p_username text,p_password text,p_event_id bigint)
returns table(draw_id bigint,winner_ticket_id bigint,customer_name text,ticket_code text,phone text,cpf text,promoter_code text,prize text,drawn_at timestamptz)
language plpgsql security definer set search_path='' as $$
declare v_staff public.staff_users%rowtype; v_event public.events%rowtype; v_winner public.tickets%rowtype; v_draw public.raffle_draws_v18%rowtype;
begin
  v_staff:=private.hype_require_staff(p_username,p_password,array['admin']);
  select e.* into v_event from public.events e where e.id=p_event_id for update;
  if not found or not v_event.raffle_enabled then raise exception 'Ative o sorteio antes de sortear'; end if;
  if trim(v_event.raffle_prize)='' then raise exception 'Informe o prêmio'; end if;
  select t.* into v_winner from public.tickets t
  where t.event_id=p_event_id and t.payment_status='Pago'
    and not exists(
      select 1 from public.raffle_draws_v18 d
      where d.event_id=p_event_id and (
        d.winner_ticket_id=t.id
        or (regexp_replace(coalesce(t.cpf,''),'[^0-9]','','g')<>'' and regexp_replace(coalesce(d.winner_cpf,''),'[^0-9]','','g')=regexp_replace(coalesce(t.cpf,''),'[^0-9]','','g'))
        or (regexp_replace(coalesce(t.cpf,''),'[^0-9]','','g')='' and private.hype_name_key(d.winner_name)=private.hype_name_key(t.customer_name))
      )
    )
  order by random() limit 1;
  if not found then raise exception 'Nenhum participante disponível'; end if;
  insert into public.raffle_draws_v18(event_id,winner_ticket_id,winner_name,winner_code,winner_cpf,winner_phone,winner_promoter_code,prize,drawn_by)
  values(p_event_id,v_winner.id,v_winner.customer_name,v_winner.ticket_code,v_winner.cpf,v_winner.phone,v_winner.promoter_code,v_event.raffle_prize,v_staff.username)
  returning * into v_draw;
  return query select v_draw.id,v_winner.id,v_winner.customer_name,v_winner.ticket_code,v_winner.phone,v_winner.cpf,v_winner.promoter_code,v_draw.prize,v_draw.drawn_at;
end; $$;

create or replace function public.public_survey_open_v34(p_token text)
returns table(event_name text,event_date date,venue text,already_responded boolean)
language sql stable security definer set search_path='' as $$
  select e.name,e.event_date,e.venue,(i.responded_at is not null)
  from public.event_survey_invites_v34 i join public.events e on e.id=i.event_id
  where i.token=p_token::uuid limit 1;
$$;

create or replace function public.public_survey_submit_v34(p_token text,p_rating integer,p_would_return boolean,p_comment text)
returns boolean language plpgsql security definer set search_path='' as $$
declare v_invite public.event_survey_invites_v34%rowtype;
begin
  if p_rating is null or p_rating not between 1 and 5 then raise exception 'Escolha uma nota de 1 a 5'; end if;
  select i.* into v_invite from public.event_survey_invites_v34 i where i.token=p_token::uuid for update;
  if not found then raise exception 'Link da pesquisa inválido'; end if;
  if v_invite.responded_at is not null then raise exception 'Esta pesquisa já foi respondida'; end if;
  insert into public.event_survey_responses_v34(invite_token,event_id,ticket_id,rating,would_return,comment)
  values(v_invite.token,v_invite.event_id,v_invite.ticket_id,p_rating,coalesce(p_would_return,false),left(trim(coalesce(p_comment,'')),1200));
  update public.event_survey_invites_v34 set responded_at=now() where token=v_invite.token;
  return true;
exception when invalid_text_representation then raise exception 'Link da pesquisa inválido';
end; $$;

create or replace function public.staff_survey_attendees_v35(p_username text,p_password text,p_event_id bigint)
returns table(ticket_id bigint,customer_name text,phone text,email text,invite_token text,sent_at timestamptz,sent_count integer,email_sent_at timestamptz,whatsapp_sent_at timestamptz,whatsapp_error text,responded boolean)
language plpgsql security definer set search_path='' as $$
begin
  perform private.hype_require_staff(p_username,p_password,array['admin','gerente']);
  insert into public.event_survey_invites_v34(event_id,ticket_id)
  select t.event_id,t.id from public.tickets t where t.event_id=p_event_id and t.payment_status='Pago' and t.entry_status='Entrada utilizada'
  on conflict on constraint event_survey_invites_v34_ticket_id_key do nothing;
  return query select t.id,t.customer_name,coalesce(t.phone,''),coalesce(t.email,''),i.token::text,i.sent_at,i.sent_count,
    i.email_sent_at,i.whatsapp_sent_at,coalesce(i.whatsapp_error,''),(i.responded_at is not null)
  from public.event_survey_invites_v34 i join public.tickets t on t.id=i.ticket_id
  where i.event_id=p_event_id order by coalesce(t.entry_at,t.purchased_at) desc,t.id desc;
end; $$;

create or replace function public.staff_survey_attendees_v34(p_username text,p_password text,p_event_id bigint)
returns table(ticket_id bigint,customer_name text,phone text,email text,invite_token text,sent_at timestamptz,sent_count integer,email_sent_at timestamptz,whatsapp_sent_at timestamptz,whatsapp_error text,responded boolean)
language sql security definer set search_path='' as $$
  select * from public.staff_survey_attendees_v35(p_username,p_password,p_event_id);
$$;

create or replace function public.staff_survey_report_v34(p_username text,p_password text,p_event_id bigint)
returns jsonb language plpgsql security definer set search_path='' as $$
declare v_result jsonb;
begin
  perform private.hype_require_staff(p_username,p_password,array['admin','gerente']);
  select jsonb_build_object(
    'eligible_count',(select count(*) from public.tickets t where t.event_id=p_event_id and t.payment_status='Pago' and t.entry_status='Entrada utilizada'),
    'invited_count',(select count(*) from public.event_survey_invites_v34 i where i.event_id=p_event_id and (i.sent_at is not null or i.email_sent_at is not null or i.whatsapp_sent_at is not null)),
    'response_count',count(r.id),'average_rating',coalesce(round(avg(r.rating)::numeric,2),0),
    'would_return_yes',count(r.id) filter(where r.would_return),'rating_1',count(r.id) filter(where r.rating=1),
    'rating_2',count(r.id) filter(where r.rating=2),'rating_3',count(r.id) filter(where r.rating=3),
    'rating_4',count(r.id) filter(where r.rating=4),'rating_5',count(r.id) filter(where r.rating=5),
    'comments',coalesce(jsonb_agg(jsonb_build_object('name',t.customer_name,'rating',r.rating,'would_return',r.would_return,'comment',r.comment,'submitted_at',r.submitted_at) order by r.submitted_at desc) filter(where r.id is not null),'[]'::jsonb)
  ) into v_result from public.event_survey_responses_v34 r left join public.tickets t on t.id=r.ticket_id where r.event_id=p_event_id;
  return coalesce(v_result,'{}'::jsonb);
end; $$;

create or replace function public.staff_system_checkup_v43(p_username text,p_password text,p_event_id bigint)
returns table(area text,status text,detail text)
language plpgsql security definer set search_path='' as $$
begin
  perform private.hype_require_staff(p_username,p_password,array['admin','gerente']);
  return query values
    ('Banco'::text,'OK'::text,'Tabelas principais acessíveis'::text),
    ('Evento','OK',case when exists(select 1 from public.events where id=p_event_id) then 'Evento selecionado encontrado' else 'Nenhum evento selecionado' end),
    ('Ingressos','OK',(select count(*)::text||' ingresso(s)' from public.tickets where event_id=p_event_id)),
    ('Estoque','OK','Proteção transacional ativa'),
    ('Segurança','OK','Tabelas privadas com acesso por RPC');
end; $$;

create or replace function public.staff_system_checkup_v429(p_username text,p_password text,p_event_id bigint)
returns table(area text,status text,detail text)
language sql security definer set search_path='' as $$
  select * from public.staff_system_checkup_v43(p_username,p_password,p_event_id);
$$;

revoke execute on all functions in schema public from public, anon, authenticated;
revoke execute on all functions in schema private from public, anon, authenticated;

grant execute on function public.public_lots_by_event_v16(bigint) to anon,authenticated;
grant execute on function public.public_lot_free_rules_v38(bigint) to anon,authenticated;
grant execute on function public.public_quote_v16(bigint,text,text) to anon,authenticated;
grant execute on function public.create_manual_order_v16(text,text,text,text,text,bigint,text,text) to anon,authenticated;
grant execute on function public.staff_add_user(text,text,text,text,text,text) to anon,authenticated;
grant execute on function public.staff_list_users(text,text) to anon,authenticated;
grant execute on function public.staff_delete_user(text,text,bigint) to anon,authenticated;
grant execute on function public.staff_upsert_promoter_v16(text,text,bigint,bigint,text,text,boolean) to anon,authenticated;
grant execute on function public.staff_list_promoters_v16(text,text,bigint) to anon,authenticated;
grant execute on function public.staff_delete_promoter_v16(text,text,bigint,bigint) to anon,authenticated;
grant execute on function public.staff_upsert_promoter_global_v16(text,text,bigint,text,text,boolean) to anon,authenticated;
grant execute on function public.staff_list_promoters_global_v16(text,text) to anon,authenticated;
grant execute on function public.staff_delete_promoter_global_v16(text,text,bigint) to anon,authenticated;
grant execute on function public.staff_upsert_coupon_v16(text,text,bigint,bigint,text,text,numeric,integer,timestamptz,timestamptz,boolean) to anon,authenticated;
grant execute on function public.staff_list_coupons_v16(text,text,bigint) to anon,authenticated;
grant execute on function public.staff_lot_free_rules_v38(text,text,bigint) to anon,authenticated;
grant execute on function public.staff_set_lot_free_until_v38(text,text,bigint,timestamptz,timestamptz) to anon,authenticated;
grant execute on function public.staff_log_action_v17(text,text,bigint,text,jsonb) to anon,authenticated;
grant execute on function public.staff_action_logs_v17(text,text,bigint,integer) to anon,authenticated;
grant execute on function public.staff_event_summary_v17(text,text,bigint) to anon,authenticated;
grant execute on function public.staff_close_event_v17(text,text,bigint) to anon,authenticated;
grant execute on function public.staff_set_event_cpf_limit_v17(text,text,bigint,boolean) to anon,authenticated;
grant execute on function public.staff_purge_ticket_v25(text,text,bigint) to anon,authenticated;
grant execute on function public.staff_purge_all_tickets(text,text) to anon,authenticated;
grant execute on function public.staff_refund_list_v38(text,text,bigint) to anon,authenticated;
grant execute on function public.staff_guest_simple_add_v408(text,text,bigint,text) to anon,authenticated;
grant execute on function public.staff_guest_simple_delete_v423(text,text,bigint) to anon,authenticated;
grant execute on function public.staff_guest_simple_list_v406(text,text,bigint) to anon,authenticated;
grant execute on function public.portaria_guest_simple_search_v406(text,bigint,text) to anon,authenticated;
grant execute on function public.portaria_guest_simple_enter_v406(text,bigint) to anon,authenticated;
grant execute on function public.staff_add_guest_ticket_v40(text,text,bigint,bigint,text,text,text) to anon,authenticated;
grant execute on function public.staff_list_raffle_events_v23(text,text) to anon,authenticated;
grant execute on function public.staff_save_raffle_v18(text,text,bigint,boolean,text) to anon,authenticated;
grant execute on function public.public_raffle_info_v18(bigint) to anon,authenticated;
grant execute on function public.staff_raffle_status_v18(text,text,bigint) to anon,authenticated;
grant execute on function public.staff_raffle_participants_v18(text,text,bigint) to anon,authenticated;
grant execute on function public.staff_draw_raffle_v18(text,text,bigint) to anon,authenticated;
grant execute on function public.public_survey_open_v34(text) to anon,authenticated;
grant execute on function public.public_survey_submit_v34(text,integer,boolean,text) to anon,authenticated;
grant execute on function public.staff_survey_attendees_v34(text,text,bigint) to anon,authenticated;
grant execute on function public.staff_survey_attendees_v35(text,text,bigint) to anon,authenticated;
grant execute on function public.staff_survey_report_v34(text,text,bigint) to anon,authenticated;
grant execute on function public.staff_system_checkup_v43(text,text,bigint) to anon,authenticated;
grant execute on function public.staff_system_checkup_v429(text,text,bigint) to anon,authenticated;

-- Core functions were revoked above and remain part of the browser RPC surface.
grant execute on function public.verify_staff(text,text) to anon,authenticated;
grant execute on function public.public_events() to anon,authenticated;
grant execute on function public.public_events_v13() to anon,authenticated;
grant execute on function public.public_pix_key() to anon,authenticated;
grant execute on function public.public_get_ticket(text) to anon,authenticated;
grant execute on function public.staff_list_events(text,text) to anon,authenticated;
grant execute on function public.staff_list_events_v13(text,text) to anon,authenticated;
grant execute on function public.staff_save_event_v2(text,text,bigint,text,text,date,time,time,text,text,text,boolean,integer) to anon,authenticated;
grant execute on function public.staff_save_event_v13(text,text,bigint,text,text,date,time,time,text,text,text,boolean,integer,text) to anon,authenticated;
grant execute on function public.staff_list_lots_v16(text,text,bigint) to anon,authenticated;
grant execute on function public.staff_upsert_lot_v16(text,text,bigint,bigint,text,text,numeric,numeric,integer,timestamptz,timestamptz,boolean,integer,boolean) to anon,authenticated;
grant execute on function public.staff_save_pix(text,text,text) to anon,authenticated;
grant execute on function public.staff_list_tickets(text,text,text) to anon,authenticated;
grant execute on function public.staff_list_tickets_manual(text,text,text) to anon,authenticated;
grant execute on function public.staff_list_tickets_v16(text,text,text) to anon,authenticated;
grant execute on function public.staff_set_payment(text,text,bigint,text) to anon,authenticated;

notify pgrst,'reload schema';
