-- HYPE V49: permanent public guest-list and promoter registration links.

alter table public.guest_list_simple_v406
  add column if not exists phone text,
  add column if not exists source text not null default 'Admin',
  add column if not exists updated_at timestamptz not null default now();

alter table public.promoters_global_v16
  add column if not exists cpf text,
  add column if not exists phone text,
  add column if not exists source text not null default 'Admin';

alter table public.guest_list_simple_v406
  drop constraint if exists guest_list_simple_v406_event_id_name_key_key;

do $$
begin
  if not exists (
    select 1 from pg_constraint
    where conrelid = 'public.guest_list_simple_v406'::regclass
      and conname = 'hype_guest_list_source_v49_check'
  ) then
    alter table public.guest_list_simple_v406
      add constraint hype_guest_list_source_v49_check
      check (source in ('Admin','Publico'));
  end if;

  if not exists (
    select 1 from pg_constraint
    where conrelid = 'public.promoters_global_v16'::regclass
      and conname = 'hype_promoter_source_v49_check'
  ) then
    alter table public.promoters_global_v16
      add constraint hype_promoter_source_v49_check
      check (source in ('Admin','Publico'));
  end if;
end;
$$;

update public.guest_list_simple_v406
set cpf = nullif(regexp_replace(coalesce(cpf,''), '[^0-9]', '', 'g'), '')
where cpf is not null;

update public.promoters_global_v16
set cpf = nullif(regexp_replace(coalesce(cpf,''), '[^0-9]', '', 'g'), '')
where cpf is not null;

create unique index if not exists hype_guest_list_event_cpf_v49_uidx
  on public.guest_list_simple_v406(event_id, cpf)
  where cpf ~ '^[0-9]{11}$' and status <> 'Cancelado';

create unique index if not exists hype_promoters_global_cpf_v49_uidx
  on public.promoters_global_v16(cpf)
  where cpf ~ '^[0-9]{11}$';

drop trigger if exists hype_guest_list_simple_v49_updated_at on public.guest_list_simple_v406;
create trigger hype_guest_list_simple_v49_updated_at
before update on public.guest_list_simple_v406
for each row execute function private.hype_touch_updated_at();

create table public.public_guest_registration_settings_v49 (
  id boolean primary key default true check (id),
  event_id bigint references public.events(id) on delete set null,
  registration_open boolean not null default false,
  updated_by text not null default '',
  updated_at timestamptz not null default now()
);

insert into public.public_guest_registration_settings_v49(id, registration_open, updated_by)
values(true, false, 'system')
on conflict(id) do nothing;

create table public.person_blocks_v49 (
  id bigint generated by default as identity primary key,
  name text not null check (length(trim(name)) between 2 and 160),
  name_key text not null,
  cpf text,
  block_type text not null check (block_type in ('Temporario','Permanente')),
  blocked_until timestamptz,
  reason text not null default '' check (length(reason) <= 500),
  active boolean not null default true,
  created_by text not null,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  check (
    (block_type = 'Permanente' and blocked_until is null)
    or (block_type = 'Temporario' and blocked_until is not null)
  )
);

create unique index hype_person_blocks_active_cpf_v49_uidx
  on public.person_blocks_v49(cpf)
  where active is true and cpf ~ '^[0-9]{11}$';

create index hype_person_blocks_name_v49_idx
  on public.person_blocks_v49(name_key, active);

alter table public.public_guest_registration_settings_v49 enable row level security;
alter table public.person_blocks_v49 enable row level security;
revoke all on public.public_guest_registration_settings_v49 from public, anon, authenticated;
revoke all on public.person_blocks_v49 from public, anon, authenticated;
revoke all on sequence public.person_blocks_v49_id_seq from public, anon, authenticated;

drop trigger if exists hype_public_guest_settings_v49_updated_at on public.public_guest_registration_settings_v49;
create trigger hype_public_guest_settings_v49_updated_at
before update on public.public_guest_registration_settings_v49
for each row execute function private.hype_touch_updated_at();

drop trigger if exists hype_person_blocks_v49_updated_at on public.person_blocks_v49;
create trigger hype_person_blocks_v49_updated_at
before update on public.person_blocks_v49
for each row execute function private.hype_touch_updated_at();

create or replace function private.hype_digits_v49(p_value text)
returns text
language sql
immutable
set search_path = ''
as $$
  select regexp_replace(coalesce(p_value, ''), '[^0-9]', '', 'g');
$$;

create or replace function private.hype_normalize_phone_v49(p_phone text)
returns text
language plpgsql
immutable
set search_path = ''
as $$
declare
  v_phone text := private.hype_digits_v49(p_phone);
begin
  if length(v_phone) = 13 and left(v_phone, 2) = '55' then
    v_phone := substr(v_phone, 3);
  end if;
  return v_phone;
end;
$$;

create or replace function private.hype_valid_cpf_v49(p_cpf text)
returns boolean
language plpgsql
immutable
set search_path = ''
as $$
declare
  v_cpf text := private.hype_digits_v49(p_cpf);
  v_sum integer := 0;
  v_digit integer;
  i integer;
begin
  if length(v_cpf) <> 11 or v_cpf ~ '^([0-9])\1{10}$' then
    return false;
  end if;

  for i in 1..9 loop
    v_sum := v_sum + substr(v_cpf, i, 1)::integer * (11 - i);
  end loop;
  v_digit := case when (v_sum * 10) % 11 = 10 then 0 else (v_sum * 10) % 11 end;
  if v_digit <> substr(v_cpf, 10, 1)::integer then return false; end if;

  v_sum := 0;
  for i in 1..10 loop
    v_sum := v_sum + substr(v_cpf, i, 1)::integer * (12 - i);
  end loop;
  v_digit := case when (v_sum * 10) % 11 = 10 then 0 else (v_sum * 10) % 11 end;
  return v_digit = substr(v_cpf, 11, 1)::integer;
end;
$$;

create or replace function private.hype_person_is_blocked_v49(p_cpf text, p_name text)
returns boolean
language sql
stable
security definer
set search_path = ''
as $$
  select exists (
    select 1
    from public.person_blocks_v49 b
    where b.active is true
      and (b.block_type = 'Permanente' or clock_timestamp() < b.blocked_until)
      and (
        (private.hype_valid_cpf_v49(p_cpf) and b.cpf = private.hype_digits_v49(p_cpf))
        or (
          not private.hype_valid_cpf_v49(p_cpf)
          and b.name_key = private.hype_name_key(p_name)
        )
      )
  );
$$;

create or replace function public.public_guest_registration_context_v49()
returns table(registration_open boolean, event_id bigint, event_name text, event_date date)
language sql
stable
security definer
set search_path = ''
as $$
  select
    (s.registration_open is true and e.id is not null and e.active is true),
    e.id,
    e.name,
    e.event_date
  from public.public_guest_registration_settings_v49 s
  left join public.events e on e.id = s.event_id
  where s.id is true;
$$;

create or replace function public.public_guest_registration_submit_v49(
  p_name text,
  p_cpf text,
  p_phone text,
  p_gender text,
  p_website text default ''
)
returns table(ok boolean, message text, list_id bigint, event_name text, status text)
language plpgsql
security definer
set search_path = ''
as $$
declare
  v_name text := regexp_replace(trim(coalesce(p_name,'')), '\s+', ' ', 'g');
  v_name_key text;
  v_cpf text := private.hype_digits_v49(p_cpf);
  v_phone text := private.hype_normalize_phone_v49(p_phone);
  v_event public.events%rowtype;
  v_open boolean := false;
  v_existing public.guest_list_simple_v406%rowtype;
  v_id bigint;
begin
  if trim(coalesce(p_website,'')) <> '' then
    return query select false, 'Nao foi possivel concluir o cadastro.', null::bigint, null::text, 'Recusado'::text;
    return;
  end if;
  if length(v_name) < 2 or length(v_name) > 160 then raise exception 'Informe o nome completo'; end if;
  if not private.hype_valid_cpf_v49(v_cpf) then raise exception 'CPF invalido'; end if;
  if length(v_phone) not in (10,11) then raise exception 'WhatsApp invalido'; end if;
  if p_gender not in ('Feminino','Masculino') then raise exception 'Selecione Feminino ou Masculino'; end if;
  v_name_key := private.hype_name_key(v_name);

  select s.registration_open into v_open
  from public.public_guest_registration_settings_v49 s
  where s.id is true;

  select e.* into v_event
  from public.events e
  where e.id = (select s.event_id from public.public_guest_registration_settings_v49 s where s.id is true);

  if not coalesce(v_open,false) or v_event.id is null or not v_event.active then
    return query select false, 'Cadastros indisponiveis no momento.', null::bigint, coalesce(v_event.name,''), 'Fechado'::text;
    return;
  end if;
  if private.hype_person_is_blocked_v49(v_cpf, v_name) then
    return query select false, 'Cadastro nao permitido. Procure a equipe HYPE.', null::bigint, v_event.name, 'Recusado'::text;
    return;
  end if;

  perform pg_advisory_xact_lock(hashtextextended('hype-lista:' || v_event.id::text || ':' || v_cpf, 0));

  select g.* into v_existing
  from public.guest_list_simple_v406 g
  where g.event_id = v_event.id and g.cpf = v_cpf and g.status <> 'Cancelado'
  limit 1;
  if found then
    return query select true, 'Voce ja esta na lista.', null::bigint, v_event.name, v_existing.status;
    return;
  end if;

  if exists (
    select 1 from public.tickets t
    where t.event_id = v_event.id and t.cpf = v_cpf and t.payment_status in ('Pendente','Pago')
  ) then
    return query select true, 'Seu cadastro para este evento ja esta confirmado.', null::bigint, v_event.name, 'Confirmado'::text;
    return;
  end if;

  insert into public.guest_list_simple_v406(
    event_id, name, name_key, cpf, phone, gender, source, status, added_by
  ) values (
    v_event.id, v_name, v_name_key, v_cpf, v_phone, p_gender, 'Publico', 'Liberado', 'publico'
  ) returning id into v_id;

  return query select true, 'Nome confirmado na lista.', v_id, v_event.name, 'Liberado'::text;
exception
  when unique_violation then
    return query select true, 'Voce ja esta na lista.', null::bigint, coalesce(v_event.name,''), 'Liberado'::text;
end;
$$;

create or replace function public.staff_guest_registration_settings_v49(p_username text, p_password text)
returns table(event_id bigint, event_name text, registration_open boolean, updated_at timestamptz)
language plpgsql
security definer
set search_path = ''
as $$
begin
  perform private.hype_require_staff(p_username,p_password,array['admin']);
  return query
  select s.event_id, coalesce(e.name,''), s.registration_open, s.updated_at
  from public.public_guest_registration_settings_v49 s
  left join public.events e on e.id = s.event_id
  where s.id is true;
end;
$$;

create or replace function public.staff_set_guest_registration_v49(
  p_username text,
  p_password text,
  p_event_id bigint,
  p_registration_open boolean
)
returns table(event_id bigint, event_name text, registration_open boolean, updated_at timestamptz)
language plpgsql
security definer
set search_path = ''
as $$
declare
  v_staff public.staff_users%rowtype;
begin
  v_staff := private.hype_require_staff(p_username,p_password,array['admin']);
  if coalesce(p_registration_open,false) and not exists (
    select 1 from public.events e where e.id = p_event_id and e.active is true
  ) then
    raise exception 'Selecione um evento ativo antes de liberar a lista';
  end if;

  update public.public_guest_registration_settings_v49 s
  set event_id = p_event_id,
      registration_open = coalesce(p_registration_open,false),
      updated_by = v_staff.username
  where s.id is true;

  return query
  select s.event_id, coalesce(e.name,''), s.registration_open, s.updated_at
  from public.public_guest_registration_settings_v49 s
  left join public.events e on e.id = s.event_id
  where s.id is true;
end;
$$;

create or replace function private.hype_promoter_code_base_v49(p_name text)
returns text
language sql
immutable
set search_path = ''
as $$
  select left(trim(both '-' from regexp_replace(
    upper(translate(trim(coalesce(p_name,'')),
      'ÁÀÂÃÄÉÈÊËÍÌÎÏÓÒÔÕÖÚÙÛÜÇÑ',
      'AAAAAEEEEIIIIOOOOOUUUUCN')),
    '[^A-Z0-9]+', '-', 'g'
  )), 40);
$$;

create or replace function public.public_promoter_registration_submit_v49(
  p_name text,
  p_cpf text,
  p_phone text,
  p_website text default ''
)
returns table(ok boolean, message text, promoter_code text, sales_url text)
language plpgsql
security definer
set search_path = ''
as $$
declare
  v_name text := regexp_replace(trim(coalesce(p_name,'')), '\s+', ' ', 'g');
  v_cpf text := private.hype_digits_v49(p_cpf);
  v_phone text := private.hype_normalize_phone_v49(p_phone);
  v_existing public.promoters_global_v16%rowtype;
  v_base text;
  v_code text;
  v_suffix integer := 1;
begin
  if trim(coalesce(p_website,'')) <> '' then
    return query select false, 'Nao foi possivel concluir o cadastro.', null::text, null::text;
    return;
  end if;
  if length(v_name) < 2 or length(v_name) > 120 then raise exception 'Informe o nome completo'; end if;
  if not private.hype_valid_cpf_v49(v_cpf) then raise exception 'CPF invalido'; end if;
  if length(v_phone) not in (10,11) then raise exception 'WhatsApp invalido'; end if;
  if private.hype_person_is_blocked_v49(v_cpf, v_name) then
    return query select false, 'Cadastro indisponivel. Procure a equipe HYPE.', null::text, null::text;
    return;
  end if;

  perform pg_advisory_xact_lock(hashtextextended('hype-promoter-cpf:' || v_cpf, 0));
  select p.* into v_existing from public.promoters_global_v16 p where p.cpf = v_cpf for update;
  if found then
    if not v_existing.active then
      return query select false, 'Cadastro indisponivel. Procure a equipe HYPE.', null::text, null::text;
    else
      return query select true, 'Seu link de vendas esta pronto.', v_existing.code,
        'https://hypeloungeclub.com.br/cliente.html?promoter=' || v_existing.code;
    end if;
    return;
  end if;

  v_base := private.hype_promoter_code_base_v49(v_name);
  if coalesce(v_base,'') = '' then v_base := 'PROMOTER'; end if;
  perform pg_advisory_xact_lock(hashtextextended('hype-promoter-code:' || v_base, 0));
  v_code := v_base;
  while exists(select 1 from public.promoters_global_v16 p where p.code = v_code) loop
    v_suffix := v_suffix + 1;
    v_code := left(v_base, 43) || '-' || v_suffix::text;
  end loop;

  insert into public.promoters_global_v16(name, code, cpf, phone, source, active)
  values(v_name, v_code, v_cpf, v_phone, 'Publico', true);

  return query select true, 'Cadastro aprovado. Seu link de vendas esta pronto.', v_code,
    'https://hypeloungeclub.com.br/cliente.html?promoter=' || v_code;
end;
$$;

revoke all on function public.public_guest_registration_context_v49() from public, anon, authenticated;
revoke all on function public.public_guest_registration_submit_v49(text,text,text,text,text) from public, anon, authenticated;
revoke all on function public.public_promoter_registration_submit_v49(text,text,text,text) from public, anon, authenticated;
revoke all on function public.staff_guest_registration_settings_v49(text,text) from public, anon, authenticated;
revoke all on function public.staff_set_guest_registration_v49(text,text,bigint,boolean) from public, anon, authenticated;

grant execute on function public.public_guest_registration_context_v49() to anon, authenticated;
grant execute on function public.public_guest_registration_submit_v49(text,text,text,text,text) to anon, authenticated;
grant execute on function public.public_promoter_registration_submit_v49(text,text,text,text) to anon, authenticated;
grant execute on function public.staff_guest_registration_settings_v49(text,text) to anon, authenticated;
grant execute on function public.staff_set_guest_registration_v49(text,text,bigint,boolean) to anon, authenticated;
