-- Hype Ingressos: portaria, readers, check-in, chat, and realtime.

alter table public.tickets
  add column document_checked boolean not null default false,
  add column document_checked_at timestamptz,
  add column document_checked_by text,
  add column temporary_exit boolean not null default false,
  add column reentry_authorized boolean not null default false,
  add column reentry_authorized_by text,
  add column reentry_count integer not null default 0 check (reentry_count >= 0),
  add column last_entry_device text,
  add column sale_origin text not null default 'site' check (sale_origin in ('site','portaria','admin'));

create table public.portaria_devices_v18 (
  id uuid primary key default extensions.gen_random_uuid(),
  device_key_hash bytea not null unique,
  request_code text not null unique,
  label text not null default 'Computador da Portaria',
  active boolean not null default false,
  approved_at timestamptz,
  approved_by text,
  revoked_at timestamptz,
  last_seen timestamptz,
  created_at timestamptz not null default now()
);

alter table public.tickets
  add column door_device_id uuid references public.portaria_devices_v18(id) on delete set null;

create table public.portaria_readers_v19 (
  id uuid primary key default extensions.gen_random_uuid(),
  device_id uuid not null references public.portaria_devices_v18(id) on delete cascade,
  reader_secret_hash bytea not null unique,
  reader_label text not null default 'Celular leitor',
  active boolean not null default true,
  connected_at timestamptz not null default now(),
  last_scan_at timestamptz,
  expires_at timestamptz,
  revoked_at timestamptz
);

create table public.portaria_pairings_v18 (
  id uuid primary key default extensions.gen_random_uuid(),
  device_id uuid not null references public.portaria_devices_v18(id) on delete cascade,
  pair_token_hash bytea not null unique,
  reader_id uuid references public.portaria_readers_v19(id) on delete set null,
  reader_label text,
  expires_at timestamptz not null,
  claimed_at timestamptz,
  active boolean not null default true,
  created_at timestamptz not null default now()
);

create table public.portaria_reader_links_v20 (
  id uuid primary key default extensions.gen_random_uuid(),
  device_id uuid not null references public.portaria_devices_v18(id) on delete cascade,
  link_token_hash bytea not null unique,
  reader_label text not null default 'Celular leitor',
  expires_at timestamptz not null,
  used_at timestamptz,
  reader_id uuid references public.portaria_readers_v19(id) on delete set null,
  revoked_at timestamptz,
  created_at timestamptz not null default now()
);

create table public.portaria_scan_queue_v18 (
  id bigint generated by default as identity primary key,
  device_id uuid not null references public.portaria_devices_v18(id) on delete cascade,
  reader_id uuid references public.portaria_readers_v19(id) on delete set null,
  raw_code text not null check (length(raw_code) between 1 and 500),
  created_at timestamptz not null default now(),
  consumed_at timestamptz
);

create table public.portaria_logs_v18 (
  id bigint generated by default as identity primary key,
  device_id uuid references public.portaria_devices_v18(id) on delete set null,
  ticket_id bigint references public.tickets(id) on delete set null,
  action text not null,
  metadata jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now()
);

create table public.internal_chat_v41 (
  id bigint generated by default as identity primary key,
  sender_role text not null check (sender_role in ('admin','portaria')),
  sender_name text not null check (length(sender_name) between 1 and 80),
  message_text text not null check (length(message_text) between 1 and 1200),
  created_at timestamptz not null default now()
);

create table public.internal_chat_state_v41 (
  singleton boolean primary key default true check (singleton),
  last_cleared_at timestamptz,
  last_cleared_by text
);

insert into public.internal_chat_state_v41(singleton) values(true);

create index hype_portaria_devices_active_idx on public.portaria_devices_v18(active,created_at desc);
create index hype_portaria_readers_device_idx on public.portaria_readers_v19(device_id,active,connected_at desc);
create index hype_portaria_pairings_device_idx on public.portaria_pairings_v18(device_id,active,created_at desc);
create index hype_portaria_links_device_idx on public.portaria_reader_links_v20(device_id,created_at desc);
create index hype_portaria_queue_pull_idx on public.portaria_scan_queue_v18(device_id,consumed_at,created_at,id);
create index hype_portaria_queue_reader_idx on public.portaria_scan_queue_v18(reader_id);
create index hype_portaria_logs_ticket_idx on public.portaria_logs_v18(ticket_id,created_at desc);
create index hype_portaria_logs_device_idx on public.portaria_logs_v18(device_id);
create index hype_portaria_pairings_reader_idx on public.portaria_pairings_v18(reader_id);
create index hype_portaria_links_reader_idx on public.portaria_reader_links_v20(reader_id);
create index hype_tickets_door_device_idx on public.tickets(door_device_id);
create index hype_tickets_sale_origin_idx on public.tickets(event_id,sale_origin,payment_status,purchased_at desc);

alter table public.portaria_devices_v18 enable row level security;
alter table public.portaria_readers_v19 enable row level security;
alter table public.portaria_pairings_v18 enable row level security;
alter table public.portaria_reader_links_v20 enable row level security;
alter table public.portaria_scan_queue_v18 enable row level security;
alter table public.portaria_logs_v18 enable row level security;
alter table public.internal_chat_v41 enable row level security;
alter table public.internal_chat_state_v41 enable row level security;

revoke all on all tables in schema public from anon, authenticated;
revoke all on all sequences in schema public from anon, authenticated;

create or replace function private.hype_secret_hash(p_secret text)
returns bytea language sql immutable set search_path='' as $$
  select extensions.digest(convert_to(trim(coalesce(p_secret,'')),'utf8'),'sha256');
$$;

create or replace function private.hype_device_id(p_device_key text)
returns uuid language sql security definer stable set search_path='' as $$
  select d.id from public.portaria_devices_v18 d
  where length(trim(coalesce(p_device_key,'')))>=20
    and d.device_key_hash=extensions.digest(convert_to(p_device_key,'utf8'),'sha256')
    and d.active and d.revoked_at is null
  limit 1;
$$;

create or replace function private.hype_device_authorized(p_device_key text)
returns boolean language sql security definer stable set search_path='' as $$
  select exists(
    select 1 from public.portaria_devices_v18 d
    where d.device_key_hash=extensions.digest(convert_to(p_device_key,'utf8'),'sha256')
      and d.active and d.revoked_at is null
  );
$$;

create or replace function private.hype_reader_id(p_reader_secret text)
returns uuid language sql security definer stable set search_path='' as $$
  select r.id from public.portaria_readers_v19 r
  join public.portaria_devices_v18 d on d.id=r.device_id
  where length(trim(coalesce(p_reader_secret,'')))>=20
    and r.reader_secret_hash=extensions.digest(convert_to(p_reader_secret,'utf8'),'sha256')
    and r.active and r.revoked_at is null
    and (r.expires_at is null or r.expires_at>clock_timestamp())
    and d.active and d.revoked_at is null
  limit 1;
$$;

create or replace function private.hype_portaria_log(
  p_device_id uuid,p_ticket_id bigint,p_action text,p_metadata jsonb default '{}'::jsonb
) returns void language sql security definer set search_path='' as $$
  insert into public.portaria_logs_v18(device_id,ticket_id,action,metadata)
  values(p_device_id,p_ticket_id,p_action,coalesce(p_metadata,'{}'::jsonb));
$$;

create or replace function public.portaria_device_request_v18(p_device_key text,p_label text default null)
returns table(device_id uuid,request_code text,active boolean,label text,approved_at timestamptz,created_at timestamptz)
language plpgsql security definer set search_path='' as $$
declare v_hash bytea; v_row public.portaria_devices_v18%rowtype; v_code text;
begin
  if length(trim(coalesce(p_device_key,'')))<20 then raise exception 'Chave do dispositivo inválida'; end if;
  v_hash:=extensions.digest(convert_to(p_device_key,'utf8'),'sha256');
  select d.* into v_row from public.portaria_devices_v18 d where d.device_key_hash=v_hash;
  if found then
    if trim(coalesce(p_label,''))<>'' then
      update public.portaria_devices_v18 d set label=left(trim(p_label),80) where d.id=v_row.id returning * into v_row;
    end if;
    return query select v_row.id,v_row.request_code,(v_row.active and v_row.revoked_at is null),v_row.label,v_row.approved_at,v_row.created_at;
    return;
  end if;
  loop
    v_code:=upper(substr(replace(extensions.gen_random_uuid()::text,'-',''),1,8));
    exit when not exists(select 1 from public.portaria_devices_v18 d where d.request_code=v_code);
  end loop;
  insert into public.portaria_devices_v18(device_key_hash,request_code,label)
  values(v_hash,v_code,left(coalesce(nullif(trim(p_label),''),'Computador da Portaria'),80)) returning * into v_row;
  return query select v_row.id,v_row.request_code,false,v_row.label,v_row.approved_at,v_row.created_at;
end; $$;

create or replace function public.portaria_device_status_v18(p_device_key text)
returns table(device_id uuid,request_code text,active boolean,label text,approved_at timestamptz,revoked_at timestamptz,last_seen timestamptz)
language plpgsql security definer set search_path='' as $$
declare v_hash bytea:=extensions.digest(convert_to(coalesce(p_device_key,''),'utf8'),'sha256'); v_row public.portaria_devices_v18%rowtype;
begin
  select d.* into v_row from public.portaria_devices_v18 d where d.device_key_hash=v_hash;
  if not found then return; end if;
  if v_row.active and v_row.revoked_at is null then
    update public.portaria_devices_v18 d set last_seen=now() where d.id=v_row.id returning * into v_row;
  end if;
  return query select v_row.id,v_row.request_code,(v_row.active and v_row.revoked_at is null),v_row.label,v_row.approved_at,v_row.revoked_at,v_row.last_seen;
end; $$;

create or replace function public.staff_list_portaria_devices_v18(p_username text,p_password text)
returns table(device_id uuid,request_code text,label text,active boolean,approved_at timestamptz,approved_by text,revoked_at timestamptz,last_seen timestamptz,created_at timestamptz)
language plpgsql security definer set search_path='' as $$
begin
  perform private.hype_require_staff(p_username,p_password,array['admin']);
  return query select d.id,d.request_code,d.label,(d.active and d.revoked_at is null),d.approved_at,d.approved_by,d.revoked_at,d.last_seen,d.created_at
  from public.portaria_devices_v18 d order by (d.active and d.revoked_at is null) desc,d.created_at desc;
end; $$;

create or replace function public.staff_approve_portaria_device_v18(p_username text,p_password text,p_request_code text,p_label text default null)
returns boolean language plpgsql security definer set search_path='' as $$
declare v_staff public.staff_users%rowtype;
begin
  v_staff:=private.hype_require_staff(p_username,p_password,array['admin']);
  update public.portaria_devices_v18 d set active=true,approved_at=now(),approved_by=v_staff.username,revoked_at=null,
    label=case when trim(coalesce(p_label,''))<>'' then left(trim(p_label),80) else d.label end
  where upper(d.request_code)=upper(trim(p_request_code));
  if not found then raise exception 'Código do computador não encontrado'; end if;
  return true;
end; $$;

create or replace function public.staff_revoke_portaria_device_v18(p_username text,p_password text,p_device_id uuid)
returns boolean language plpgsql security definer set search_path='' as $$
begin
  perform private.hype_require_staff(p_username,p_password,array['admin']);
  update public.portaria_devices_v18 d set active=false,revoked_at=now() where d.id=p_device_id;
  if not found then raise exception 'Dispositivo não encontrado'; end if;
  update public.portaria_readers_v19 r set active=false,revoked_at=now() where r.device_id=p_device_id and r.active;
  update public.portaria_pairings_v18 p set active=false where p.device_id=p_device_id and p.active;
  update public.portaria_reader_links_v20 l set revoked_at=now() where l.device_id=p_device_id and l.revoked_at is null;
  return true;
end; $$;

create or replace function public.portaria_create_pair_v18(p_device_key text,p_pair_token text)
returns table(pairing_id uuid,expires_at timestamptz)
language plpgsql security definer set search_path='' as $$
declare v_device uuid; v_row public.portaria_pairings_v18%rowtype;
begin
  v_device:=private.hype_device_id(p_device_key);
  if v_device is null then raise exception 'Computador não autorizado'; end if;
  if length(trim(coalesce(p_pair_token,'')))<20 then raise exception 'Token de pareamento inválido'; end if;
  update public.portaria_pairings_v18 p set active=false where p.device_id=v_device and p.claimed_at is null and p.active;
  insert into public.portaria_pairings_v18(device_id,pair_token_hash,expires_at)
  values(v_device,extensions.digest(convert_to(p_pair_token,'utf8'),'sha256'),now()+interval '3 minutes') returning * into v_row;
  return query select v_row.id,v_row.expires_at;
end; $$;

create or replace function public.portaria_create_pair_v19(p_device_key text,p_pair_token text)
returns table(pairing_id uuid,expires_at timestamptz,pairing_code text)
language plpgsql security definer set search_path='' as $$
declare v_pair record;
begin
  select * into v_pair from public.portaria_create_pair_v18(p_device_key,p_pair_token);
  return query select v_pair.pairing_id,v_pair.expires_at,upper(substr(replace(v_pair.pairing_id::text,'-',''),1,6));
end; $$;

create or replace function private.hype_claim_pair(
  p_pair_token text,p_reader_secret text,p_reader_label text,p_expires interval
) returns public.portaria_readers_v19
language plpgsql security definer set search_path='' as $$
declare v_pair public.portaria_pairings_v18%rowtype; v_device public.portaria_devices_v18%rowtype; v_reader public.portaria_readers_v19%rowtype;
begin
  if length(trim(coalesce(p_reader_secret,'')))<20 then raise exception 'Leitor inválido'; end if;
  select p.* into v_pair from public.portaria_pairings_v18 p
  where p.pair_token_hash=extensions.digest(convert_to(p_pair_token,'utf8'),'sha256')
    and p.active and p.claimed_at is null and p.expires_at>clock_timestamp()
  for update limit 1;
  if not found then raise exception 'QR de conexão expirado ou já utilizado'; end if;
  select d.* into v_device from public.portaria_devices_v18 d where d.id=v_pair.device_id;
  if not found or not v_device.active or v_device.revoked_at is not null then raise exception 'Computador não autorizado'; end if;
  insert into public.portaria_readers_v19(device_id,reader_secret_hash,reader_label,expires_at)
  values(v_pair.device_id,extensions.digest(convert_to(p_reader_secret,'utf8'),'sha256'),
    left(coalesce(nullif(trim(p_reader_label),''),nullif(trim(v_pair.reader_label),''),'Celular leitor'),50),now()+p_expires)
  returning * into v_reader;
  update public.portaria_pairings_v18 p set claimed_at=now(),reader_id=v_reader.id,active=false where p.id=v_pair.id;
  return v_reader;
end; $$;

create or replace function public.portaria_claim_pair_v18(p_pair_token text,p_reader_secret text)
returns table(ok boolean,message text,reader_expires_at timestamptz)
language plpgsql security definer set search_path='' as $$
declare v_reader public.portaria_readers_v19%rowtype;
begin
  begin
    v_reader:=private.hype_claim_pair(p_pair_token,p_reader_secret,null,interval '12 hours');
    return query select true,'Leitor conectado'::text,v_reader.expires_at;
  exception when others then
    return query select false,sqlerrm,null::timestamptz;
  end;
end; $$;

create or replace function public.portaria_claim_pair_v19(p_pair_token text,p_reader_secret text,p_reader_label text default null)
returns table(ok boolean,message text,reader_id uuid,reader_label text,reader_expires_at timestamptz)
language plpgsql security definer set search_path='' as $$
declare v_reader public.portaria_readers_v19%rowtype;
begin
  begin
    v_reader:=private.hype_claim_pair(p_pair_token,p_reader_secret,p_reader_label,interval '12 hours');
    return query select true,'Leitor conectado'::text,v_reader.id,v_reader.reader_label,v_reader.expires_at;
  exception when others then
    return query select false,sqlerrm,null::uuid,null::text,null::timestamptz;
  end;
end; $$;

create or replace function public.portaria_device_create_reader_link_v20(p_device_key text,p_link_token text,p_reader_label text default null)
returns table(reader_id uuid,reader_label text,link_expires_at timestamptz)
language plpgsql security definer set search_path='' as $$
declare v_device uuid; v_link public.portaria_reader_links_v20%rowtype;
begin
  v_device:=private.hype_device_id(p_device_key);
  if v_device is null then raise exception 'Computador não autorizado'; end if;
  if length(trim(coalesce(p_link_token,'')))<40 then raise exception 'Token do link inválido'; end if;
  insert into public.portaria_reader_links_v20(device_id,link_token_hash,reader_label,expires_at)
  values(v_device,extensions.digest(convert_to(p_link_token,'utf8'),'sha256'),left(coalesce(nullif(trim(p_reader_label),''),'Celular leitor'),50),now()+interval '15 minutes')
  returning * into v_link;
  return query select v_link.id,v_link.reader_label,v_link.expires_at;
end; $$;

create or replace function public.portaria_claim_reader_link_v20(p_link_token text,p_reader_secret text,p_reader_label text default null)
returns table(ok boolean,message text,reader_id uuid,reader_label text,reader_expires_at timestamptz)
language plpgsql security definer set search_path='' as $$
declare v_link public.portaria_reader_links_v20%rowtype; v_device public.portaria_devices_v18%rowtype; v_reader public.portaria_readers_v19%rowtype;
begin
  if length(trim(coalesce(p_reader_secret,'')))<20 then
    return query select false,'Leitor inválido'::text,null::uuid,null::text,null::timestamptz; return;
  end if;
  select l.* into v_link from public.portaria_reader_links_v20 l
  where l.link_token_hash=extensions.digest(convert_to(p_link_token,'utf8'),'sha256')
    and l.used_at is null and l.revoked_at is null and l.expires_at>clock_timestamp()
  for update limit 1;
  if not found then
    return query select false,'Link expirado, já utilizado ou bloqueado'::text,null::uuid,null::text,null::timestamptz; return;
  end if;
  select d.* into v_device from public.portaria_devices_v18 d where d.id=v_link.device_id;
  if not found or not v_device.active or v_device.revoked_at is not null then
    return query select false,'Computador da Portaria não autorizado'::text,null::uuid,null::text,null::timestamptz; return;
  end if;
  insert into public.portaria_readers_v19(device_id,reader_secret_hash,reader_label,expires_at)
  values(v_link.device_id,extensions.digest(convert_to(p_reader_secret,'utf8'),'sha256'),
    left(coalesce(nullif(trim(p_reader_label),''),v_link.reader_label,'Celular leitor'),50),null)
  returning * into v_reader;
  update public.portaria_reader_links_v20 l set used_at=now(),reader_id=v_reader.id where l.id=v_link.id;
  return query select true,'Leitor autorizado'::text,v_reader.id,v_reader.reader_label,v_reader.expires_at;
end; $$;

create or replace function private.hype_submit_reader_scan(p_reader_secret text,p_raw_code text)
returns public.portaria_scan_queue_v18
language plpgsql security definer set search_path='' as $$
declare v_reader public.portaria_readers_v19%rowtype; v_queue public.portaria_scan_queue_v18%rowtype; v_code text:=left(trim(coalesce(p_raw_code,'')),500);
begin
  if v_code='' then raise exception 'QR vazio'; end if;
  select r.* into v_reader from public.portaria_readers_v19 r
  join public.portaria_devices_v18 d on d.id=r.device_id
  where r.reader_secret_hash=extensions.digest(convert_to(p_reader_secret,'utf8'),'sha256')
    and r.active and r.revoked_at is null and (r.expires_at is null or r.expires_at>clock_timestamp())
    and d.active and d.revoked_at is null
  for update of r limit 1;
  if not found then raise exception 'Acesso do leitor encerrado'; end if;
  insert into public.portaria_scan_queue_v18(device_id,reader_id,raw_code)
  values(v_reader.device_id,v_reader.id,v_code) returning * into v_queue;
  update public.portaria_readers_v19 r set last_scan_at=now() where r.id=v_reader.id;
  return v_queue;
end; $$;

create or replace function public.portaria_reader_submit_v18(p_reader_secret text,p_raw_code text)
returns boolean language plpgsql security definer set search_path='' as $$
begin perform private.hype_submit_reader_scan(p_reader_secret,p_raw_code); return true; end; $$;

create or replace function public.portaria_reader_submit_v19(p_reader_secret text,p_raw_code text)
returns boolean language sql security definer set search_path='' as $$
  select public.portaria_reader_submit_v18(p_reader_secret,p_raw_code);
$$;

create or replace function public.portaria_reader_submit_v31(p_reader_secret text,p_raw_code text)
returns table(ok boolean,message text,scan_id bigint,created_at timestamptz)
language plpgsql security definer set search_path='' as $$
declare v_queue public.portaria_scan_queue_v18%rowtype;
begin
  v_queue:=private.hype_submit_reader_scan(p_reader_secret,p_raw_code);
  return query select true,'QR enviado'::text,v_queue.id,v_queue.created_at;
end; $$;

create or replace function public.portaria_reader_status_v25(p_reader_secret text)
returns table(active boolean,message text,reader_id uuid,reader_label text,device_label text,connected_at timestamptz,last_scan_at timestamptz,expires_at timestamptz)
language plpgsql security definer set search_path='' as $$
declare v_hash bytea:=extensions.digest(convert_to(coalesce(p_reader_secret,''),'utf8'),'sha256');
begin
  return query
  select (r.active and r.revoked_at is null and (r.expires_at is null or r.expires_at>clock_timestamp()) and d.active and d.revoked_at is null),
    case when r.active and r.revoked_at is null and d.active and d.revoked_at is null and (r.expires_at is null or r.expires_at>clock_timestamp()) then 'Leitor ativo' else 'Acesso encerrado pelo Admin' end,
    r.id,r.reader_label,d.label,r.connected_at,r.last_scan_at,r.expires_at
  from public.portaria_readers_v19 r join public.portaria_devices_v18 d on d.id=r.device_id
  where r.reader_secret_hash=v_hash limit 1;
  if not found then
    return query select false,'Leitor não autorizado'::text,null::uuid,null::text,null::text,null::timestamptz,null::timestamptz,null::timestamptz;
  end if;
end; $$;

create or replace function public.portaria_device_list_readers_v19(p_device_key text)
returns table(reader_id uuid,reader_label text,connected_at timestamptz,last_scan_at timestamptz,expires_at timestamptz,active boolean)
language plpgsql security definer set search_path='' as $$
declare v_device uuid:=private.hype_device_id(p_device_key);
begin
  if v_device is null then raise exception 'Computador não autorizado'; end if;
  return query select r.id,r.reader_label,r.connected_at,r.last_scan_at,r.expires_at,
    (r.active and r.revoked_at is null and (r.expires_at is null or r.expires_at>clock_timestamp()))
  from public.portaria_readers_v19 r where r.device_id=v_device order by r.active desc,r.connected_at desc;
end; $$;

create or replace function public.portaria_device_disconnect_reader_v19(p_device_key text,p_reader_id uuid)
returns boolean language plpgsql security definer set search_path='' as $$
declare v_device uuid:=private.hype_device_id(p_device_key);
begin
  if v_device is null then raise exception 'Computador não autorizado'; end if;
  update public.portaria_readers_v19 r set active=false,revoked_at=now() where r.id=p_reader_id and r.device_id=v_device;
  if not found then raise exception 'Leitor não encontrado'; end if;
  return true;
end; $$;

create or replace function public.portaria_device_end_readers_v18(p_device_key text)
returns boolean language plpgsql security definer set search_path='' as $$
declare v_device uuid:=private.hype_device_id(p_device_key);
begin
  if v_device is null then raise exception 'Computador não autorizado'; end if;
  update public.portaria_readers_v19 r set active=false,revoked_at=now() where r.device_id=v_device and r.active;
  update public.portaria_pairings_v18 p set active=false where p.device_id=v_device and p.active;
  update public.portaria_reader_links_v20 l set revoked_at=now() where l.device_id=v_device and l.used_at is null and l.revoked_at is null;
  return true;
end; $$;

create or replace function private.hype_pull_scan(p_device_key text)
returns public.portaria_scan_queue_v18
language plpgsql security definer set search_path='' as $$
declare v_device uuid:=private.hype_device_id(p_device_key); v_queue public.portaria_scan_queue_v18%rowtype;
begin
  if v_device is null then raise exception 'Computador não autorizado'; end if;
  update public.portaria_devices_v18 d set last_seen=now() where d.id=v_device;
  select q.* into v_queue from public.portaria_scan_queue_v18 q
  where q.device_id=v_device and q.consumed_at is null
  order by q.created_at,q.id for update skip locked limit 1;
  if not found then return null; end if;
  update public.portaria_scan_queue_v18 q set consumed_at=now() where q.id=v_queue.id;
  return v_queue;
end; $$;

create or replace function public.portaria_device_pull_scan_v18(p_device_key text)
returns table(scan_id bigint,raw_code text,created_at timestamptz)
language plpgsql security definer set search_path='' as $$
declare v_queue public.portaria_scan_queue_v18%rowtype;
begin
  v_queue:=private.hype_pull_scan(p_device_key);
  if v_queue.id is not null then return query select v_queue.id,v_queue.raw_code,v_queue.created_at; end if;
end; $$;

create or replace function public.portaria_device_pull_scan_v29(p_device_key text,p_event_id bigint)
returns table(scan_id bigint,raw_code text,created_at timestamptz)
language sql security definer set search_path='' as $$
  select * from public.portaria_device_pull_scan_v18(p_device_key);
$$;

create or replace function public.portaria_device_pull_scan_v31(p_device_key text)
returns table(scan_id bigint,raw_code text,created_at timestamptz)
language sql security definer set search_path='' as $$
  select * from public.portaria_device_pull_scan_v18(p_device_key);
$$;

create or replace function public.portaria_current_event_v32(p_device_key text)
returns table(event_id bigint,event_name text,event_date date,status text)
language plpgsql security definer set search_path='' as $$
declare v_device uuid:=private.hype_device_id(p_device_key); v_logical_date date;
begin
  if v_device is null then raise exception 'Computador não autorizado'; end if;
  v_logical_date:=case when (clock_timestamp() at time zone 'America/Sao_Paulo')::time<time '08:00'
    then (clock_timestamp() at time zone 'America/Sao_Paulo')::date-1
    else (clock_timestamp() at time zone 'America/Sao_Paulo')::date end;
  return query
  select e.id,e.name,e.event_date,case when e.event_date=v_logical_date then 'ATUAL' else 'PRÓXIMO' end
  from public.events e where e.active and e.event_date>=v_logical_date
  order by case when e.event_date=v_logical_date then 0 else 1 end,e.event_date,e.sort_order,e.id limit 1;
end; $$;

create or replace function public.portaria_device_lookup_v18(p_device_key text,p_code text)
returns table(
  ticket_id bigint,event_id bigint,event_name text,event_date date,ticket_code text,qr_token text,
  customer_name text,phone text,cpf text,gender text,lot_name text,sector text,payment_status text,
  entry_status text,entry_at timestamptz,document_checked boolean,temporary_exit boolean,
  reentry_authorized boolean,reentry_count integer
)
language plpgsql security definer set search_path='' as $$
declare v_device uuid:=private.hype_device_id(p_device_key); v_code text:=regexp_replace(trim(coalesce(p_code,'')),'^#','','');
begin
  if v_device is null then raise exception 'Computador não autorizado'; end if;
  return query select t.id,t.event_id,e.name,e.event_date,t.ticket_code,t.qr_token,t.customer_name,t.phone,t.cpf,t.gender,
    l.name,l.sector,t.payment_status,t.entry_status,t.entry_at,t.document_checked,t.temporary_exit,t.reentry_authorized,t.reentry_count
  from public.tickets t join public.ticket_lots l on l.id=t.lot_id join public.events e on e.id=t.event_id
  where upper(t.ticket_code)=upper(v_code) or t.qr_token=v_code order by t.id desc limit 1;
end; $$;

create or replace function public.portaria_device_lookup_event_v26(p_device_key text,p_event_id bigint,p_code text)
returns table(
  ticket_id bigint,event_id bigint,event_name text,event_date date,ticket_code text,qr_token text,
  customer_name text,phone text,cpf text,gender text,lot_name text,sector text,payment_status text,
  entry_status text,entry_at timestamptz,document_checked boolean,temporary_exit boolean,
  reentry_authorized boolean,reentry_count integer
)
language plpgsql security definer set search_path='' as $$
begin
  if not private.hype_device_authorized(p_device_key) then raise exception 'Computador não autorizado'; end if;
  return query select x.* from public.portaria_device_lookup_v18(p_device_key,p_code) x where x.event_id=p_event_id;
end; $$;

create or replace function public.portaria_device_qr_event_v30(p_device_key text,p_code text)
returns table(ticket_id bigint,event_id bigint,event_name text,event_date date,ticket_code text,customer_name text)
language plpgsql security definer set search_path='' as $$
begin
  if not private.hype_device_authorized(p_device_key) then raise exception 'Computador não autorizado'; end if;
  return query select x.ticket_id,x.event_id,x.event_name,x.event_date,x.ticket_code,x.customer_name
  from public.portaria_device_lookup_v18(p_device_key,p_code) x;
end; $$;

create or replace function public.portaria_device_search_v18(p_device_key text,p_event_id bigint,p_query text)
returns table(
  ticket_id bigint,event_id bigint,event_name text,event_date date,ticket_code text,qr_token text,
  customer_name text,phone text,cpf text,gender text,lot_name text,sector text,payment_status text,
  entry_status text,entry_at timestamptz,document_checked boolean,temporary_exit boolean,
  reentry_authorized boolean,reentry_count integer
)
language plpgsql security definer set search_path='' as $$
declare v_query text:=lower(trim(coalesce(p_query,'')));
begin
  if not private.hype_device_authorized(p_device_key) then raise exception 'Computador não autorizado'; end if;
  if v_query='' then return; end if;
  return query select t.id,t.event_id,e.name,e.event_date,t.ticket_code,t.qr_token,t.customer_name,t.phone,t.cpf,t.gender,
    l.name,l.sector,t.payment_status,t.entry_status,t.entry_at,t.document_checked,t.temporary_exit,t.reentry_authorized,t.reentry_count
  from public.tickets t join public.ticket_lots l on l.id=t.lot_id join public.events e on e.id=t.event_id
  where t.event_id=p_event_id and (
    lower(t.customer_name) like '%'||v_query||'%' or lower(coalesce(t.phone,'')) like '%'||v_query||'%'
    or regexp_replace(coalesce(t.cpf,''),'[^0-9]','','g') like '%'||regexp_replace(v_query,'[^0-9]','','g')||'%'
    or lower(t.ticket_code) like '%'||lower(regexp_replace(v_query,'^#','',''))||'%'
  ) order by t.purchased_at desc,t.id desc limit 25;
end; $$;

create or replace function public.portaria_device_snapshot_v18(p_device_key text,p_event_id bigint)
returns table(
  ticket_id bigint,event_id bigint,ticket_code text,qr_token text,customer_name text,phone text,cpf text,gender text,
  lot_name text,sector text,payment_status text,entry_status text,entry_at timestamptz,document_checked boolean,
  temporary_exit boolean,reentry_authorized boolean,reentry_count integer
)
language plpgsql security definer set search_path='' as $$
begin
  if not private.hype_device_authorized(p_device_key) then raise exception 'Computador não autorizado'; end if;
  return query select t.id,t.event_id,t.ticket_code,t.qr_token,t.customer_name,t.phone,t.cpf,t.gender,l.name,l.sector,
    t.payment_status,t.entry_status,t.entry_at,t.document_checked,t.temporary_exit,t.reentry_authorized,t.reentry_count
  from public.tickets t join public.ticket_lots l on l.id=t.lot_id
  where t.event_id=p_event_id and t.payment_status='Pago' order by t.id;
end; $$;

create or replace function private.hype_portaria_dashboard(p_event_id bigint)
returns jsonb language sql security definer stable set search_path='' as $$
  with paid as (
    select t.*,l.sector from public.tickets t join public.ticket_lots l on l.id=t.lot_id
    where t.event_id=p_event_id and t.payment_status='Pago'
  ), sectors as (
    select sector,count(*)::bigint paid,count(*) filter(where entry_status='Entrada utilizada')::bigint entered
    from paid group by sector
  ), recent as (
    select customer_name as name,sector,ticket_code as code,entry_at from paid
    where entry_status='Entrada utilizada' and entry_at is not null order by entry_at desc limit 12
  )
  select jsonb_build_object(
    'total_paid',(select count(*) from paid),
    'entered_count',(select count(*) from paid where entry_status='Entrada utilizada' and not temporary_exit),
    'remaining_count',(select count(*) from paid where entry_status<>'Entrada utilizada' or temporary_exit),
    'female_entered',(select count(*) from paid where entry_status='Entrada utilizada' and not temporary_exit and gender='Feminino'),
    'male_entered',(select count(*) from paid where entry_status='Entrada utilizada' and not temporary_exit and gender='Masculino'),
    'sector_stats',coalesce((select jsonb_agg(to_jsonb(s) order by sector) from sectors s),'[]'::jsonb),
    'recent',coalesce((select jsonb_agg(to_jsonb(r) order by entry_at desc) from recent r),'[]'::jsonb)
  );
$$;

create or replace function public.portaria_device_dashboard_v18(p_device_key text,p_event_id bigint)
returns jsonb language plpgsql security definer set search_path='' as $$
begin
  if not private.hype_device_authorized(p_device_key) then raise exception 'Computador não autorizado'; end if;
  return private.hype_portaria_dashboard(p_event_id);
end; $$;

create or replace function public.portaria_device_document_v18(p_device_key text,p_ticket_id bigint,p_checked boolean)
returns boolean language plpgsql security definer set search_path='' as $$
declare v_device uuid:=private.hype_device_id(p_device_key); v_label text;
begin
  if v_device is null then raise exception 'Computador não autorizado'; end if;
  select d.label into v_label from public.portaria_devices_v18 d where d.id=v_device;
  update public.tickets t set document_checked=coalesce(p_checked,false),
    document_checked_at=case when p_checked then now() else null end,
    document_checked_by=case when p_checked then v_label else null end
  where t.id=p_ticket_id;
  if not found then raise exception 'Ingresso não encontrado'; end if;
  perform private.hype_portaria_log(v_device,p_ticket_id,'DOCUMENT',jsonb_build_object('checked',coalesce(p_checked,false)));
  return true;
end; $$;

create or replace function public.portaria_device_temporary_exit_v18(p_device_key text,p_ticket_id bigint)
returns boolean language plpgsql security definer set search_path='' as $$
declare v_device uuid:=private.hype_device_id(p_device_key);
begin
  if v_device is null then raise exception 'Computador não autorizado'; end if;
  update public.tickets t set entry_status='Saída temporária',temporary_exit=true,temporary_exit_at=now(),
    reentry_authorized=false,reentry_authorized_at=null,reentry_authorized_by=null
  where t.id=p_ticket_id and t.payment_status='Pago' and t.entry_status='Entrada utilizada' and not t.temporary_exit;
  if not found then raise exception 'Somente quem já entrou pode registrar saída temporária'; end if;
  perform private.hype_portaria_log(v_device,p_ticket_id,'TEMPORARY_EXIT');
  return true;
end; $$;

create or replace function public.portaria_device_reentry_v18(p_device_key text,p_ticket_id bigint,p_authorized boolean)
returns boolean language plpgsql security definer set search_path='' as $$
declare v_device uuid:=private.hype_device_id(p_device_key); v_label text;
begin
  if v_device is null then raise exception 'Computador não autorizado'; end if;
  select d.label into v_label from public.portaria_devices_v18 d where d.id=v_device;
  update public.tickets t set entry_status=case when p_authorized then 'Reentrada autorizada' else 'Saída temporária' end,
    reentry_authorized=coalesce(p_authorized,false),
    reentry_authorized_at=case when p_authorized then now() else null end,
    reentry_authorized_by=case when p_authorized then v_label else null end
  where t.id=p_ticket_id and t.temporary_exit;
  if not found then raise exception 'Saída temporária não registrada'; end if;
  perform private.hype_portaria_log(v_device,p_ticket_id,'REENTRY_AUTH',jsonb_build_object('authorized',coalesce(p_authorized,false)));
  return true;
end; $$;

create or replace function public.portaria_device_validate_v18(p_device_key text,p_event_id bigint,p_code text)
returns table(
  ok boolean,message text,ticket_id bigint,event_id bigint,ticket_code text,customer_name text,cpf text,
  lot_name text,sector text,payment_status text,entry_status text,entry_at timestamptz,
  document_checked boolean,temporary_exit boolean,reentry_authorized boolean,reentry_count integer
)
language plpgsql security definer set search_path='' as $$
declare v_device uuid:=private.hype_device_id(p_device_key); v_ticket public.tickets%rowtype; v_lot public.ticket_lots%rowtype; v_code text:=regexp_replace(trim(coalesce(p_code,'')),'^#','','');
begin
  if v_device is null then raise exception 'Computador não autorizado'; end if;
  select t.* into v_ticket from public.tickets t
  where t.ticket_code=v_code or upper(t.ticket_code)=upper(v_code) or t.qr_token=v_code for update;
  if not found or v_ticket.event_id<>p_event_id then
    return query select false,'INGRESSO NÃO ENCONTRADO NESTE EVENTO',null::bigint,null::bigint,null::text,null::text,null::text,null::text,null::text,null::text,null::text,null::timestamptz,false,false,false,0; return;
  end if;
  select l.* into v_lot from public.ticket_lots l where l.id=v_ticket.lot_id;
  if v_ticket.payment_status<>'Pago' then
    return query select false,case when v_ticket.payment_status='Cancelado' then 'INGRESSO CANCELADO' else 'PAGAMENTO NÃO CONFIRMADO' end,
      v_ticket.id,v_ticket.event_id,v_ticket.ticket_code,v_ticket.customer_name,v_ticket.cpf,v_lot.name,v_lot.sector,v_ticket.payment_status,v_ticket.entry_status,v_ticket.entry_at,
      v_ticket.document_checked,v_ticket.temporary_exit,v_ticket.reentry_authorized,v_ticket.reentry_count; return;
  end if;
  if v_ticket.entry_status='Entrada utilizada' and not v_ticket.temporary_exit then
    return query select false,'INGRESSO JÁ UTILIZADO',v_ticket.id,v_ticket.event_id,v_ticket.ticket_code,v_ticket.customer_name,v_ticket.cpf,v_lot.name,v_lot.sector,
      v_ticket.payment_status,v_ticket.entry_status,v_ticket.entry_at,v_ticket.document_checked,v_ticket.temporary_exit,v_ticket.reentry_authorized,v_ticket.reentry_count; return;
  end if;
  if v_ticket.entry_status='Saída temporária' and not v_ticket.reentry_authorized then
    return query select false,'REENTRADA NÃO AUTORIZADA',v_ticket.id,v_ticket.event_id,v_ticket.ticket_code,v_ticket.customer_name,v_ticket.cpf,v_lot.name,v_lot.sector,
      v_ticket.payment_status,v_ticket.entry_status,v_ticket.entry_at,v_ticket.document_checked,v_ticket.temporary_exit,v_ticket.reentry_authorized,v_ticket.reentry_count; return;
  end if;
  if v_ticket.entry_status='Reentrada autorizada' or (v_ticket.temporary_exit and v_ticket.reentry_authorized) then
    update public.tickets t set entry_status='Entrada utilizada',temporary_exit=false,reentry_authorized=false,
      reentry_count=t.reentry_count+1,last_entry_device=v_device::text where t.id=v_ticket.id returning * into v_ticket;
    perform private.hype_portaria_log(v_device,v_ticket.id,'REENTRY');
    return query select true,'REENTRADA LIBERADA',v_ticket.id,v_ticket.event_id,v_ticket.ticket_code,v_ticket.customer_name,v_ticket.cpf,v_lot.name,v_lot.sector,
      v_ticket.payment_status,v_ticket.entry_status,v_ticket.entry_at,v_ticket.document_checked,v_ticket.temporary_exit,v_ticket.reentry_authorized,v_ticket.reentry_count; return;
  end if;
  update public.tickets t set entry_status='Entrada utilizada',entry_at=now(),entry_device=v_device::text,last_entry_device=v_device::text
  where t.id=v_ticket.id returning * into v_ticket;
  perform private.hype_portaria_log(v_device,v_ticket.id,'ENTRY');
  return query select true,'ENTRADA LIBERADA',v_ticket.id,v_ticket.event_id,v_ticket.ticket_code,v_ticket.customer_name,v_ticket.cpf,v_lot.name,v_lot.sector,
    v_ticket.payment_status,v_ticket.entry_status,v_ticket.entry_at,v_ticket.document_checked,v_ticket.temporary_exit,v_ticket.reentry_authorized,v_ticket.reentry_count;
end; $$;

create or replace function public.staff_lookup_ticket_v17(p_username text,p_password text,p_code text)
returns table(
  id bigint,event_id bigint,ticket_code text,qr_token text,customer_name text,phone text,email text,cpf text,gender text,
  lot_name text,sector text,price numeric,payment_status text,entry_status text,entry_at timestamptz,
  document_checked boolean,temporary_exit boolean,reentry_authorized boolean,reentry_count integer
)
language plpgsql security definer set search_path='' as $$
declare v_code text:=regexp_replace(trim(coalesce(p_code,'')),'^#','','');
begin
  perform private.hype_require_staff(p_username,p_password,array['admin','portaria']);
  return query select t.id,t.event_id,t.ticket_code,t.qr_token,t.customer_name,t.phone,t.email,t.cpf,t.gender,l.name,l.sector,t.price,
    t.payment_status,t.entry_status,t.entry_at,t.document_checked,t.temporary_exit,t.reentry_authorized,t.reentry_count
  from public.tickets t join public.ticket_lots l on l.id=t.lot_id
  where upper(t.ticket_code)=upper(v_code) or t.qr_token=v_code limit 1;
end; $$;

create or replace function public.staff_lookup_ticket(p_username text,p_password text,p_code text)
returns table(
  id bigint,event_id bigint,ticket_code text,customer_name text,phone text,gender text,lot_name text,sector text,
  price numeric,payment_status text,entry_status text,entry_at timestamptz,event_name text,event_date date
)
language plpgsql security definer set search_path='' as $$
declare v_code text:=regexp_replace(trim(coalesce(p_code,'')),'^#','','');
begin
  perform private.hype_require_staff(p_username,p_password,array['admin','portaria']);
  return query select t.id,t.event_id,t.ticket_code,t.customer_name,t.phone,t.gender,l.name,l.sector,t.price,t.payment_status,
    t.entry_status,t.entry_at,e.name,e.event_date
  from public.tickets t join public.ticket_lots l on l.id=t.lot_id join public.events e on e.id=t.event_id
  where upper(t.ticket_code)=upper(v_code) or t.qr_token=v_code limit 1;
end; $$;

create or replace function public.staff_mark_document_v17(p_username text,p_password text,p_ticket_id bigint,p_checked boolean)
returns boolean language plpgsql security definer set search_path='' as $$
declare v_staff public.staff_users%rowtype;
begin
  v_staff:=private.hype_require_staff(p_username,p_password,array['admin','portaria']);
  update public.tickets t set document_checked=coalesce(p_checked,false),document_checked_at=case when p_checked then now() else null end,
    document_checked_by=case when p_checked then v_staff.username else null end where t.id=p_ticket_id;
  if not found then raise exception 'Ingresso não encontrado'; end if;
  perform private.hype_portaria_log(null,p_ticket_id,'DOCUMENT',jsonb_build_object('checked',coalesce(p_checked,false),'staff',v_staff.username));
  return true;
end; $$;

create or replace function public.staff_temporary_exit_v17(p_username text,p_password text,p_ticket_id bigint)
returns boolean language plpgsql security definer set search_path='' as $$
declare v_staff public.staff_users%rowtype;
begin
  v_staff:=private.hype_require_staff(p_username,p_password,array['admin','portaria']);
  update public.tickets t set entry_status='Saída temporária',temporary_exit=true,temporary_exit_at=now(),reentry_authorized=false,
    reentry_authorized_at=null,reentry_authorized_by=null where t.id=p_ticket_id and t.payment_status='Pago' and t.entry_status='Entrada utilizada';
  if not found then raise exception 'Somente quem já entrou pode registrar saída temporária'; end if;
  perform private.hype_portaria_log(null,p_ticket_id,'TEMPORARY_EXIT',jsonb_build_object('staff',v_staff.username));
  return true;
end; $$;

create or replace function public.staff_authorize_reentry_v17(p_username text,p_password text,p_ticket_id bigint,p_authorized boolean)
returns boolean language plpgsql security definer set search_path='' as $$
declare v_staff public.staff_users%rowtype;
begin
  v_staff:=private.hype_require_staff(p_username,p_password,array['admin','portaria']);
  update public.tickets t set entry_status=case when p_authorized then 'Reentrada autorizada' else 'Saída temporária' end,
    reentry_authorized=coalesce(p_authorized,false),reentry_authorized_at=case when p_authorized then now() else null end,
    reentry_authorized_by=case when p_authorized then v_staff.username else null end
  where t.id=p_ticket_id and t.temporary_exit;
  if not found then raise exception 'Saída temporária não registrada'; end if;
  perform private.hype_portaria_log(null,p_ticket_id,'REENTRY_AUTH',jsonb_build_object('authorized',coalesce(p_authorized,false),'staff',v_staff.username));
  return true;
end; $$;

create or replace function public.staff_validate_entry_v17(
  p_username text,p_password text,p_code text,p_device text default null,p_offline_sync boolean default false
) returns table(
  ok boolean,message text,id bigint,event_id bigint,ticket_code text,customer_name text,cpf text,lot_name text,sector text,
  payment_status text,entry_status text,entry_at timestamptz,document_checked boolean,temporary_exit boolean,reentry_authorized boolean,reentry_count integer
)
language plpgsql security definer set search_path='' as $$
declare v_staff public.staff_users%rowtype; v_ticket public.tickets%rowtype; v_lot public.ticket_lots%rowtype; v_code text:=regexp_replace(trim(coalesce(p_code,'')),'^#','','');
begin
  v_staff:=private.hype_require_staff(p_username,p_password,array['admin','portaria']);
  select t.* into v_ticket from public.tickets t
  where t.ticket_code=v_code or upper(t.ticket_code)=upper(v_code) or t.qr_token=v_code for update;
  if not found then
    return query select false,'INGRESSO NÃO ENCONTRADO',null::bigint,null::bigint,null::text,null::text,null::text,null::text,null::text,null::text,null::text,null::timestamptz,false,false,false,0; return;
  end if;
  select l.* into v_lot from public.ticket_lots l where l.id=v_ticket.lot_id;
  if v_ticket.payment_status<>'Pago' then
    return query select false,'PAGAMENTO NÃO CONFIRMADO',v_ticket.id,v_ticket.event_id,v_ticket.ticket_code,v_ticket.customer_name,v_ticket.cpf,v_lot.name,v_lot.sector,
      v_ticket.payment_status,v_ticket.entry_status,v_ticket.entry_at,v_ticket.document_checked,v_ticket.temporary_exit,v_ticket.reentry_authorized,v_ticket.reentry_count; return;
  end if;
  if v_ticket.entry_status='Entrada utilizada' and not v_ticket.temporary_exit then
    return query select false,'INGRESSO JÁ UTILIZADO',v_ticket.id,v_ticket.event_id,v_ticket.ticket_code,v_ticket.customer_name,v_ticket.cpf,v_lot.name,v_lot.sector,
      v_ticket.payment_status,v_ticket.entry_status,v_ticket.entry_at,v_ticket.document_checked,v_ticket.temporary_exit,v_ticket.reentry_authorized,v_ticket.reentry_count; return;
  end if;
  if v_ticket.entry_status='Saída temporária' and not v_ticket.reentry_authorized then
    return query select false,'REENTRADA NÃO AUTORIZADA',v_ticket.id,v_ticket.event_id,v_ticket.ticket_code,v_ticket.customer_name,v_ticket.cpf,v_lot.name,v_lot.sector,
      v_ticket.payment_status,v_ticket.entry_status,v_ticket.entry_at,v_ticket.document_checked,v_ticket.temporary_exit,v_ticket.reentry_authorized,v_ticket.reentry_count; return;
  end if;
  if v_ticket.entry_status='Reentrada autorizada' or (v_ticket.temporary_exit and v_ticket.reentry_authorized) then
    update public.tickets t set entry_status='Entrada utilizada',temporary_exit=false,reentry_authorized=false,reentry_count=t.reentry_count+1,
      last_entry_device=p_device where t.id=v_ticket.id returning * into v_ticket;
    perform private.hype_portaria_log(null,v_ticket.id,case when p_offline_sync then 'OFFLINE_REENTRY_SYNC' else 'REENTRY' end,jsonb_build_object('staff',v_staff.username,'device',p_device));
    return query select true,'REENTRADA LIBERADA',v_ticket.id,v_ticket.event_id,v_ticket.ticket_code,v_ticket.customer_name,v_ticket.cpf,v_lot.name,v_lot.sector,
      v_ticket.payment_status,v_ticket.entry_status,v_ticket.entry_at,v_ticket.document_checked,v_ticket.temporary_exit,v_ticket.reentry_authorized,v_ticket.reentry_count; return;
  end if;
  update public.tickets t set entry_status='Entrada utilizada',entry_at=now(),entry_by=v_staff.id,entry_device=p_device,last_entry_device=p_device
  where t.id=v_ticket.id returning * into v_ticket;
  perform private.hype_portaria_log(null,v_ticket.id,case when p_offline_sync then 'OFFLINE_ENTRY_SYNC' else 'ENTRY' end,jsonb_build_object('staff',v_staff.username,'device',p_device));
  return query select true,'ENTRADA LIBERADA',v_ticket.id,v_ticket.event_id,v_ticket.ticket_code,v_ticket.customer_name,v_ticket.cpf,v_lot.name,v_lot.sector,
    v_ticket.payment_status,v_ticket.entry_status,v_ticket.entry_at,v_ticket.document_checked,v_ticket.temporary_exit,v_ticket.reentry_authorized,v_ticket.reentry_count;
end; $$;

create or replace function public.staff_validate_entry(p_username text,p_password text,p_code text,p_device text default null)
returns table(ok boolean,message text,ticket_id bigint,ticket_code text,customer_name text,lot_name text,sector text,price numeric,payment_status text,entry_status text,entry_at timestamptz)
language plpgsql security definer set search_path='' as $$
begin
  return query select r.ok,r.message,r.id,r.ticket_code,r.customer_name,r.lot_name,r.sector,t.price,r.payment_status,r.entry_status,r.entry_at
  from public.staff_validate_entry_v17(p_username,p_password,p_code,p_device,false) r
  left join public.tickets t on t.id=r.id;
end; $$;

create or replace function public.staff_offline_snapshot_v17(p_username text,p_password text,p_event_id bigint)
returns table(id bigint,event_id bigint,ticket_code text,qr_token text,customer_name text,cpf text,lot_name text,sector text,payment_status text,entry_status text,entry_at timestamptz,document_checked boolean,temporary_exit boolean,reentry_authorized boolean,reentry_count integer)
language plpgsql security definer set search_path='' as $$
begin
  perform private.hype_require_staff(p_username,p_password,array['admin','portaria']);
  return query select t.id,t.event_id,t.ticket_code,t.qr_token,t.customer_name,t.cpf,l.name,l.sector,t.payment_status,t.entry_status,t.entry_at,
    t.document_checked,t.temporary_exit,t.reentry_authorized,t.reentry_count
  from public.tickets t join public.ticket_lots l on l.id=t.lot_id where t.event_id=p_event_id and t.payment_status='Pago';
end; $$;

create or replace function public.portaria_device_sales_context_v19(p_device_key text,p_event_id bigint)
returns table(
  event_id bigint,event_name text,event_date date,pix_key text,raffle_enabled boolean,raffle_prize text,
  lot_id bigint,lot_name text,sector text,price_female numeric,price_male numeric,quantity_available bigint,
  starts_at timestamptz,ends_at timestamptz,active boolean
)
language plpgsql security definer set search_path='' as $$
begin
  if not private.hype_device_authorized(p_device_key) then raise exception 'Computador não autorizado'; end if;
  return query select e.id,e.name,e.event_date,e.pix_key,e.raffle_enabled,e.raffle_prize,l.id,l.name,l.sector,l.price_female,l.price_male,
    case when l.quantity_total=0 then null::bigint else greatest(l.quantity_total-count(t.id) filter(where t.payment_status in('Pendente','Pago')),0)::bigint end,
    l.starts_at,l.ends_at,l.active
  from public.events e join public.ticket_lots l on l.event_id=e.id left join public.tickets t on t.lot_id=l.id
  where e.id=p_event_id and e.active group by e.id,l.id order by l.sort_order,l.id;
end; $$;

create or replace function public.portaria_device_create_door_order_v19(
  p_device_key text,p_event_id bigint,p_lot_id bigint,p_name text,p_phone text default null,p_cpf text default null,
  p_email text default null,p_gender text default 'Feminino'
) returns table(
  ticket_id bigint,event_id bigint,event_name text,ticket_code text,qr_token text,customer_name text,phone text,cpf text,email text,
  gender text,lot_id bigint,lot_name text,sector text,price numeric,payment_status text,pix_key text,raffle_enabled boolean,raffle_prize text,purchased_at timestamptz
)
language plpgsql security definer set search_path='' as $$
declare v_device uuid:=private.hype_device_id(p_device_key); v_event public.events%rowtype; v_lot public.ticket_lots%rowtype;
  v_price numeric(12,2); v_fee numeric(12,2); v_total numeric(12,2); v_status text; v_id bigint; v_code text; v_qr text; v_at timestamptz;
begin
  if v_device is null then raise exception 'Computador não autorizado'; end if;
  if length(trim(coalesce(p_name,'')))<2 then raise exception 'Informe o nome da pessoa'; end if;
  if p_gender not in('Feminino','Masculino') then raise exception 'Selecione Feminino ou Masculino'; end if;
  select l.* into v_lot from public.ticket_lots l where l.id=p_lot_id and l.event_id=p_event_id for update;
  if not found or not private.hype_lot_available_at(v_lot,clock_timestamp()) then raise exception 'Ingresso indisponível'; end if;
  select e.* into v_event from public.events e where e.id=p_event_id and e.active;
  if not found then raise exception 'Evento indisponível'; end if;
  if v_lot.quantity_total>0 and (
    select count(*) from public.tickets t where t.lot_id=v_lot.id and t.payment_status in('Pendente','Pago')
  )>=v_lot.quantity_total then raise exception 'Ingresso esgotado'; end if;
  v_price:=private.hype_effective_price(v_lot,p_gender,clock_timestamp());
  v_fee:=case when v_price=0 then 0 else 1.98 end;
  v_total:=round(v_price+v_fee,2);
  v_status:=case when v_price=0 then 'Pago' else 'Pendente' end;
  if v_price>0 and trim(coalesce(v_event.pix_key,''))='' then raise exception 'Cadastre a chave PIX do evento antes de vender na Portaria'; end if;
  loop v_code:='HYPE-'||upper(substr(md5(random()::text||clock_timestamp()::text),1,10));
    exit when not exists(select 1 from public.tickets t where t.ticket_code=v_code); end loop;
  v_qr:=extensions.gen_random_uuid()::text;
  insert into public.tickets(event_id,lot_id,customer_name,phone,email,cpf,gender,price,original_price,service_fee,ticket_code,qr_token,
    payment_status,payment_method,paid_at,sale_origin,door_device_id)
  values(v_event.id,v_lot.id,trim(p_name),nullif(trim(coalesce(p_phone,'')),''),nullif(lower(trim(coalesce(p_email,''))),''),
    nullif(regexp_replace(coalesce(p_cpf,''),'[^0-9]','','g'),''),p_gender,v_total,v_price,v_fee,v_code,v_qr,v_status,
    case when v_price=0 then 'Cortesia FREE Portaria' else 'PIX Portaria' end,case when v_price=0 then now() else null end,'portaria',v_device)
  returning tickets.id,tickets.purchased_at into v_id,v_at;
  perform private.hype_portaria_log(v_device,v_id,'DOOR_ORDER_CREATED',jsonb_build_object('lot_id',v_lot.id,'price',v_total));
  return query select v_id,v_event.id,v_event.name,v_code,v_qr,trim(p_name),nullif(trim(coalesce(p_phone,'')),''),
    nullif(regexp_replace(coalesce(p_cpf,''),'[^0-9]','','g'),''),nullif(lower(trim(coalesce(p_email,''))),''),p_gender,
    v_lot.id,v_lot.name,v_lot.sector,v_total,v_status,v_event.pix_key,v_event.raffle_enabled,v_event.raffle_prize,v_at;
end; $$;

create or replace function public.portaria_device_confirm_door_payment_v19(p_device_key text,p_ticket_id bigint)
returns table(ticket_id bigint,ticket_code text,qr_token text,customer_name text,payment_status text,paid_at timestamptz,raffle_enabled boolean,raffle_prize text)
language plpgsql security definer set search_path='' as $$
declare v_device uuid:=private.hype_device_id(p_device_key); v_ticket public.tickets%rowtype; v_event public.events%rowtype;
begin
  if v_device is null then raise exception 'Computador não autorizado'; end if;
  select t.* into v_ticket from public.tickets t where t.id=p_ticket_id for update;
  if not found then raise exception 'Venda não encontrada'; end if;
  if v_ticket.sale_origin<>'portaria' or v_ticket.door_device_id is distinct from v_device then raise exception 'Sem permissão para confirmar esta venda'; end if;
  if v_ticket.payment_status in('Cancelado','Estornado') then raise exception 'Ingresso cancelado'; end if;
  update public.tickets t set payment_status='Pago',paid_at=coalesce(t.paid_at,now()) where t.id=v_ticket.id returning * into v_ticket;
  select e.* into v_event from public.events e where e.id=v_ticket.event_id;
  perform private.hype_portaria_log(v_device,v_ticket.id,'DOOR_PAYMENT_CONFIRMED',jsonb_build_object('price',v_ticket.price));
  return query select v_ticket.id,v_ticket.ticket_code,v_ticket.qr_token,v_ticket.customer_name,v_ticket.payment_status,v_ticket.paid_at,v_event.raffle_enabled,v_event.raffle_prize;
end; $$;

create or replace function public.portaria_device_cancel_door_order_v19(p_device_key text,p_ticket_id bigint)
returns boolean language plpgsql security definer set search_path='' as $$
declare v_device uuid:=private.hype_device_id(p_device_key); v_ticket public.tickets%rowtype;
begin
  if v_device is null then raise exception 'Computador não autorizado'; end if;
  select t.* into v_ticket from public.tickets t where t.id=p_ticket_id for update;
  if not found then raise exception 'Venda não encontrada'; end if;
  if v_ticket.sale_origin<>'portaria' or v_ticket.door_device_id is distinct from v_device then raise exception 'Sem permissão para cancelar esta venda'; end if;
  if v_ticket.payment_status='Pago' then raise exception 'Venda já paga. Cancele pelo Admin'; end if;
  update public.tickets t set payment_status='Cancelado',canceled_at=now() where t.id=v_ticket.id;
  perform private.hype_portaria_log(v_device,v_ticket.id,'DOOR_ORDER_CANCELED');
  return true;
end; $$;

create or replace function public.staff_list_portaria_readers_v20(p_username text,p_password text)
returns table(reader_id uuid,device_id uuid,device_label text,reader_label text,connected_at timestamptz,last_scan_at timestamptz,expires_at timestamptz,active boolean)
language plpgsql security definer set search_path='' as $$
begin
  perform private.hype_require_staff(p_username,p_password,array['admin']);
  return query select r.id,d.id,d.label,r.reader_label,r.connected_at,r.last_scan_at,r.expires_at,
    (r.active and r.revoked_at is null and d.active and d.revoked_at is null and (r.expires_at is null or r.expires_at>clock_timestamp()))
  from public.portaria_readers_v19 r join public.portaria_devices_v18 d on d.id=r.device_id order by r.active desc,r.connected_at desc;
end; $$;

create or replace function public.staff_revoke_portaria_reader_v20(p_username text,p_password text,p_reader_id uuid)
returns boolean language plpgsql security definer set search_path='' as $$
begin
  perform private.hype_require_staff(p_username,p_password,array['admin']);
  update public.portaria_readers_v19 r set active=false,revoked_at=now() where r.id=p_reader_id;
  if not found then raise exception 'Leitor não encontrado'; end if;
  return true;
end; $$;

create or replace function public.staff_list_access_devices_v23(p_username text,p_password text)
returns table(item_type text,item_id uuid,request_code text,label text,device_label text,active boolean,connected_at timestamptz,last_seen timestamptz,expires_at timestamptz)
language plpgsql security definer set search_path='' as $$
begin
  perform private.hype_require_staff(p_username,p_password,array['admin']);
  return query select access.* from (
    select 'computer'::text as item_type,d.id as item_id,d.request_code,d.label,d.label as device_label,
      (d.active and d.revoked_at is null) as active,d.approved_at as connected_at,d.last_seen,null::timestamptz as expires_at
    from public.portaria_devices_v18 d
    union all
    select 'reader'::text,r.id,null::text,r.reader_label,d.label,
      (r.active and r.revoked_at is null and d.active and d.revoked_at is null and (r.expires_at is null or r.expires_at>clock_timestamp())),
      r.connected_at,r.last_scan_at,r.expires_at
    from public.portaria_readers_v19 r join public.portaria_devices_v18 d on d.id=r.device_id
  ) access order by access.item_type,access.connected_at desc nulls last;
end; $$;

create or replace function public.staff_delete_access_item_v42_5(p_username text,p_password text,p_item_type text,p_item_id text)
returns table(ok boolean,message text)
language plpgsql security definer set search_path='' as $$
declare v_id uuid;
begin
  perform private.hype_require_staff(p_username,p_password,array['admin']);
  begin v_id:=p_item_id::uuid; exception when others then raise exception 'Identificador inválido'; end;
  if p_item_type='reader' then
    delete from public.portaria_readers_v19 r where r.id=v_id;
    if not found then raise exception 'Leitor não encontrado'; end if;
    return query select true,'Celular leitor excluído'::text;
  elsif p_item_type='computer' then
    delete from public.portaria_devices_v18 d where d.id=v_id;
    if not found then raise exception 'Computador não encontrado'; end if;
    return query select true,'Computador da Portaria excluído'::text;
  else raise exception 'Tipo de acesso inválido';
  end if;
end; $$;

create or replace function public.staff_clear_access_devices_v42_5(p_username text,p_password text,p_mode text)
returns table(ok boolean,deleted_count integer,message text)
language plpgsql security definer set search_path='' as $$
declare v_count integer:=0; v_part integer:=0;
begin
  perform private.hype_require_staff(p_username,p_password,array['admin']);
  if p_mode='all_readers' then
    delete from public.portaria_readers_v19; get diagnostics v_count=row_count;
    return query select true,v_count,format('%s leitor(es) excluído(s)',v_count); return;
  elsif p_mode='inactive' then
    delete from public.portaria_readers_v19 r where not r.active or r.revoked_at is not null or (r.expires_at is not null and r.expires_at<=clock_timestamp());
    get diagnostics v_count=row_count;
    delete from public.portaria_devices_v18 d where (not d.active or d.revoked_at is not null) and d.created_at<now()-interval '1 hour';
    get diagnostics v_part=row_count; v_count:=v_count+v_part;
    return query select true,v_count,format('%s acesso(s) antigo(s) excluído(s)',v_count); return;
  else raise exception 'Modo de limpeza inválido';
  end if;
end; $$;

create or replace function public.staff_portaria_dashboard_v16_9(p_username text,p_password text,p_event_id bigint default null)
returns table(event_id bigint,event_name text,event_date date,total_paid bigint,entered_count bigint,remaining_count bigint,female_entered bigint,male_entered bigint,sector_stats jsonb,recent_entries jsonb)
language plpgsql security definer set search_path='' as $$
declare v_event public.events%rowtype; v_data jsonb; v_today date:=(clock_timestamp() at time zone 'America/Sao_Paulo')::date;
begin
  perform private.hype_require_staff(p_username,p_password,array['admin','portaria']);
  if p_event_id is not null then select e.* into v_event from public.events e where e.id=p_event_id;
  else select e.* into v_event from public.events e where e.active order by abs(coalesce(e.event_date,v_today)-v_today),e.event_date,e.id limit 1; end if;
  if not found then return; end if;
  v_data:=private.hype_portaria_dashboard(v_event.id);
  return query select v_event.id,v_event.name,v_event.event_date,(v_data->>'total_paid')::bigint,(v_data->>'entered_count')::bigint,
    (v_data->>'remaining_count')::bigint,(v_data->>'female_entered')::bigint,(v_data->>'male_entered')::bigint,
    v_data->'sector_stats',v_data->'recent';
end; $$;

create or replace function public.staff_live_checkin_v34(p_username text,p_password text,p_event_id bigint)
returns jsonb language plpgsql security definer set search_path='' as $$
declare v_event public.events%rowtype; v_paid bigint; v_entered bigint; v_inside bigint; v_out bigint; v_remaining bigint; v_reentries bigint; v_last bigint; v_timeline jsonb;
begin
  perform private.hype_require_staff(p_username,p_password,array['admin','gerente','caixa']);
  select e.* into v_event from public.events e where e.id=p_event_id;
  if not found then raise exception 'Evento não encontrado'; end if;
  select count(*) filter(where t.payment_status='Pago'),
    count(*) filter(where t.payment_status='Pago' and t.entry_at is not null),
    count(*) filter(where t.payment_status='Pago' and t.entry_status='Entrada utilizada' and not t.temporary_exit),
    count(*) filter(where t.payment_status='Pago' and t.temporary_exit),
    count(*) filter(where t.payment_status='Pago' and t.entry_at is null),
    coalesce(sum(t.reentry_count) filter(where t.payment_status='Pago'),0)
  into v_paid,v_entered,v_inside,v_out,v_remaining,v_reentries from public.tickets t where t.event_id=p_event_id;
  select coalesce(max(l.id),0) into v_last from public.portaria_logs_v18 l join public.tickets t on t.id=l.ticket_id
  where t.event_id=p_event_id and l.action in('ENTRY','TEMPORARY_EXIT','REENTRY');
  select coalesce(jsonb_agg(to_jsonb(x) order by x.created_at,x.id),'[]'::jsonb) into v_timeline from (
    select l.id,l.created_at as at,l.created_at,l.action,
      greatest(sum(case when l.action in('ENTRY','REENTRY') then 1 when l.action='TEMPORARY_EXIT' then -1 else 0 end)
      over(order by l.created_at,l.id rows between unbounded preceding and current row),0)::bigint as inside
    from public.portaria_logs_v18 l join public.tickets t on t.id=l.ticket_id
    where t.event_id=p_event_id and l.action in('ENTRY','TEMPORARY_EXIT','REENTRY') order by l.created_at desc,l.id desc limit 500
  ) x;
  return jsonb_build_object('event_id',v_event.id,'event_name',v_event.name,'event_date',v_event.event_date,'paid_total',v_paid,
    'entered_total',v_entered,'inside_now',v_inside,'temporary_out',v_out,'remaining',v_remaining,'reentries',v_reentries,
    'last_log_id',v_last,'timeline',v_timeline,'server_time',now());
end; $$;

create or replace function public.hype_chat_send_v41(p_sender_role text,p_sender_name text,p_message text)
returns bigint language plpgsql security definer set search_path='' as $$
declare v_role text:=lower(trim(coalesce(p_sender_role,''))); v_name text:=trim(coalesce(p_sender_name,'')); v_message text:=trim(coalesce(p_message,'')); v_id bigint;
begin
  if v_role not in('admin','portaria') then raise exception 'Origem do chat inválida'; end if;
  if v_name='' then v_name:=case when v_role='admin' then 'Admin' else 'Portaria' end; end if;
  if v_message='' then raise exception 'Digite uma mensagem'; end if;
  if length(v_message)>1200 then raise exception 'Mensagem muito longa'; end if;
  insert into public.internal_chat_v41(sender_role,sender_name,message_text) values(v_role,left(v_name,80),v_message) returning id into v_id;
  return v_id;
end; $$;

create or replace function public.hype_chat_list_v41(p_after_id bigint default 0)
returns table(message_id bigint,sender_role text,sender_name text,message_text text,created_at timestamptz)
language plpgsql security definer set search_path='' as $$
begin
  if coalesce(p_after_id,0)>0 then
    return query select c.id,c.sender_role,c.sender_name,c.message_text,c.created_at from public.internal_chat_v41 c
    where c.id>p_after_id order by c.id limit 120;
  else
    return query select c.id,c.sender_role,c.sender_name,c.message_text,c.created_at from public.internal_chat_v41 c
    where c.id in(select recent.id from public.internal_chat_v41 recent order by recent.id desc limit 120) order by c.id;
  end if;
end; $$;

create or replace function public.hype_chat_state_v41()
returns table(last_cleared_at timestamptz)
language sql security definer stable set search_path='' as $$
  select s.last_cleared_at from public.internal_chat_state_v41 s where s.singleton;
$$;

create or replace function public.hype_chat_clear_v41(p_username text,p_password text)
returns table(cleared_at timestamptz,deleted_count integer)
language plpgsql security definer set search_path='' as $$
declare v_staff public.staff_users%rowtype; v_at timestamptz:=now(); v_count integer;
begin
  v_staff:=private.hype_require_staff(p_username,p_password,array['admin']);
  delete from public.internal_chat_v41; get diagnostics v_count=row_count;
  update public.internal_chat_state_v41 s set last_cleared_at=v_at,last_cleared_by=v_staff.username where s.singleton;
  return query select v_at,v_count;
end; $$;

alter table public.portaria_scan_queue_v18 replica identity full;
alter table public.internal_chat_v41 replica identity full;
alter publication supabase_realtime add table public.portaria_scan_queue_v18;
alter publication supabase_realtime add table public.internal_chat_v41;

grant execute on function public.portaria_device_request_v18(text,text) to anon,authenticated;
grant execute on function public.portaria_device_status_v18(text) to anon,authenticated;
grant execute on function public.staff_list_portaria_devices_v18(text,text) to anon,authenticated;
grant execute on function public.staff_approve_portaria_device_v18(text,text,text,text) to anon,authenticated;
grant execute on function public.staff_revoke_portaria_device_v18(text,text,uuid) to anon,authenticated;
grant execute on function public.portaria_create_pair_v18(text,text) to anon,authenticated;
grant execute on function public.portaria_create_pair_v19(text,text) to anon,authenticated;
grant execute on function public.portaria_claim_pair_v18(text,text) to anon,authenticated;
grant execute on function public.portaria_claim_pair_v19(text,text,text) to anon,authenticated;
grant execute on function public.portaria_device_create_reader_link_v20(text,text,text) to anon,authenticated;
grant execute on function public.portaria_claim_reader_link_v20(text,text,text) to anon,authenticated;
grant execute on function public.portaria_reader_submit_v18(text,text) to anon,authenticated;
grant execute on function public.portaria_reader_submit_v19(text,text) to anon,authenticated;
grant execute on function public.portaria_reader_submit_v31(text,text) to anon,authenticated;
grant execute on function public.portaria_reader_status_v25(text) to anon,authenticated;
grant execute on function public.portaria_device_list_readers_v19(text) to anon,authenticated;
grant execute on function public.portaria_device_disconnect_reader_v19(text,uuid) to anon,authenticated;
grant execute on function public.portaria_device_end_readers_v18(text) to anon,authenticated;
grant execute on function public.portaria_device_pull_scan_v18(text) to anon,authenticated;
grant execute on function public.portaria_device_pull_scan_v29(text,bigint) to anon,authenticated;
grant execute on function public.portaria_device_pull_scan_v31(text) to anon,authenticated;
grant execute on function public.portaria_current_event_v32(text) to anon,authenticated;
grant execute on function public.portaria_device_lookup_v18(text,text) to anon,authenticated;
grant execute on function public.portaria_device_lookup_event_v26(text,bigint,text) to anon,authenticated;
grant execute on function public.portaria_device_qr_event_v30(text,text) to anon,authenticated;
grant execute on function public.portaria_device_search_v18(text,bigint,text) to anon,authenticated;
grant execute on function public.portaria_device_snapshot_v18(text,bigint) to anon,authenticated;
grant execute on function public.portaria_device_dashboard_v18(text,bigint) to anon,authenticated;
grant execute on function public.portaria_device_document_v18(text,bigint,boolean) to anon,authenticated;
grant execute on function public.portaria_device_temporary_exit_v18(text,bigint) to anon,authenticated;
grant execute on function public.portaria_device_reentry_v18(text,bigint,boolean) to anon,authenticated;
grant execute on function public.portaria_device_validate_v18(text,bigint,text) to anon,authenticated;
grant execute on function public.portaria_device_sales_context_v19(text,bigint) to anon,authenticated;
grant execute on function public.portaria_device_create_door_order_v19(text,bigint,bigint,text,text,text,text,text) to anon,authenticated;
grant execute on function public.portaria_device_confirm_door_payment_v19(text,bigint) to anon,authenticated;
grant execute on function public.portaria_device_cancel_door_order_v19(text,bigint) to anon,authenticated;
grant execute on function public.staff_list_portaria_readers_v20(text,text) to anon,authenticated;
grant execute on function public.staff_revoke_portaria_reader_v20(text,text,uuid) to anon,authenticated;
grant execute on function public.staff_list_access_devices_v23(text,text) to anon,authenticated;
grant execute on function public.staff_delete_access_item_v42_5(text,text,text,text) to anon,authenticated;
grant execute on function public.staff_clear_access_devices_v42_5(text,text,text) to anon,authenticated;
grant execute on function public.staff_lookup_ticket_v17(text,text,text) to anon,authenticated;
grant execute on function public.staff_lookup_ticket(text,text,text) to anon,authenticated;
grant execute on function public.staff_mark_document_v17(text,text,bigint,boolean) to anon,authenticated;
grant execute on function public.staff_temporary_exit_v17(text,text,bigint) to anon,authenticated;
grant execute on function public.staff_authorize_reentry_v17(text,text,bigint,boolean) to anon,authenticated;
grant execute on function public.staff_validate_entry_v17(text,text,text,text,boolean) to anon,authenticated;
grant execute on function public.staff_validate_entry(text,text,text,text) to anon,authenticated;
grant execute on function public.staff_offline_snapshot_v17(text,text,bigint) to anon,authenticated;
grant execute on function public.staff_portaria_dashboard_v16_9(text,text,bigint) to anon,authenticated;
grant execute on function public.staff_live_checkin_v34(text,text,bigint) to anon,authenticated;
grant execute on function public.hype_chat_send_v41(text,text,text) to anon,authenticated;
grant execute on function public.hype_chat_list_v41(bigint) to anon,authenticated;
grant execute on function public.hype_chat_state_v41() to anon,authenticated;
grant execute on function public.hype_chat_clear_v41(text,text) to anon,authenticated;
