-- Hype Ingressos: private support for payment, email, and push Edge Functions.

alter table public.tickets
  add column refund_requested_at timestamptz,
  add column refund_asaas_payment_id text,
  add column free_reason text;

create table public.payment_webhook_events (
  id bigint generated by default as identity primary key,
  provider text not null default 'asaas',
  provider_event_id text not null unique,
  event_name text not null,
  payment_id text,
  external_reference text,
  ticket_id bigint references public.tickets(id) on delete set null,
  payload_hash text not null,
  status text not null default 'processing' check (status in ('processing','processed','ignored','failed')),
  error_message text,
  received_at timestamptz not null default now(),
  processed_at timestamptz
);

create table public.hype_chat_push_subscriptions_v42 (
  id bigint generated by default as identity primary key,
  endpoint text not null unique,
  p256dh text not null,
  auth text not null,
  role text not null check (role in ('admin','portaria')),
  user_agent text not null default '',
  active boolean not null default true,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  last_seen_at timestamptz not null default now(),
  disabled_at timestamptz
);

create index hype_payment_webhook_ticket_idx on public.payment_webhook_events(ticket_id);
create index hype_payment_webhook_payment_idx on public.payment_webhook_events(payment_id);
create index hype_push_active_role_idx on public.hype_chat_push_subscriptions_v42(active,role);

alter table public.payment_webhook_events enable row level security;
alter table public.hype_chat_push_subscriptions_v42 enable row level security;

revoke all on all tables in schema public from anon, authenticated;
revoke all on all sequences in schema public from anon, authenticated;
